/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef NGINX_MARKDOWN_CONVERTER_H
#define NGINX_MARKDOWN_CONVERTER_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. */
/* Any manual changes will be overwritten on next build. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success - no error occurred.
 */
#define ERROR_SUCCESS 0

/**
 * HTML parsing failed (malformed HTML, invalid structure).
 */
#define ERROR_PARSE 1

/**
 * Character encoding error (invalid UTF-8, unsupported charset).
 */
#define ERROR_ENCODING 2

/**
 * Conversion timeout exceeded.
 */
#define ERROR_TIMEOUT 3

/**
 * Memory limit exceeded during conversion.
 */
#define ERROR_MEMORY_LIMIT 4

/**
 * Invalid input data (NULL pointers, invalid parameters).
 */
#define ERROR_INVALID_INPUT 5

/**
 * Internal error (unexpected condition, panic caught).
 */
#define ERROR_INTERNAL 99

/**
 * Opaque handle to Rust converter state shared across conversions.
 */
typedef struct MarkdownConverterHandle MarkdownConverterHandle;

/**
 * Conversion options passed from C to Rust.
 */
typedef struct MarkdownOptions {
  uint32_t flavor;
  uint32_t timeout_ms;
  uint8_t generate_etag;
  uint8_t estimate_tokens;
  uint8_t front_matter;
  const uint8_t *content_type;
  uintptr_t content_type_len;
  const uint8_t *base_url;
  uintptr_t base_url_len;
} MarkdownOptions;

/**
 * Conversion result returned from Rust to C.
 */
typedef struct MarkdownResult {
  uint8_t *markdown;
  uintptr_t markdown_len;
  uint8_t *etag;
  uintptr_t etag_len;
  uint32_t token_estimate;
  uint32_t error_code;
  uint8_t *error_message;
  uintptr_t error_len;
} MarkdownResult;

/**
 * Allocate a new converter handle for use across multiple FFI calls.
 *
 * # Safety
 *
 * Returns a raw pointer that must eventually be freed with
 * `markdown_converter_free()`.
 *
 * # Returns
 *
 * Returns a non-NULL handle on success. Returns NULL only when
 * `MarkdownConverterHandle::new()` panics and that panic is caught by
 * `catch_unwind()`. On stable Rust, allocator out-of-memory aborts the process
 * instead of unwinding, so OOM is not caught here and does not produce NULL.
 */
struct MarkdownConverterHandle *markdown_converter_new(void);

/**
 * Convert an HTML byte buffer into Markdown using the provided converter handle.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `handle` points to a live converter created by `markdown_converter_new()`
 * - `options` points to a valid `MarkdownOptions`
 * - `result` points to writable storage for a `MarkdownResult` whose owned
 *   buffers are either NULL/zero-length or were previously returned by this API
 * - `html` either points to `html_len` readable bytes or is NULL when `html_len == 0`
 * - `result` is not concurrently mutated while this function is executing
 */
void markdown_convert(struct MarkdownConverterHandle *handle,
                      const uint8_t *html,
                      uintptr_t html_len,
                      const struct MarkdownOptions *options,
                      struct MarkdownResult *result);

/**
 * Release buffers owned by a `MarkdownResult` and reset it to the empty state.
 *
 * # Safety
 *
 * The caller must ensure that `result` either is NULL or points to a valid
 * `MarkdownResult` previously initialized by `markdown_convert()`. Passing the
 * same result twice is allowed because the function resets pointers to NULL.
 */
void markdown_result_free(struct MarkdownResult *result);

/**
 * Destroy a converter handle previously returned by `markdown_converter_new()`.
 *
 * # Safety
 *
 * The caller must ensure that `handle` either is NULL or was returned by
 * `markdown_converter_new()` and has not already been freed. The handle must
 * not be used after this call returns.
 */
void markdown_converter_free(struct MarkdownConverterHandle *handle);

#endif  /* NGINX_MARKDOWN_CONVERTER_H */
