/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef NGINX_MARKDOWN_CONVERTER_H
#define NGINX_MARKDOWN_CONVERTER_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. */
/* Any manual changes will be overwritten on next build. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Total number of reason code variants.
 *
 * This constant is used by the closure test to verify that all variants
 * are accounted for in the `ALL` array. Update this when adding variants.
 */
#define REASON_CODE_COUNT 26

/**
 * Number of error class variants.
 */
#define ERROR_CLASS_COUNT 10

/**
 * Success - no error occurred.
 */
#define ERROR_SUCCESS 0

/**
 * HTML parsing failed (malformed HTML, invalid structure).
 */
#define ERROR_PARSE 1

/**
 * Character encoding error (invalid UTF-8, unsupported charset).
 */
#define ERROR_ENCODING 2

/**
 * Conversion timeout exceeded.
 */
#define ERROR_TIMEOUT 3

/**
 * Memory limit exceeded during conversion.
 */
#define ERROR_MEMORY_LIMIT 4

/**
 * Invalid input data (NULL pointers, invalid parameters).
 */
#define ERROR_INVALID_INPUT 5

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Memory budget exceeded during streaming conversion.
 */
#define ERROR_BUDGET_EXCEEDED 6
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Streaming engine requests fallback to full-buffer conversion (Pre-Commit only).
 */
#define ERROR_STREAMING_FALLBACK 7
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Error after the streaming engine has already emitted partial output (Post-Commit).
 */
#define ERROR_POST_COMMIT 8
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Post-commit safe finish: return code from `markdown_streaming_safe_finish`.
 *
 * Indicates that all open Markdown structures were successfully closed.
 * The output buffer contains the closing Markdown text (fences, newlines, etc.)
 * that the C caller should append after the already-committed output.
 *
 * Corresponds to design doc FFI Return Code 3 (Post-commit safe finish required
 * was handled successfully).
 */
#define POST_COMMIT_SAFE_FINISH 3
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Post-commit abort required: return code from `markdown_streaming_safe_finish`.
 *
 * Indicates that the open Markdown structures could NOT be safely closed
 * (e.g., emitter budget exceeded during closure attempt). The C caller must
 * abort and discard or truncate the partial output. C MUST NOT infer or
 * synthesize Markdown closure for Rust-owned parser/emitter state.
 *
 * Corresponds to design doc FFI Return Code 4 (Post-commit abort required).
 */
#define POST_COMMIT_ABORT 4
#endif

/**
 * Decompression budget exceeded (decompressed output exceeds decompress_max_size).
 */
#define ERROR_DECOMPRESSION_BUDGET_EXCEEDED 9

/**
 * Parse timeout: HTML parsing exceeded the configured deadline.
 */
#define ERROR_PARSE_TIMEOUT 10

/**
 * Parse budget exceeded: parser memory allocation exceeded parser_memory_budget.
 */
#define ERROR_PARSE_BUDGET_EXCEEDED 11

/**
 * Decompression format error (invalid or corrupt compressed data).
 */
#define ERROR_DECOMPRESSION_FORMAT_ERROR 12

/**
 * Decompression truncated input (incomplete compressed stream).
 */
#define ERROR_DECOMPRESSION_TRUNCATED_INPUT 13

/**
 * Decompression I/O error (unexpected failure during decompression).
 */
#define ERROR_DECOMPRESSION_IO_ERROR 14

/**
 * Internal error (unexpected condition, panic caught).
 */
#define ERROR_INTERNAL 99

/**
 * Decompression error category: budget exceeded.
 *
 * These constants are used in `FFIDecompResult.error_category` and as
 * the return value of `markdown_decompress_bounded`. They occupy a
 * separate namespace from `ERROR_*` (which are for `MarkdownResult.error_code`).
 * Values start at 101 to avoid numeric overlap with the ERROR_* range (0-99).
 */
#define DECOMP_CATEGORY_BUDGET_EXCEEDED 101

/**
 * Decompression error category: invalid compression format.
 */
#define DECOMP_CATEGORY_FORMAT_ERROR 102

/**
 * Decompression error category: truncated input stream.
 */
#define DECOMP_CATEGORY_TRUNCATED_INPUT 103

/**
 * Decompression error category: I/O error during decompression.
 */
#define DECOMP_CATEGORY_IO_ERROR 104

/**
 * Decompression error category: invalid arguments (NULL pointers, unknown format).
 */
#define DECOMP_CATEGORY_INVALID_ARGS 105

/**
 * Reason code: client prefers text/markdown, proceed with conversion.
 */
#define NEGOTIATE_REASON_CONVERT 0

/**
 * Reason code: no Accept header was present.
 */
#define NEGOTIATE_REASON_NO_ACCEPT 1

/**
 * Reason code: text/markdown has lower q-value than text/html.
 */
#define NEGOTIATE_REASON_LOWER_Q 2

/**
 * Reason code: client explicitly set text/markdown;q=0.
 */
#define NEGOTIATE_REASON_EXPLICIT_REJECT 3

/**
 * Reason code: Accept header is malformed.
 */
#define NEGOTIATE_REASON_MALFORMED 4

/**
 * Wildcard mode: strict — wildcard MIME type does NOT match text/markdown.
 */
#define NEGOTIATE_WILDCARD_STRICT 0

/**
 * Wildcard mode: allow — wildcard MIME type matches text/markdown.
 */
#define NEGOTIATE_WILDCARD_ALLOW 1

/**
 * `markdown_trusted_proxies_push` result: CIDR parsed and stored.
 */
#define TRUSTED_PROXIES_PUSH_OK 0

/**
 * `markdown_trusted_proxies_push` result: CIDR string was invalid.
 */
#define TRUSTED_PROXIES_PUSH_INVALID_CIDR 1

/**
 * `markdown_trusted_proxies_push` result: NULL handle or input.
 */
#define TRUSTED_PROXIES_PUSH_NULL 2

/**
 * `markdown_decide_base_url` result: decision written successfully.
 */
#define DECIDE_BASE_URL_OK 0

/**
 * `markdown_decide_base_url` result: NULL input/output or buffer too small.
 */
#define DECIDE_BASE_URL_INVALID 1

/**
 * `markdown_decide_streaming` sentinel: no block reason (request is
 * streaming-eligible).
 */
#define STREAMING_BLOCK_REASON_NONE 255

/**
 * Sentinel value for "not set" in FFI enum fields (u8).
 */
#define FFI_CONFIG_NOT_SET_U8 255

/**
 * Sentinel value for "not set" in FFI u64 fields.
 */
#define FFI_CONFIG_NOT_SET_U64 UINT64_MAX

/**
 * Sentinel value for "not set" in FFI u32 fields.
 */
#define FFI_CONFIG_NOT_SET_U32 UINT32_MAX

/**
 * Profile discriminant: no profile active (use built-in defaults).
 */
#define FFI_PROFILE_NONE 0

/**
 * Profile discriminant: `strict_cache` (CDN/caching proxy).
 */
#define FFI_PROFILE_STRICT_CACHE 1

/**
 * Profile discriminant: `balanced` (recommended default).
 */
#define FFI_PROFILE_BALANCED 2

/**
 * Profile discriminant: `streaming_first` (AI agent workloads).
 */
#define FFI_PROFILE_STREAMING_FIRST 3

/**
 * FFI error policy kind: pass (fail-open, default).
 */
#define FFI_ERROR_POLICY_PASS 0

/**
 * FFI error policy kind: return specified status code.
 */
#define FFI_ERROR_POLICY_STATUS 1

/**
 * FFI error policy kind: fail_closed (return 502).
 */
#define FFI_ERROR_POLICY_FAIL_CLOSED 2

/**
 * FFI error behavior kind: pass through original response.
 */
#define FFI_ERROR_BEHAVIOR_PASS_THROUGH 0

/**
 * FFI error behavior kind: return specified HTTP status code.
 */
#define FFI_ERROR_BEHAVIOR_RETURN_STATUS 1

/**
 * FFI error behavior kind: terminate connection (post-commit).
 */
#define FFI_ERROR_BEHAVIOR_TERMINATE 2

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Maximum accumulated buffer size in bytes (64 MiB).
 */
#define IncrementalConverter_MAX_BUFFER_SIZE ((64 * 1024) * 1024)
#endif

/**
 * Severity level for a detected configuration conflict (FFI-safe).
 *
 * Mirrors `crate::config::conflict::ConflictLevel` with a stable `#[repr(u8)]`
 * layout for the C side.
 */
enum FFIConflictLevel {
  /**
   * Hard error — `nginx -t` must fail.
   */
  Error = 0,
  /**
   * Advisory warning — logged but does not block startup.
   */
  Warning = 1,
};
typedef uint8_t FFIConflictLevel;

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Opaque handle wrapping an [`IncrementalConverter`] for the C ABI.
 *
 * The handle is produced by [`markdown_incremental_new`] and consumed by
 * either [`markdown_incremental_finalize`] (which produces output) or
 * [`markdown_incremental_free`] (which drops without output).  The C caller
 * owns the handle for its entire lifetime.
 *
 * # Fields (FFI boundary semantics)
 *
 * * `inner` — The [`IncrementalConverter`] instance that accumulates input
 *   chunks and performs the conversion.  Owned by the handle; moved into
 *   on construction and consumed on finalization.
 * * `generate_etag` — Whether to compute and emit a BLAKE3-based ETag in
 *   the final result.  Set once at construction from `MarkdownOptions`;
 *   immutable thereafter.
 * * `estimate_tokens` — Whether to run LLM token-count estimation in the
 *   final result.  Set once at construction from `MarkdownOptions`.
 * * `chars_per_token` — The average characters-per-token ratio used by
 *   [`TokenEstimator`] when `estimate_tokens` is true.  Stored as `f32`
 *   with typical values 1.0–4.0 (CJK–English).  This value is the
 *   **normalized** form (clamped to `[1.0, 100.0]` by
 *   [`clamp_chars_per_token`](super::options::clamp_chars_per_token))
 *   rather than the raw FFI input, so all token-estimation paths behave
 *   consistently.
 */
typedef struct IncrementalConverterHandle IncrementalConverterHandle;
#endif

/**
 * Opaque handle to a reusable Rust converter instance shared across FFI calls.
 *
 * This struct holds stateful components (ETag generator, token estimator) that
 * are reused across multiple conversions to avoid re-initialization overhead.
 * The handle is created via `markdown_converter_new()` and freed via
 * `markdown_converter_free()` on the C side.
 *
 * # Thread Safety
 *
 * This handle is NOT thread-safe. The caller must ensure exclusive access
 * when using a handle across multiple FFI calls.
 */
typedef struct MarkdownConverterHandle MarkdownConverterHandle;

/**
 * Opaque Rust-owned set of config-time-validated trusted-proxy CIDRs
 * (spec 47).
 *
 * The C side creates one handle per `markdown_trusted_proxies` directive via
 * `markdown_trusted_proxies_new`, appends each CIDR with
 * `markdown_trusted_proxies_push` (which validates at config time), and frees
 * it with `markdown_trusted_proxies_free` (registered as an NGINX pool
 * cleanup handler).  CIDR parsing happens once here; request-time matching is
 * pure bitwise prefix comparison.  This type is intentionally **not**
 * `#[repr(C)]` — cbindgen emits it as an opaque struct so the C side only
 * ever holds a pointer and never inspects the layout.
 */
typedef struct MarkdownTrustedProxies MarkdownTrustedProxies;

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Opaque handle wrapping a [`StreamingConverter`] for the C ABI.
 */
typedef struct StreamingConverterHandle StreamingConverterHandle;
#endif

/**
 * Conversion options passed from C to Rust.
 *
 * This full-buffer ABI keeps its own explicit `#[repr(C)]` layout instead of
 * sharing fields with `StreamingOptions`. The duplicate option fields are an
 * intentional FFI stability tradeoff: full-buffer and streaming callers each
 * get a clear, independently versioned C contract. Any shared semantic change
 * must update both structs, generated headers, layout tests, and docs in the
 * same change set; structural reuse belongs in a future breaking ABI version.
 */
typedef struct MarkdownOptions {
  /**
   * Markdown flavor selector.
   *
   * `0` selects CommonMark-compatible output, `1` selects the GFM
   * extension set, `2` selects experimental MDX-oriented behavior, and `3`
   * selects experimental Org-mode-oriented behavior. Other values are
   * rejected during option decoding.
   */
  uint32_t flavor;
  /**
   * Cooperative conversion timeout in milliseconds.
   *
   * `0` disables the deadline. The value is copied from C at call entry and
   * is not retained after the FFI call returns.
   */
  uint32_t timeout_ms;
  /**
   * Non-zero when Rust should generate a Markdown-variant ETag.
   */
  uint8_t generate_etag;
  /**
   * Non-zero when Rust should estimate token count/savings.
   */
  uint8_t estimate_tokens;
  /**
   * Non-zero when Rust should extract YAML front matter metadata.
   */
  uint8_t front_matter;
  /**
   * Borrowed Content-Type bytes from the C caller.
   *
   * Must either be NULL with `content_type_len == 0` or point to
   * `content_type_len` readable bytes for the duration of the FFI call.
   * Rust never takes ownership of this buffer.
   */
  const uint8_t *content_type;
  /**
   * Length in bytes of [`MarkdownOptions::content_type`].
   */
  uintptr_t content_type_len;
  /**
   * Borrowed base URL bytes used for resolving relative links.
   *
   * Must either be NULL with `base_url_len == 0` or point to
   * `base_url_len` readable UTF-8 bytes for the duration of the FFI call.
   * Rust copies any value it needs to retain.
   */
  const uint8_t *base_url;
  /**
   * Length in bytes of [`MarkdownOptions::base_url`].
   */
  uintptr_t base_url_len;
  /**
   * Streaming memory budget in bytes (0 = use default).
   *
   * When non-zero, the streaming converter uses this value as the
   * total memory budget instead of the compiled-in default (2 MiB).
   * Populated from `markdown_limits streaming_buffer=<size>` (Config V2).
   */
  uint64_t streaming_budget;
  /**
   * Non-zero when noise region pruning is enabled at runtime.
   *
   * When non-zero, structural HTML regions matching the prune selectors
   * are excluded from output. Protection selectors override prune selectors.
   * Populated from the `markdown_prune_noise` NGINX directive.
   */
  uint32_t prune_noise;
  /**
   * Borrowed prune selector string from the C caller.
   *
   * Space-separated tag names for regions to prune (e.g., "nav footer aside").
   * Must either be NULL with `prune_selectors_len == 0` or point to
   * `prune_selector_len` readable UTF-8 bytes for the duration of the FFI call.
   * Rust never takes ownership of this buffer.
   */
  const uint8_t *prune_selectors;
  /**
   * Length in bytes of [`MarkdownOptions::prune_selectors`].
   */
  uintptr_t prune_selector_len;
  /**
   * Borrowed protection selector string from the C caller.
   *
   * Space-separated tag names for regions to protect from pruning.
   * An element matching both a prune selector and a protection selector
   * is kept (protection wins). Must either be NULL with
   * `prune_protection_selector_len == 0` or point to
   * `prune_protection_selector_len` readable UTF-8 bytes.
   */
  const uint8_t *prune_protection_selectors;
  /**
   * Length in bytes of [`MarkdownOptions::prune_protection_selectors`].
   */
  uintptr_t prune_protection_selector_len;
  /**
   * Unified memory budget in bytes (0 = use per-engine defaults).
   *
   * When non-zero, NGINX may use this value to derive full-buffer
   * max_size when no explicit markdown_max_size is set. Rust
   * currently enforces this budget only for streaming/incremental
   * paths; full-buffer relies on NGINX-side buffering limits.
   * Populated from `markdown_limits memory=<size>` (Config V2).
   */
  uint64_t memory_budget;
  /**
   * LLM provider for token estimation (0=default, 1=openai-gpt, 2=anthropic-claude,
   * 3=google-gemini, 4=meta-llama).
   *
   * When non-zero and `estimate_tokens` is enabled, the provider's
   * characteristic chars-per-token ratio overrides the default 4.0.
   * Populated from the `markdown_llm_provider` NGINX directive.
   */
  uint8_t llm_provider;
  /**
   * Explicit chars-per-token ratio for token estimation (0.0 = use default/provider).
   *
   * When non-zero, this value overrides both the default 4.0 and the
   * provider-specific ratio.  Stored as a fixed-point value: actual
   * ratio = `chars_per_token_fixed / 10.0` (e.g., 38 = 3.8 chars/token).
   * Populated from the `markdown_chars_per_token` NGINX directive.
   *
   * # Type rationale
   *
   * `u8` is intentional for FFI ABI compactness (single byte, no padding).
   * Valid range: 1–255, representing ratios 0.1–25.5 chars/token.
   * Value 0 means "use default".  All practical LLM tokenizer ratios
   * (GPT-4: ~3.5, Claude: ~4.0, Gemini: ~3.8) fit within this range.
   */
  uint8_t chars_per_token_fixed;
  /**
   * Parse-specific timeout in milliseconds (0 = use `timeout_ms` fallback).
   *
   * When non-zero, the HTML parser uses this deadline instead of the
   * general `timeout_ms` field.  This allows operators to set a tighter
   * parse-phase budget while keeping a longer overall conversion timeout.
   * Populated from the `markdown_parse_timeout` NGINX directive.
   */
  uint32_t parse_timeout_ms;
  /**
   * Parser memory budget in bytes (0 = unlimited).
   *
   * When non-zero, the HTML parser is constrained to this memory
   * allocation ceiling.  Exceeding the budget produces
   * `ERROR_PARSE_BUDGET_EXCEEDED`.
   * Populated from the `markdown_parser_budget` NGINX directive.
   */
  uint64_t parser_memory_budget;
  /**
   * Streaming flush threshold in bytes (0 = use default threshold).
   *
   * Controls the minimum number of accumulated output bytes before
   * the streaming emitter returns non-empty output to the C caller.
   * Populated from the `markdown_stream_flush_min` NGINX directive.
   */
  uint32_t flush_threshold;
} MarkdownOptions;

/**
 * Conversion result returned from Rust to C.
 */
typedef struct MarkdownResult {
  /**
   * Rust-owned Markdown output buffer.
   *
   * Valid only when `error_code == ERROR_SUCCESS`. The C caller must release
   * it with `markdown_result_free()` and must not mutate it.
   */
  uint8_t *markdown;
  /**
   * Length in bytes of [`MarkdownResult::markdown`].
   */
  uintptr_t markdown_len;
  /**
   * Rust-owned ETag bytes, or NULL when ETag generation was disabled.
   *
   * Valid only when `etag_len > 0` and released by `markdown_result_free()`.
   */
  uint8_t *etag;
  /**
   * Length in bytes of [`MarkdownResult::etag`].
   */
  uintptr_t etag_len;
  /**
   * Estimated token count for successful conversions.
   *
   * `0` means token estimation was disabled or no estimate was produced.
   */
  uint32_t token_estimate;
  /**
   * FFI error code; `ERROR_SUCCESS` means the output fields are valid.
   */
  uint32_t error_code;
  /**
   * Rust-owned UTF-8 diagnostic message for non-success results.
   *
   * The pointer may be NULL when no diagnostic is available. Release through
   * `markdown_result_free()` together with the rest of the result.
   */
  uint8_t *error_message;
  /**
   * Length in bytes of [`MarkdownResult::error_message`].
   */
  uintptr_t error_len;
  /**
   * Peak working-set memory estimate during streaming conversion (bytes).
   *
   * This is derived from converter-owned resident state and is not
   * a process RSS/high-water-mark measurement.
   * Populated by `markdown_streaming_finalize` from
   * `StreamingStats.peak_memory_estimate`.
   */
  uintptr_t peak_memory_estimate;
} MarkdownResult;

/**
 * Result of Accept header content negotiation.
 *
 * Returned by `markdown_negotiate_accept()` for the C caller to decide
 * whether to proceed with HTML-to-Markdown conversion.
 *
 * # Fields
 *
 * - `should_convert`: 1 if the client prefers text/markdown, 0 otherwise.
 * - `reason`: Numeric reason code for the decision.
 *   - 0: Convert (text/markdown preferred)
 *   - 1: No Accept header present
 *   - 2: text/markdown has lower q-value than text/html
 *   - 3: text/markdown;q=0 explicit reject
 *   - 4: Malformed Accept header
 */
typedef struct FFIAcceptResult {
  /**
   * 1 if conversion should proceed, 0 otherwise.
   */
  uint8_t should_convert;
  /**
   * Reason code for the negotiation decision.
   */
  uint8_t reason;
} FFIAcceptResult;

/**
 * Borrowed byte string passed across the FFI boundary.
 *
 * Points to caller-owned memory that must remain valid for the duration of
 * the call. `data` may be NULL only when `len == 0`.
 */
typedef struct FFIStr {
  /**
   * Pointer to the first byte (may be NULL when `len == 0`).
   */
  const uint8_t *data;
  /**
   * Number of bytes.
   */
  uintptr_t len;
} FFIStr;

/**
 * Input snapshot for `markdown_decide_eligibility`.
 *
 * All fields are marshaled from `ngx_http_request_t` and the module
 * configuration by the C caller. Array fields (`content_types`,
 * `stream_types`) point to caller-owned arrays of [`FFIStr`] valid for the
 * duration of the call; a NULL pointer with count 0 means "not configured".
 */
typedef struct FFIEligibilityInput {
  /**
   * 1 if `markdown_filter` is enabled for this request, else 0.
   */
  uint8_t filter_enabled;
  /**
   * 1 if the request method is GET or HEAD, else 0.
   */
  uint8_t method_get_or_head;
  /**
   * 1 if the request carried a `Range` header, else 0.
   */
  uint8_t has_range_header;
  /**
   * Response status code.
   */
  uint16_t status;
  /**
   * Response `Content-Type` value bytes (NULL/0 if absent).
   */
  const uint8_t *content_type;
  /**
   * Length of `content_type`.
   */
  uintptr_t content_type_len;
  /**
   * Configured `markdown_content_types` allowlist (NULL/0 = default html).
   */
  const struct FFIStr *content_types;
  /**
   * Number of entries in `content_types`.
   */
  uintptr_t content_types_count;
  /**
   * Configured `markdown_stream_types` exclusions (NULL/0 = none).
   */
  const struct FFIStr *stream_types;
  /**
   * Number of entries in `stream_types`.
   */
  uintptr_t stream_types_count;
  /**
   * Response `Content-Length`; negative means absent/unknown.
   */
  int64_t content_length;
  /**
   * Effective full-buffer body limit in bytes; 0 means unlimited.
   */
  uintptr_t body_limit;
} FFIEligibilityInput;

/**
 * Result of a conditional request check (If-None-Match / If-Modified-Since).
 *
 * Returned by `markdown_check_conditional` FFI function.
 *
 * Fields:
 * - `result_code`: 0 = not modified (send 304), 1 = proceed (no match or no conditional headers)
 * - `matched_etag_len`: Length of the matched ETag value (reserved, currently always 0)
 */
typedef struct FFIConditionalResult {
  /**
   * 0 = not_modified (send 304), 1 = proceed (modified or no conditional headers)
   */
  uint8_t result_code;
  /**
   * Length of matched ETag value (reserved for future use, currently 0).
   */
  uint32_t matched_etag_len;
} FFIConditionalResult;

/**
 * Input snapshot for `markdown_decide_conditional` (spec 49).
 *
 * All byte fields are borrowed from the C caller for the duration of the
 * call (NULL with length 0 means "absent"). This struct exposes neither
 * `ngx_http_request_t *` nor any NGINX pool; the C side marshals request
 * headers, response metadata, and the effective `cache_validation` mode.
 */
typedef struct FFIConditionalInput {
  /**
   * Effective `markdown_cache_validation` mode: 0 = off, 1 = ims_only,
   * 2 = full. Unknown values fall back to ims_only (safe default).
   */
  uint8_t cache_validation;
  /**
   * 1 if the request carried a `Range` header, else 0.
   */
  uint8_t has_range;
  /**
   * 1 if request or response carried `Cache-Control: no-transform`.
   */
  uint8_t no_transform;
  /**
   * `If-None-Match` header value bytes (NULL/0 if absent).
   */
  const uint8_t *if_none_match;
  /**
   * Length of `if_none_match`.
   */
  uintptr_t if_none_match_len;
  /**
   * Transformed-representation entity ETag bytes (NULL/0 if none; always
   * absent on the streaming path).
   */
  const uint8_t *entity_etag;
  /**
   * Length of `entity_etag`.
   */
  uintptr_t entity_etag_len;
  /**
   * `If-Modified-Since` header value bytes (NULL/0 if absent).
   */
  const uint8_t *if_modified_since;
  /**
   * Length of `if_modified_since`.
   */
  uintptr_t if_modified_since_len;
  /**
   * Preserved upstream `Last-Modified` value bytes (NULL/0 if absent).
   */
  const uint8_t *last_modified;
  /**
   * Length of `last_modified`.
   */
  uintptr_t last_modified_len;
} FFIConditionalInput;

/**
 * Result of `markdown_decide_conditional` (spec 49).
 */
typedef struct FFIConditionalDecision {
  /**
   * `ConditionalOutcome` discriminant: 0 = not_modified (send 304),
   * 1 = proceed, 2 = bypass (deliver upstream unmodified).
   */
  uint8_t outcome;
  /**
   * `ConditionalReason` discriminant (spec 53 alignment).
   */
  uint8_t reason;
  /**
   * `ConditionalHeader` discriminant: 0 = none, 1 = if_none_match,
   * 2 = if_modified_since.
   */
  uint8_t evaluated_header;
} FFIConditionalDecision;

/**
 * Input snapshot for `markdown_decide_streaming` (spec 49).
 *
 * This struct exposes neither `ngx_http_request_t *` nor any NGINX pool;
 * the C side marshals the policy/engine selectors, the effective
 * `cache_validation` mode, request/response flags, and sizing fields.
 */
typedef struct FFIStreamingInput {
  /**
   * `markdown_streaming` policy: 0 = off, 1 = auto, 2 = force.
   */
  uint8_t policy;
  /**
   * `markdown_streaming_engine`: 0 = off, 1 = auto, 2 = on.
   */
  uint8_t engine;
  /**
   * Effective `markdown_cache_validation` mode: 0 = off, 1 = ims_only,
   * 2 = full.
   */
  uint8_t cache_validation;
  /**
   * 1 if the request method is `HEAD`, else 0.
   */
  uint8_t is_head;
  /**
   * 1 if the conditional decision yielded `304 Not Modified`, else 0.
   */
  uint8_t is_not_modified;
  /**
   * 1 if the request carried a `Range` header, else 0.
   */
  uint8_t has_range;
  /**
   * 1 if request or response carried `Cache-Control: no-transform`.
   */
  uint8_t no_transform;
  /**
   * 1 if the upstream response carried a `Content-Encoding`, else 0.
   */
  uint8_t has_content_encoding;
  /**
   * 1 if the upstream `Content-Length` is known, else 0.
   */
  uint8_t content_length_known;
  /**
   * Upstream `Content-Length` in bytes (meaningful when known).
   */
  uint64_t content_length;
  /**
   * `markdown_stream_threshold` in bytes (auto-mode trigger).
   */
  uint64_t streaming_threshold;
} FFIStreamingInput;

/**
 * Result of `markdown_decide_streaming` (spec 49).
 */
typedef struct FFIStreamingDecision {
  /**
   * 1 if the request may take the streaming path, else 0.
   */
  uint8_t eligible;
  /**
   * `StreamingBlockReason` discriminant when `eligible == 0`, or
   * `STREAMING_BLOCK_REASON_NONE` (255) when `eligible == 1`.
   */
  uint8_t block_reason;
} FFIStreamingDecision;

/**
 * Result of a decision engine evaluation.
 *
 * Returned by `markdown_make_decision` FFI function.
 *
 * Fields:
 * - `decision`: 0 = convert, 1 = skip
 * - `reason_code`: Canonical `ReasonCode` discriminant for the decision
 *   (e.g. `Converted` = 0, `SkippedAccept` = 1, `NotEligible` = 14,
 *   `Disabled` = 15). The value can be passed directly to
 *   `markdown_reason_code_str()` / `markdown_reason_code_metric_key()`.
 */
typedef struct FFIDecisionResult {
  /**
   * 0 = convert, 1 = skip
   */
  uint8_t decision;
  /**
   * Canonical `ReasonCode` discriminant for the decision
   * (`Converted` = 0 when `decision` == 0).
   */
  uint8_t reason_code;
} FFIDecisionResult;

/**
 * Opaque Rust-owned handle that keeps header-plan backing storage alive.
 */
typedef struct FFIHeaderPlanHandle {
  uint8_t _private[0];
} FFIHeaderPlanHandle;

/**
 * A single header operation in a header plan.
 *
 * Fields:
 * - `op_type`: 0 = set, 1 = delete, 2 = set-etag-placeholder, 3 = delete-all
 * - `key`: Pointer to header name (NUL-terminated, borrowed from plan; NULL for set-etag-placeholder)
 * - `key_len`: Length of header name
 * - `value`: Pointer to header value (NUL-terminated, borrowed from plan; NULL for delete, delete-all, and set-etag-placeholder)
 * - `value_len`: Length of header value (0 for delete, delete-all, and set-etag-placeholder)
 *
 * For op_type == 2 (set-etag-placeholder), the C caller must substitute
 * the actual ETag value from MarkdownResult.etag instead of reading
 * key/value from the entry. This avoids the fragile empty-string
 * placeholder contract.
 */
typedef struct FFIHeaderEntry {
  /**
   * 0 = set, 1 = delete, 2 = set-etag-placeholder, 3 = delete-all
   */
  uint8_t op_type;
  /**
   * Pointer to header name (borrowed).
   */
  const uint8_t *key;
  /**
   * Length of header name.
   */
  uintptr_t key_len;
  /**
   * Pointer to header value (NULL for delete).
   */
  const uint8_t *value;
  /**
   * Length of header value.
   */
  uintptr_t value_len;
} FFIHeaderEntry;

/**
 * Header plan: an ordered list of header operations for atomic application.
 *
 * Fields:
 * - `handle`: Opaque plan handle owned by Rust
 * - `entries`: Pointer to array of FFIHeaderEntry
 * - `count`: Number of entries in the plan
 */
typedef struct FFIHeaderPlan {
  /**
   * Opaque Rust-owned handle. Free with `markdown_header_plan_free`.
   */
  struct FFIHeaderPlanHandle *handle;
  /**
   * Pointer to header entry array.
   */
  const struct FFIHeaderEntry *entries;
  /**
   * Number of entries.
   */
  uintptr_t count;
} FFIHeaderPlan;

/**
 * Input snapshot for `markdown_decide_base_url` (spec 47).
 *
 * All byte fields are borrowed from the C caller for the duration of the
 * call (NULL with length 0 means "absent").  `trusted` is a borrowed
 * pointer to a [`MarkdownTrustedProxies`] handle (may be NULL when trust is
 * not configured).  This struct intentionally exposes neither
 * `ngx_http_request_t *` nor any NGINX pool.
 */
typedef struct FFIBaseUrlInput {
  /**
   * Textual source IP (`r->connection->addr_text`), realip/PROXY resolved.
   */
  const uint8_t *source_ip;
  /**
   * Length of `source_ip`.
   */
  uintptr_t source_ip_len;
  /**
   * Borrowed handle of config-time-validated trusted CIDRs (may be NULL).
   */
  const struct MarkdownTrustedProxies *trusted;
  /**
   * `Forwarded` header value bytes (RFC 7239), NULL/0 if absent.
   */
  const uint8_t *forwarded;
  /**
   * Length of `forwarded`.
   */
  uintptr_t forwarded_len;
  /**
   * `X-Forwarded-Proto` header value bytes, NULL/0 if absent.
   */
  const uint8_t *x_forwarded_proto;
  /**
   * Length of `x_forwarded_proto`.
   */
  uintptr_t x_forwarded_proto_len;
  /**
   * `X-Forwarded-Host` header value bytes, NULL/0 if absent.
   */
  const uint8_t *x_forwarded_host;
  /**
   * Length of `x_forwarded_host`.
   */
  uintptr_t x_forwarded_host_len;
  /**
   * `Host` header value bytes, NULL/0 if absent.
   */
  const uint8_t *host;
  /**
   * Length of `host`.
   */
  uintptr_t host_len;
  /**
   * 1 if the source is a Unix-domain socket peer (forces untrusted).
   */
  uint8_t is_unix_socket;
  /**
   * 1 if `markdown_trusted_proxies` was configured (even as `off`).
   */
  uint8_t trusted_configured;
} FFIBaseUrlInput;

/**
 * Result of `markdown_decide_base_url` (spec 47).
 *
 * `base_url_len` bytes are written into the caller-provided output buffer.
 * `reason` is a `BaseUrlReason` discriminant; `source` is a `BaseUrlSource`
 * discriminant.
 */
typedef struct FFIBaseUrlDecision {
  /**
   * Bytes written into the caller's output buffer.
   */
  uintptr_t base_url_len;
  /**
   * `BaseUrlReason` discriminant.
   */
  uint8_t reason;
  /**
   * `BaseUrlSource` discriminant.
   */
  uint8_t source;
} FFIBaseUrlDecision;

/**
 * Result of a bounded decompression operation.
 *
 * Returned by decompression FFI functions to communicate the output buffer,
 * its length, and any error category to the C caller.
 *
 * # Error Categories
 *
 * - `0` = success (output is valid decompressed data)
 * - `DECOMP_CATEGORY_BUDGET_EXCEEDED` (101) = decompressed output exceeded the configured limit
 * - `DECOMP_CATEGORY_FORMAT_ERROR` (102) = input is not valid gzip/deflate
 * - `DECOMP_CATEGORY_TRUNCATED_INPUT` (103) = input stream ended prematurely
 * - `DECOMP_CATEGORY_IO_ERROR` (104) = I/O error during decompression
 * - `DECOMP_CATEGORY_INVALID_ARGS` (105) = invalid arguments (NULL pointers, unknown format)
 *
 * # Memory Ownership
 *
 * When `error_category == 0`, the `output` pointer is Rust-owned and must be
 * freed via the corresponding cleanup function. When `error_category != 0`,
 * `output` is NULL and `output_len` is 0.
 */
typedef struct FFIDecompResult {
  /**
   * Pointer to decompressed output buffer (Rust-owned, NULL on error).
   */
  uint8_t *output;
  /**
   * Length of decompressed output in bytes (0 on error).
   */
  uintptr_t output_len;
  /**
   * Error category: 0=success, 101..105 for DECOMP_CATEGORY_* errors.
   * See DECOMP_CATEGORY_BUDGET_EXCEEDED through DECOMP_CATEGORY_INVALID_ARGS.
   */
  uint32_t error_category;
} FFIDecompResult;

/**
 * A single detected configuration conflict (FFI-safe).
 *
 * Contains the severity level and a pointer to a UTF-8 message describing
 * the incompatibility. The message bytes are owned by the containing
 * [`FFIConflictList`] and remain valid until `markdown_free_conflicts`
 * is called.
 */
typedef struct FFIConflict {
  /**
   * Severity: error blocks startup, warning is advisory.
   */
  FFIConflictLevel level;
  /**
   * Pointer to UTF-8 message bytes (NOT NUL-terminated).
   */
  const uint8_t *message;
  /**
   * Length of the message in bytes.
   */
  uintptr_t message_len;
} FFIConflict;

/**
 * List of detected conflicts returned from `markdown_detect_conflicts`.
 *
 * The caller must free this with `markdown_free_conflicts`. When `count == 0`,
 * `conflicts` is NULL (Rule 53: empty results return NULL).
 */
typedef struct FFIConflictList {
  /**
   * Pointer to array of `FFIConflict` entries (NULL when `count == 0`).
   */
  struct FFIConflict *conflicts;
  /**
   * Number of entries in the array.
   */
  uintptr_t count;
} FFIConflictList;

/**
 * Explicit user-set configuration flags for conflict detection (FFI-safe).
 *
 * Each field uses a sentinel value to indicate "not explicitly set":
 * - Enum fields: `255` means not set (valid discriminants are 0..3).
 * - Integer fields: `u64::MAX` / `u32::MAX` means not set.
 * - Boolean fields: `255` means not set (0 = false, 1 = true).
 *
 * The C side populates only fields that the user explicitly configured via
 * `markdown_*` directives; all other fields remain at their sentinel values.
 */
typedef struct FFIExplicitConfig {
  /**
   * `markdown_accept`: 0=strict, 1=wildcard, 2=force; 255=not set.
   */
  uint8_t accept;
  /**
   * `markdown_cache_validation`: 0=off, 1=ims_only, 2=full; 255=not set.
   */
  uint8_t cache_validation;
  /**
   * `markdown_streaming`: 0=off, 1=auto, 2=force; 255=not set.
   */
  uint8_t streaming;
  /**
   * `markdown_limits memory=` in bytes; `u64::MAX`=not set.
   */
  uint64_t limits_memory_bytes;
  /**
   * `markdown_limits timeout=` in milliseconds; `u64::MAX`=not set.
   */
  uint64_t limits_timeout_ms;
  /**
   * `markdown_limits streaming_buffer=` in bytes; `u64::MAX`=not set.
   */
  uint64_t limits_streaming_buffer_bytes;
  /**
   * `markdown_limits max_inflight=`; `u32::MAX`=not set.
   */
  uint32_t limits_max_inflight;
  /**
   * `markdown_error_policy`: 0=pass, 1=fail_closed; 255=not set.
   */
  uint8_t error_policy;
  /**
   * `markdown_diagnostics`: 0=off, 1=on; 255=not set.
   */
  uint8_t diagnostics;
} FFIExplicitConfig;

/**
 * Effective configuration after merge (FFI-safe).
 *
 * All fields are concrete (no sentinels). This is the fully-resolved
 * configuration the C side uses at runtime.
 */
typedef struct FFIEffectiveConfig {
  /**
   * Effective accept mode: 0=strict, 1=wildcard, 2=force.
   */
  uint8_t accept;
  /**
   * Effective cache_validation: 0=off, 1=ims_only, 2=full.
   */
  uint8_t cache_validation;
  /**
   * Effective streaming: 0=off, 1=auto, 2=force.
   */
  uint8_t streaming;
  /**
   * Effective memory limit in bytes.
   */
  uint64_t limits_memory_bytes;
  /**
   * Effective timeout in milliseconds.
   */
  uint64_t limits_timeout_ms;
  /**
   * Effective streaming buffer size in bytes.
   */
  uint64_t limits_streaming_buffer_bytes;
  /**
   * Effective max inflight conversions.
   */
  uint32_t limits_max_inflight;
  /**
   * Effective error policy: 0=pass, 1=fail_closed.
   */
  uint8_t error_policy;
  /**
   * Effective diagnostics: 0=off, 1=on.
   */
  uint8_t diagnostics;
} FFIEffectiveConfig;

/**
 * FFI-safe error policy enum (spec 51).
 *
 * The C side derives this from the `markdown_error_policy` directive value
 * and passes it to `markdown_decide_error_behavior`.
 */
typedef struct FFIErrorPolicy {
  /**
   * Policy kind: 0 = pass, 1 = status, 2 = fail_closed.
   */
  uint8_t kind;
  /**
   * HTTP status code (meaningful only when kind == 1).
   */
  uint16_t status_code;
} FFIErrorPolicy;

/**
 * FFI-safe error behavior enum (spec 51).
 *
 * Returned by `markdown_decide_error_behavior` to tell the C error handler
 * what action to take.
 */
typedef struct FFIErrorBehavior {
  /**
   * Behavior kind: 0 = pass_through, 1 = return_status, 2 = terminate.
   */
  uint8_t kind;
  /**
   * HTTP status code (meaningful only when kind == 1).
   */
  uint16_t status_code;
  /**
   * 1 if behavior was forced (post-commit), 0 if policy-driven.
   */
  uint8_t forced;
} FFIErrorBehavior;

/**
 * Get the string representation of a reason code by its numeric value.
 *
 * Returns a pointer to a static string and writes the length to `out_len`.
 * Returns NULL if the discriminant is invalid.
 *
 * # Safety
 *
 * The caller must ensure that `out_len` either is NULL or points to
 * writable storage for a `usize`.
 */
const uint8_t *markdown_reason_code_str(uint32_t code, uintptr_t *out_len);

/**
 * Get the Prometheus metric key for a reason code by its numeric value.
 *
 * Returns a pointer to a static string and writes the length to `out_len`.
 * Returns NULL if the discriminant is invalid.
 *
 * # Safety
 *
 * The caller must ensure that `out_len` either is NULL or points to
 * writable storage for a `usize`.
 */
const uint8_t *markdown_reason_code_metric_key(uint32_t code, uintptr_t *out_len);

/**
 * Return the total number of defined reason codes.
 *
 * C callers can use this to verify they handle all variants.
 */
uint32_t markdown_reason_code_count(void);

/**
 * Get a default diagnostics JSON schema v1 string.
 *
 * Returns a pointer to a heap-allocated JSON byte buffer and writes the
 * byte length (excluding any NUL terminator) to `out_len`. The returned
 * buffer is NUL-terminated for convenience but `out_len` does NOT include
 * the terminator.
 *
 * On failure (NULL `out_len`, serialization error, or caught panic) returns
 * NULL and sets `*out_len = 0`.
 *
 * The caller must free the returned buffer by calling
 * [`markdown_free_diagnostics`] with the same pointer and length.
 *
 * # Safety
 *
 * The caller must ensure that `out_len` either is NULL (in which case the
 * function returns NULL immediately) or points to writable storage for a
 * `usize`.
 */
uint8_t *markdown_get_diagnostics_schema(uintptr_t *out_len);

/**
 * Free a diagnostics JSON string previously returned by
 * [`markdown_get_diagnostics_schema`].
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `ptr` was returned by `markdown_get_diagnostics_schema` and has not
 *   already been freed
 * - `len` is the value written to `out_len` by that call
 *
 * After this call, `ptr` is invalid and must not be dereferenced.
 */
void markdown_free_diagnostics(uint8_t *ptr, uintptr_t len);

/**
 * Allocate a new converter handle for use across multiple FFI calls.
 *
 * # Safety
 *
 * Returns a raw pointer that must eventually be freed with
 * `markdown_converter_free()`.
 *
 * # Returns
 *
 * Returns a non-NULL handle on success. Returns NULL only when
 * `MarkdownConverterHandle::new()` panics and that panic is caught by
 * `catch_unwind()`. On stable Rust, allocator out-of-memory aborts the process
 * instead of unwinding, so OOM is not caught here and does not produce NULL.
 */
struct MarkdownConverterHandle *markdown_converter_new(void);

/**
 * Convert an HTML byte buffer into Markdown using the provided converter handle.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `handle` points to a live converter created by `markdown_converter_new()`
 * - `options` points to a valid `MarkdownOptions`
 * - `result` points to writable storage for a `MarkdownResult` whose owned
 *   buffers are either NULL/zero-length or were previously returned by this API
 * - `html` either points to `html_len` readable bytes or is NULL when `html_len == 0`
 * - `result` is not concurrently mutated while this function is executing
 */
void markdown_convert(struct MarkdownConverterHandle *handle,
                      const uint8_t *html,
                      uintptr_t html_len,
                      const struct MarkdownOptions *options,
                      struct MarkdownResult *result);

/**
 * Release buffers owned by a `MarkdownResult` and reset it to the empty state.
 *
 * # Safety
 *
 * The caller must ensure that `result` either is NULL or points to a valid
 * `MarkdownResult` previously initialized by `markdown_convert()`. Passing the
 * same result twice is allowed because the function resets pointers to NULL.
 */
void markdown_result_free(struct MarkdownResult *result);

/**
 * Destroy a converter handle previously returned by `markdown_converter_new()`.
 *
 * # Safety
 *
 * The caller must ensure that `handle` either is NULL or was returned by
 * `markdown_converter_new()` and has not already been freed. The handle must
 * not be used after this call returns.
 */
void markdown_converter_free(struct MarkdownConverterHandle *handle);

/**
 * Perform Accept header content negotiation.
 *
 * Parses the client `Accept` header and determines whether the client
 * prefers `text/markdown` over `text/html`, using RFC 9110 §12.5.1
 * q-value comparison.
 *
 * # Parameters
 *
 * - `on_wildcard`: Controls wildcard (all-types MIME) handling.
 *   - `0` (NEGOTIATE_WILDCARD_STRICT): wildcards do NOT match text/markdown;
 *     only explicit `text/markdown` triggers conversion.
 *   - `1` (NEGOTIATE_WILDCARD_ALLOW): wildcards match text/markdown,
 *     so a wildcard Accept header will trigger conversion.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `accept_header` either points to `accept_header_len` readable bytes
 *   or is NULL when `accept_header_len == 0`
 * - `result` points to writable storage for a `FFIAcceptResult`
 */
void markdown_negotiate_accept(const uint8_t *accept_header,
                               uintptr_t accept_header_len,
                               uint8_t on_wildcard,
                               struct FFIAcceptResult *result);

/**
 * Decide whether an upstream response is eligible for Markdown conversion.
 *
 * Single source of truth for the eligibility determination (method, status,
 * Range, unbounded streaming, Content-Type allowlist, size limit). The C
 * module marshals request/config fields into [`FFIEligibilityInput`] and
 * casts the returned `u8` directly to `ngx_http_markdown_eligibility_t`
 * (the codes match that enum's discriminants).
 *
 * Returns `FFI_ELIGIBILITY_INELIGIBLE_CONFIG` (skip conversion, the safe
 * fail-open outcome) if `input` is NULL or on any caught panic.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `input` is NULL or points to a valid [`FFIEligibilityInput`]
 * - `content_type` points to `content_type_len` readable bytes (or is NULL
 *   when `content_type_len == 0`)
 * - `content_types`/`stream_types` point to `*_count` readable [`FFIStr`]
 *   entries (or are NULL when the count is 0), each `FFIStr.data` pointing to
 *   `FFIStr.len` readable bytes (or NULL when `len == 0`)
 * - all referenced memory remains valid for the duration of the call
 */
uint8_t markdown_decide_eligibility(const struct FFIEligibilityInput *input);

/**
 * Evaluate HTTP conditional request headers (If-None-Match / If-Modified-Since).
 *
 * Returns the conditional result through the `result` output parameter.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - All string pointers either point to readable UTF-8 bytes of the given length
 *   or are NULL when the corresponding length is 0
 * - `result` points to writable storage for a `FFIConditionalResult`
 */
void markdown_check_conditional(const uint8_t *if_none_match,
                                uintptr_t if_none_match_len,
                                const uint8_t *entity_etag,
                                uintptr_t entity_etag_len,
                                const uint8_t *if_modified_since,
                                uintptr_t if_modified_since_len,
                                const uint8_t *last_modified,
                                uintptr_t last_modified_len,
                                struct FFIConditionalResult *result);

/**
 * Decide the conditional-request outcome (spec 49): cache-validation mode,
 * `If-None-Match` over `If-Modified-Since` precedence, and `Range` /
 * `no-transform` bypass.
 *
 * This is the Rust single source of truth wrapping
 * `crate::decision::conditional::decide_conditional`. The result is written
 * through the `out` output parameter.
 *
 * On NULL `input`/`out` or on a caught panic, the output is left at the
 * fail-open default (proceed, no headers evaluated) so a spurious 304 is
 * never produced.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `input` is NULL or points to a readable `FFIConditionalInput` whose
 *   byte pointers each reference `*_len` readable bytes (or are NULL when
 *   the length is 0)
 * - `out` is NULL or points to writable storage for an
 *   `FFIConditionalDecision`
 * - all referenced memory remains valid for the duration of the call
 */
void markdown_decide_conditional(const struct FFIConditionalInput *input,
                                 struct FFIConditionalDecision *out);

/**
 * Decide whether the request may take the streaming path (spec 49).
 *
 * This is the Rust single source of truth wrapping
 * `crate::decision::streaming::decide_streaming`. The result is written
 * through the `out` output parameter.
 *
 * On NULL `input`/`out` or on a caught panic, the output is the safe
 * fallback: not eligible (the full-buffer path), with no block reason
 * reported (`STREAMING_BLOCK_REASON_NONE`).
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `input` is NULL or points to a readable `FFIStreamingInput`
 * - `out` is NULL or points to writable storage for an
 *   `FFIStreamingDecision`
 */
void markdown_decide_streaming(const struct FFIStreamingInput *input,
                               struct FFIStreamingDecision *out);

/**
 * Evaluate the conversion decision engine.
 *
 * Returns the decision through the `result` output parameter.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for a `FFIDecisionResult`.
 */
void markdown_make_decision(uint8_t enabled,
                            uint8_t eligible,
                            uint8_t accept_prefers_markdown,
                            uint8_t accept_header_present,
                            uint8_t conditional_not_modified,
                            uint8_t decompression_ok,
                            uint8_t parse_timed_out,
                            uint8_t parse_budget_exceeded,
                            struct FFIDecisionResult *result);

/**
 * Build a header plan for a successful Markdown conversion.
 * The returned plan contains Rust-owned buffers. The C caller must release
 * the plan via `markdown_header_plan_free`.
 * This function treats `result` as uninitialized output storage and never
 * reads its previous fields. Callers that already own a plan in the same
 * storage must call `markdown_header_plan_free` before rebuilding it.
 * # Safety
 * The caller must ensure that:
 * - `content_type` points to readable UTF-8 bytes of `content_type_len`
 * - `result` points to writable storage for a `FFIHeaderPlan`; its previous
 *   bytes may be uninitialized, but any previously-owned plan must have been
 *   released before this call
 */
void markdown_build_header_plan(const uint8_t *content_type,
                                uintptr_t content_type_len,
                                uint8_t has_etag,
                                struct FFIHeaderPlan *result);

/**
 * Validate a URL for use in Markdown link destinations.
 *
 * Returns 1 if the URL is safe, 0 if it contains control characters
 * or dangerous schemes.
 *
 * # Safety
 *
 * The caller must ensure that `url` either points to `url_len` readable
 * bytes or is NULL when `url_len == 0`.
 */
uint8_t markdown_validate_url(const uint8_t *url, uintptr_t url_len);

/**
 * Check if a URL uses a dangerous scheme (javascript:, data:, etc.).
 *
 * Returns 1 if dangerous, 0 if safe.
 *
 * # Safety
 *
 * The caller must ensure that `url` either points to `url_len` readable
 * bytes or is NULL when `url_len == 0`.
 */
uint8_t markdown_is_dangerous_url(const uint8_t *url, uintptr_t url_len);

/**
 * Build a base URL from X-Forwarded-Host and X-Forwarded-Proto headers.
 *
 * Parses the forwarded headers and constructs a validated base URL
 * (e.g., "https://api.example.com"). The result is written into the
 * caller-provided buffer. Returns the number of bytes written, or 0
 * if the headers are absent, empty, or contain invalid characters.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `x_forwarded_host` either points to `host_len` readable bytes or is NULL
 * - `x_forwarded_proto` either points to `proto_len` readable bytes or is NULL
 * - `out_buf` points to at least `out_buf_cap` writable bytes
 */
uintptr_t markdown_build_base_url(const uint8_t *x_forwarded_host,
                                  uintptr_t host_len,
                                  const uint8_t *x_forwarded_proto,
                                  uintptr_t proto_len,
                                  uint8_t *out_buf,
                                  uintptr_t out_buf_cap);

/**
 * Allocate a new, empty trusted-proxy CIDR set (spec 47).
 *
 * The handle accumulates config-time-validated CIDRs via
 * `markdown_trusted_proxies_push` and is consumed at request time by
 * `markdown_decide_base_url`.
 *
 * # Safety
 *
 * Returns a raw pointer that must eventually be freed with
 * `markdown_trusted_proxies_free`.  Returns NULL only if allocation of the
 * handle panics and that panic is caught.
 */
struct MarkdownTrustedProxies *markdown_trusted_proxies_new(void);

/**
 * Validate a CIDR string and append it to a trusted-proxy set (config time).
 *
 * Returns `TRUSTED_PROXIES_PUSH_OK` (0) on success,
 * `TRUSTED_PROXIES_PUSH_INVALID_CIDR` (1) when the CIDR is malformed, or
 * `TRUSTED_PROXIES_PUSH_NULL` (2) when `handle` or `cidr` is NULL/empty.
 *
 * # Safety
 *
 * The caller must ensure that `handle` points to a live set created by
 * `markdown_trusted_proxies_new`, and that `cidr` either points to `cidr_len`
 * readable bytes or is NULL when `cidr_len == 0`.
 */
uint8_t markdown_trusted_proxies_push(struct MarkdownTrustedProxies *handle,
                                      const uint8_t *cidr,
                                      uintptr_t cidr_len);

/**
 * Free a trusted-proxy set previously returned by
 * `markdown_trusted_proxies_new`.
 *
 * # Safety
 *
 * `handle` must either be NULL or a pointer previously returned by
 * `markdown_trusted_proxies_new` that has not already been freed.
 */
void markdown_trusted_proxies_free(struct MarkdownTrustedProxies *handle);

/**
 * Decide the trusted base URL for a request (spec 47 small API).
 *
 * Marshals the borrowed request/config fields into the pure
 * [`decide_base_url`] decision, writes the chosen base URL into the
 * caller-provided `out_buf`, and fills `out` with the byte count, reason
 * code, and source.  The decision logic (CIDR matching, forwarded-header
 * precedence, multi-hop handling, host/proto validation, fallback) lives
 * entirely in Rust.
 *
 * Returns `DECIDE_BASE_URL_OK` (0) on success, or `DECIDE_BASE_URL_INVALID`
 * (1) when `input`/`out`/`out_buf` is NULL, the output buffer is too small,
 * or a panic is caught (fail-safe).
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `input` points to a valid `FFIBaseUrlInput`; every non-NULL byte field
 *   points to its stated length of readable bytes, and `trusted` is NULL or
 *   a live `MarkdownTrustedProxies` handle;
 * - `out_buf` points to at least `out_buf_cap` writable bytes;
 * - `out` points to writable storage for an `FFIBaseUrlDecision`.
 */
uint8_t markdown_decide_base_url(const struct FFIBaseUrlInput *input,
                                 uint8_t *out_buf,
                                 uintptr_t out_buf_cap,
                                 struct FFIBaseUrlDecision *out);

/**
 * Release a header plan previously returned by `markdown_build_header_plan`.
 *
 * # Safety
 *
 * The caller must ensure that `plan` either is NULL or points to a valid
 * `FFIHeaderPlan` previously returned by `markdown_build_header_plan`.
 */
void markdown_header_plan_free(struct FFIHeaderPlan *plan);

/**
 * Initialize a `MarkdownOptions` struct with sensible defaults.
 *
 * C callers **MUST** use this function instead of `memset(&opts, 0, sizeof(opts))`
 * or literal struct initialization (`MarkdownOptions opts = {0}`). The helper
 * guarantees that all fields — including any future tail-appended fields — are
 * set to valid defaults. After calling this function, the caller may override
 * individual fields as needed.
 *
 * Default values:
 * - `flavor`: 0 (CommonMark)
 * - `timeout_ms`: 5000 (5 seconds)
 * - `generate_etag`: 0 (disabled — ETag generation is a config-layer
 *   decision; the init helper only provides a safe ABI baseline)
 * - `estimate_tokens`: 0 (disabled)
 * - `front_matter`: 0 (disabled)
 * - `content_type` / `base_url` / selectors: NULL/0
 * - `streaming_budget`: 0 (use engine default)
 * - `prune_noise`: 0 (disabled)
 * - `memory_budget`: 0 (use per-engine defaults)
 * - `llm_provider`: 0 (default)
 * - `chars_per_token_fixed`: 0 (use default ratio)
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for a `MarkdownOptions`.
 */
void markdown_options_init(struct MarkdownOptions *result);

/**
 * Zero-initialize a MarkdownResult struct.
 *
 * The C caller should use this instead of manual = {0} or memset
 * to guarantee all fields (including any future tail-appended fields)
 * start in a valid zero state.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for a `MarkdownResult`.
 */
void markdown_result_init(struct MarkdownResult *result);

/**
 * Zero-initialize an FFIAcceptResult struct.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for an `FFIAcceptResult`.
 */
void markdown_accept_result_init(struct FFIAcceptResult *result);

/**
 * Zero-initialize an FFIConditionalResult struct.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for an `FFIConditionalResult`.
 */
void markdown_conditional_result_init(struct FFIConditionalResult *result);

/**
 * Zero-initialize an FFIDecisionResult struct.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for an `FFIDecisionResult`.
 */
void markdown_decision_result_init(struct FFIDecisionResult *result);

/**
 * Zero-initialize an FFIHeaderPlan struct.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for an `FFIHeaderPlan`.
 */
void markdown_header_plan_init(struct FFIHeaderPlan *result);

/**
 * Perform bounded decompression of compressed input data.
 *
 * Decompresses the input using the specified format (gzip, deflate, or brotli)
 * with a hard budget limit on the output size. If the decompressed output
 * would exceed `budget` bytes, decompression is terminated immediately and
 * `BudgetExceeded` is returned.
 *
 * On success, the `result` struct is populated with a Rust-owned output buffer.
 * The C caller **must** free this buffer via [`markdown_decompress_free`].
 *
 * # Format Codes
 *
 * - `0` = gzip (RFC 1952)
 * - `1` = deflate (RFC 1951)
 * - `2` = brotli (RFC 7932)
 *
 * # Return Value
 *
 * Returns `0` on success. On failure, returns the error category code:
 * - `101` = budget_exceeded (`DECOMP_CATEGORY_BUDGET_EXCEEDED`)
 * - `102` = format_error (`DECOMP_CATEGORY_FORMAT_ERROR`)
 * - `103` = truncated_input (`DECOMP_CATEGORY_TRUNCATED_INPUT`)
 * - `104` = io_error (`DECOMP_CATEGORY_IO_ERROR`)
 * - `105` = invalid arguments — NULL pointers, unknown format (`DECOMP_CATEGORY_INVALID_ARGS`)
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `input` points to at least `input_len` readable bytes; if `input` is
 *   NULL, then `input_len` **must** be 0 (NULL with non-zero `input_len`
 *   returns `DECOMP_CATEGORY_INVALID_ARGS`)
 * - `result` points to writable storage for an `FFIDecompResult`
 * - The output buffer in `result` is freed via `markdown_decompress_free`
 *   after use (only when return value is 0)
 */
uint32_t markdown_decompress_bounded(const uint8_t *input,
                                     uintptr_t input_len,
                                     uint8_t format,
                                     uintptr_t budget,
                                     struct FFIDecompResult *result);

/**
 * Release the output buffer from a successful `markdown_decompress_bounded` call.
 *
 * After calling this function, the `result` struct is reset to a safe zero
 * state. Calling this on a result with a NULL output pointer is a no-op.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `result` either is NULL or points to a valid `FFIDecompResult` previously
 *   populated by `markdown_decompress_bounded`
 * - The same result is not freed twice (the function resets pointers to NULL
 *   after freeing, so double-free is safe but wasteful)
 */
void markdown_decompress_free(struct FFIDecompResult *result);

/**
 * Zero-initialize an FFIDecompResult struct.
 *
 * # Safety
 *
 * The caller must ensure that `result` points to writable storage
 * for an `FFIDecompResult`.
 */
void markdown_decomp_result_init(struct FFIDecompResult *result);

/**
 * Detect configuration conflicts between a profile, explicit directives, and
 * the effective configuration.
 *
 * This is the primary FFI entry point for `nginx -t` validation. The C side
 * calls this after computing the effective config via its own merge logic,
 * passing the profile selector, the explicitly-set directive flags, and the
 * fully-resolved effective config.
 *
 * Returns an [`FFIConflictList`] that the caller must free with
 * [`markdown_free_conflicts`]. If no conflicts are detected, the returned
 * list has `count == 0` and `conflicts == NULL` (Rule 53).
 *
 * On NULL input pointers or on a caught panic, returns an empty conflict list
 * (the safe fail-open outcome: no spurious errors reported).
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `profile` is a valid `FFIProfile` discriminant (0–3)
 * - `explicit` is NULL or points to a readable `FFIExplicitConfig`
 * - `effective` is NULL or points to a readable `FFIEffectiveConfig`
 */
struct FFIConflictList markdown_detect_conflicts(uint8_t profile,
                                                 const struct FFIExplicitConfig *explicit_,
                                                 const struct FFIEffectiveConfig *effective);

/**
 * Free a conflict list returned by `markdown_detect_conflicts`.
 *
 * Releases all heap-allocated message buffers and the conflict array itself.
 * Calling with a zeroed/empty list (`count == 0`, `conflicts == NULL`) is a
 * safe no-op.
 *
 * # Safety
 *
 * The caller must ensure that `list` points to a valid `FFIConflictList`
 * previously returned by `markdown_detect_conflicts`, or is a zeroed struct.
 * The list must not be used after this call.
 */
void markdown_free_conflicts(struct FFIConflictList *list);

/**
 * Decide error handling behavior for a given error class and policy (spec 51).
 *
 * This is the FFI entry point for the unified error policy decision.
 * The C error handler calls this to determine what action to take.
 *
 * # Parameters
 *
 * - `error_class`: The `FFIErrorClass` discriminant identifying the error.
 * - `policy`: The `FFIErrorPolicy` derived from `markdown_error_policy`.
 * - `out`: Output pointer for the resulting `FFIErrorBehavior`.
 *
 * # Returns
 *
 * `0` on success, `1` if `out` is NULL or `error_class` is invalid.
 *
 * # Safety
 *
 * The caller must ensure that `out` is NULL or points to writable storage
 * for an `FFIErrorBehavior`.
 */
uint8_t markdown_decide_error_behavior(uint8_t error_class,
                                       struct FFIErrorPolicy policy,
                                       struct FFIErrorBehavior *out);

/**
 * Map an error class to its reason code discriminant (spec 51).
 *
 * Returns the `ReasonCode` discriminant (u8) for the given error class.
 * Returns `u8::MAX` (255) if the error class is invalid.
 *
 * # Safety
 *
 * No pointer parameters; always safe to call.
 */
uint8_t markdown_error_to_reason_code(uint8_t error_class);

/**
 * Classify a raw FFI error code into its `ErrorClass` discriminant.
 *
 * This is the FFI entry point that maps the raw `ERROR_*` constants
 * (defined in `markdown_converter.h`) to `ErrorClass` discriminants.
 * The C side calls this to delegate error classification to Rust
 * (single source of truth) instead of maintaining an independent switch.
 *
 * Returns the `ErrorClass` discriminant (u8) for the given error code.
 * Unknown error codes return `ErrorClass::FfiPanic` discriminant (3).
 *
 * # Safety
 *
 * No pointer parameters; always safe to call. The function is panic-free
 * by construction (trivial match expression with no allocations).
 */
uint8_t markdown_classify_error_code(uint32_t error_code);

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Create a new incremental converter handle for incremental Markdown processing.
 *
 * The returned handle is an opaque pointer owned by the caller and must be
 * either finalized with `markdown_incremental_finalize` or freed with
 * `markdown_incremental_free`.
 *
 * # Safety
 *
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 * - The returned pointer is heap-allocated; the caller owns it and must not
 *   dereference it except via the `markdown_incremental_*` family of functions.
 *
 * # Returns
 *
 * A non-NULL handle on success, or NULL if `options` is NULL, if `MarkdownOptions`
 * cannot be decoded, or if an internal panic is caught.
 *
 * # Examples
 *
 * ```no_run
 * use nginx_markdown_converter::ffi::{MarkdownOptions, markdown_incremental_new, markdown_incremental_free};
 * // Construct and fully initialize MarkdownOptions for your environment.
 * let opts = MarkdownOptions {
 *     flavor: 0,
 *     timeout_ms: 0,
 *     generate_etag: 0,
 *     estimate_tokens: 0,
 *     front_matter: 0,
 *     content_type: std::ptr::null(),
 *     content_type_len: 0,
 *     base_url: std::ptr::null(),
 *     base_url_len: 0,
 *     streaming_budget: 0,
 *     prune_noise: 1,
 *     prune_selectors: std::ptr::null(),
 *     prune_selector_len: 0,
 *     prune_protection_selectors: std::ptr::null(),
 *     prune_protection_selector_len: 0,
 *     memory_budget: 0,
 *     llm_provider: 0,
 *     chars_per_token_fixed: 0,
 *     parse_timeout_ms: 0,
 *     parser_memory_budget: 0,
 *     flush_threshold: 0,
 * };
 * let handle = unsafe { markdown_incremental_new(&opts) };
 * assert!(!handle.is_null());
 * // Either finalize to produce output or free when done without producing output.
 * unsafe { markdown_incremental_free(handle) };
 * ```
 * Create a new incremental converter handle and return an explicit status code.
 *
 * This API is the recommended constructor for C callers that need actionable
 * failure classification. On success, `*out_handle` receives a non-NULL handle.
 * On error, `*out_handle` is set to NULL and the function returns an error code.
 *
 * Unlike [`markdown_incremental_new`], this function does not write to stderr,
 * making it suitable for use as a library function within NGINX where all
 * diagnostics should go through `ngx_log_error()`.
 *
 * # Safety
 *
 * - `out_handle` must be a valid, writable pointer to
 *   `*mut IncrementalConverterHandle`.
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) on success
 * - `ERROR_INVALID_INPUT` (5) for NULL pointers or invalid options
 * - `ERROR_INTERNAL` (99) for caught panics
 */
uint32_t markdown_incremental_new_with_code(const struct MarkdownOptions *options,
                                            struct IncrementalConverterHandle **out_handle);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Convenience wrapper around [`markdown_incremental_new_with_code`] that
 * returns only the handle pointer.
 *
 * On failure, returns NULL. For actionable error classification, prefer
 * [`markdown_incremental_new_with_code`].
 *
 * # Safety
 *
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call, or be NULL.
 */
struct IncrementalConverterHandle *markdown_incremental_new(const struct MarkdownOptions *options);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Buffers a provided input chunk for later conversion.
 *
 * Accepts an empty chunk (`data_len == 0`) as a no-op.
 *
 * # Safety
 *
 * * `handle` must be a live pointer returned by [`markdown_incremental_new`].
 * * `data` must point to at least `data_len` readable bytes, or be NULL when `data_len` is 0`.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure.
 *
 * # Examples
 *
 * ```no_run
 * use std::ptr;
 * use nginx_markdown_converter::ffi::{markdown_incremental_new, markdown_incremental_feed, markdown_incremental_free};
 * unsafe {
 *     let options = ptr::null(); // populate as needed
 *     let handle = markdown_incremental_new(options);
 *     if !handle.is_null() {
 *         // feed a chunk
 *         let _ = markdown_incremental_feed(handle, b"hello".as_ptr(), 5);
 *         // finalize or free the handle as appropriate
 *         markdown_incremental_free(handle);
 *     }
 * }
 * ```
 */
uint32_t markdown_incremental_feed(struct IncrementalConverterHandle *handle,
                                   const uint8_t *data,
                                   uintptr_t data_len);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Finalize an incremental converter, consume its handle, and write the conversion output or error into `result`.
 *
 * The call always consumes the provided `handle`; after this function returns (whether success, failure,
 * or internal panic) the handle is invalid and must not be used again or freed by the caller.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by `markdown_incremental_new` that has not already been
 *   finalized or freed. This function takes ownership of the handle and will free it during execution.
 * - `result` must be a valid, writable pointer to a `MarkdownResult`. Any buffers previously owned by
 *   `result` must either be NULL/zero-length or must have been previously returned by this API.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure. In all cases `result` is populated
 * with either the produced markdown (and optional ETag/token estimate) or an error code and message.
 *
 * # Examples
 *
 * ```no_run
 * use std::ptr::null_mut;
 * use nginx_markdown_converter::ffi::{markdown_incremental_finalize, ERROR_INVALID_INPUT};
 *
 * // Passing NULL result pointer is invalid and returns ERROR_INVALID_INPUT.
 * let code = unsafe { markdown_incremental_finalize(null_mut(), null_mut()) };
 * assert_eq!(code, ERROR_INVALID_INPUT);
 * ```
 */
uint32_t markdown_incremental_finalize(struct IncrementalConverterHandle *handle,
                                       struct MarkdownResult *result);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Frees an incremental converter handle without finalizing.
 *
 * Use this function to release resources when the conversion is being
 * abandoned (e.g. on error or cancellation).  If the handle has already
 * been consumed by [`markdown_incremental_finalize`], do **not** call
 * this function — `finalize` always consumes the handle regardless of
 * its return code, and calling `free` afterwards is a double-free.
 *
 * Passing NULL is a safe no-op.
 *
 * # Safety
 *
 * * `handle` must be NULL or a live pointer returned by
 *   [`markdown_incremental_new`] that has not been finalized or freed.
 */
void markdown_incremental_free(struct IncrementalConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Create a new streaming converter handle and return an explicit status code.
 *
 * This API is the recommended constructor for C callers that need actionable
 * failure classification. On success, `*out_handle` receives a non-NULL handle.
 * On error, `*out_handle` is set to NULL and the function returns an error code.
 *
 * # Safety
 *
 * - `out_handle` must be a valid, writable pointer to `*mut StreamingConverterHandle`.
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) on success
 * - `ERROR_INVALID_INPUT` (5) for NULL pointers or invalid options
 * - `ERROR_INTERNAL` (99) for caught panics
 */
uint32_t markdown_streaming_new_with_code(const struct MarkdownOptions *options,
                                          struct StreamingConverterHandle **out_handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Create a new streaming converter handle.
 *
 * The returned handle is an opaque pointer owned by the caller and must be
 * consumed by exactly one of `markdown_streaming_finalize`,
 * `markdown_streaming_abort`, or `markdown_streaming_free`.
 *
 * # Safety
 *
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 * - The returned pointer is heap-allocated; the caller owns it and must not
 *   dereference it except via the `markdown_streaming_*` family of functions.
 *
 * # Returns
 *
 * A non-NULL handle on success, or NULL if `options` is NULL, if
 * `MarkdownOptions` cannot be decoded, or if an internal panic is caught.
 */
struct StreamingConverterHandle *markdown_streaming_new(const struct MarkdownOptions *options);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Feed a chunk of HTML input and receive any ready Markdown output.
 *
 * On success (`ERROR_SUCCESS`), `*out_data` and `*out_len` are set to the
 * Markdown output buffer allocated by Rust. The caller must free this buffer
 * via [`markdown_streaming_output_free`]. If no output is ready, `*out_data`
 * is NULL and `*out_len` is 0.
 *
 * On error, `*out_data` is set to NULL and `*out_len` to 0. The returned
 * error code indicates the failure type.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by [`markdown_streaming_new`].
 * - `data` must point to at least `data_len` readable bytes, or be NULL
 *   when `data_len` is 0.
 * - `out_data` must be a valid, writable pointer to `*mut u8`.
 * - `out_len` must be a valid, writable pointer to `usize`.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) on success
 * - `ERROR_STREAMING_FALLBACK` (7) for pre-commit fallback signal
 * - `ERROR_BUDGET_EXCEEDED` (6) for memory budget exceeded
 * - `ERROR_POST_COMMIT` (8) for post-commit error
 * - `ERROR_TIMEOUT` (3) for timeout
 * - `ERROR_INVALID_INPUT` (5) for NULL handle or output pointers
 * - `ERROR_INTERNAL` (99) for caught panics
 */
uint32_t markdown_streaming_feed(struct StreamingConverterHandle *handle,
                                 const uint8_t *data,
                                 uintptr_t data_len,
                                 uint8_t **out_data,
                                 uintptr_t *out_len);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Signal end-of-input to the streaming converter, flush remaining output,
 * and consume the handle.
 *
 * This is a lightweight finish path for C callers that only need the final
 * flushed Markdown bytes and a status code — without the full
 * [`MarkdownResult`] metadata (ETag, token estimate, peak memory) that
 * [`markdown_streaming_finalize`] provides.
 *
 * On success (`ERROR_SUCCESS`), `*out_data` and `*out_len` are set to the
 * final Markdown output buffer allocated by Rust. The caller must free this
 * buffer via [`markdown_streaming_output_free`]. If the final flush produces
 * no additional output, `*out_data` is NULL and `*out_len` is 0.
 *
 * This call always consumes the provided `handle` when validation passes
 * (handle is non-NULL and output pointers are non-NULL); after this function
 * returns successfully the handle is invalid and must not be passed to any
 * other `markdown_streaming_*` function. If validation fails (NULL handle or
 * NULL output pointers), `ERROR_INVALID_INPUT` is returned and the handle is
 * NOT consumed — the caller remains responsible for freeing or aborting it.
 * Violating this rule causes a double-free (CWE-415).
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by [`markdown_streaming_new`]
 *   that has not already been finalized, aborted, freed, or finished.
 * - `out_data` must be a valid, writable pointer to `*mut u8`.
 * - `out_len` must be a valid, writable pointer to `usize`.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) — conversion completed normally, output available
 * - `ERROR_STREAMING_FALLBACK` (7) — unsupported content detected (pre-commit)
 * - `ERROR_POST_COMMIT` (8) — error after partial output committed
 * - `ERROR_TIMEOUT` (3) — cooperative timeout exceeded during flush
 * - `ERROR_BUDGET_EXCEEDED` (6) — memory budget exceeded during flush
 * - `ERROR_INVALID_INPUT` (5) — NULL handle or output pointers
 * - `ERROR_INTERNAL` (99) — caught panic
 */
uint32_t markdown_streaming_finish(struct StreamingConverterHandle *handle,
                                   uint8_t **out_data,
                                   uintptr_t *out_len);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Finalize a streaming conversion, consume the handle, and write the result.
 *
 * This call consumes the provided `handle` when validation passes (both
 * `handle` and `result` are non-NULL); after successful consumption the
 * handle is invalid and must not be used again or freed by the caller.
 * If validation fails (NULL `handle` or NULL `result`), `ERROR_INVALID_INPUT`
 * is returned and the handle is NOT consumed — the caller remains responsible
 * for freeing or aborting it.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by `markdown_streaming_new`
 *   that has not already been finalized, aborted, or freed.
 * - `result` must be a valid, writable pointer to a `MarkdownResult`. Any
 *   buffers previously owned by `result` must either be NULL/zero-length
 *   or must have been previously returned by this API.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure.
 * In all cases `result` is populated with either the produced markdown
 * (and optional ETag/token estimate) or an error code and message.
 */
uint32_t markdown_streaming_finalize(struct StreamingConverterHandle *handle,
                                     struct MarkdownResult *result);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Abort a streaming conversion and release all Rust resources.
 *
 * Use this function when the conversion must be abandoned (e.g. client
 * abort or unrecoverable error). This always consumes the handle.
 *
 * Passing NULL is a safe no-op.
 *
 * # Safety
 *
 * - `handle` must be NULL or a live pointer returned by
 *   [`markdown_streaming_new`] that has not been finalized, aborted,
 *   or freed.
 */
void markdown_streaming_abort(struct StreamingConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Attempt a post-commit safe finish: close all open Markdown structures
 * without emitting raw HTML, then consume the handle.
 *
 * This function is designed to be called after `markdown_streaming_feed`
 * returns `ERROR_POST_COMMIT` (8). It attempts to gracefully close all
 * open Markdown constructs (headings, paragraphs, lists, code blocks,
 * blockquotes, inline formatting) so that the already-emitted output
 * forms valid Markdown.
 *
 * On success (`POST_COMMIT_SAFE_FINISH` = 3), `*out_data` and `*out_len`
 * are set to the Markdown closure bytes (e.g., closing fences, trailing
 * newlines). The caller must free this buffer via
 * [`markdown_streaming_output_free`]. The caller should append these
 * bytes after the already-committed output.
 *
 * On failure (`POST_COMMIT_ABORT` = 4), structures could not be safely
 * closed. The output buffer is set to NULL/0. The caller must abort and
 * discard or truncate the partial output. **C MUST NOT infer or synthesize
 * Markdown closure for Rust-owned parser/emitter state** (safety invariant: C must not infer Markdown closure).
 *
 * This call consumes the handle after validation succeeds (the handle and
 * output pointers are non-NULL). If validation fails, `ERROR_INVALID_INPUT`
 * is returned and the handle is not consumed; the caller remains responsible
 * for aborting or freeing it. All other return codes consume the handle. In
 * particular, a caught panic (`ERROR_INTERNAL`) can only occur after
 * `Box::from_raw` has taken ownership, so the handle is consumed in that case.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by [`markdown_streaming_new`]
 *   that has not already been finalized, aborted, freed, or finished.
 * - `out_data` must be a valid, writable pointer to `*mut u8`.
 * - `out_len` must be a valid, writable pointer to `usize`.
 *
 * # Returns
 *
 * - `POST_COMMIT_SAFE_FINISH` (3) — all open structures were closed
 *   successfully; output buffer contains closure Markdown.
 * - `POST_COMMIT_ABORT` (4) — safe finish failed; output is NULL/0.
 *   Caller must abort (discard partial output).
 * - `ERROR_INVALID_INPUT` (5) — NULL handle or output pointers.
 * - `ERROR_INTERNAL` (99) — caught panic.
 */
uint32_t markdown_streaming_safe_finish(struct StreamingConverterHandle *handle,
                                        uint8_t **out_data,
                                        uintptr_t *out_len);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Free a streaming converter handle without finalizing.
 *
 * Use this function to release resources when the conversion is being
 * abandoned in an error path where neither `finalize` nor `abort` was
 * called. If the handle has already been consumed by `finalize` or
 * `abort`, do **not** call this function — that would be a double-free.
 *
 * Passing NULL is a safe no-op.
 *
 * This delegates to [`markdown_streaming_abort`] which has identical
 * semantics (both consume the handle by dropping it).
 *
 * # Safety
 *
 * - `handle` must be NULL or a live pointer returned by
 *   [`markdown_streaming_new`] that has not been finalized, aborted,
 *   or freed.
 */
void markdown_streaming_free(struct StreamingConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Free a Markdown output buffer returned by [`markdown_streaming_feed`]
 * or [`markdown_streaming_finish`].
 *
 * This is the **only** valid way to release output buffers produced by the
 * streaming FFI. The buffer is allocated by the Rust global allocator; C
 * callers MUST NOT free it with `free()`, `ngx_pfree()`, or any other
 * deallocator — doing so is undefined behaviour due to allocator mismatch.
 *
 * The `data` pointer and `len` must be exactly the values written to
 * `out_data` and `out_len` by a previous `feed` or `finish` call.
 * Passing `(NULL, 0)` is a safe no-op, which simplifies error-path cleanup.
 *
 * # Typical usage pattern (NGINX integration)
 *
 * ```text
 * // C pseudo-code: copy into NGINX chain, then free Rust buffer
 * rc = markdown_streaming_feed(handle, chunk, len, &out_data, &out_len);
 * if (rc == 0 && out_data != NULL) {
 *     ngx_memcpy(pool_buf->last, out_data, out_len);
 *     pool_buf->last += out_len;
 *     markdown_streaming_output_free(out_data, out_len);
 * }
 * ```
 *
 * # Safety
 *
 * - `data` must be NULL or a pointer previously returned via
 *   `markdown_streaming_feed`'s or `markdown_streaming_finish`'s
 *   `out_data` parameter.
 * - `len` must be the corresponding `out_len` value from the same call.
 * - Each `(data, len)` pair must be freed exactly once. Double-free is
 *   undefined behaviour (CWE-415).
 * - After this call, `data` is a dangling pointer and must not be
 *   dereferenced.
 */
void markdown_streaming_output_free(uint8_t *data, uintptr_t len);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Return the NUL-terminated reason string from the last `feed` or `finish`
 * call that signalled fallback or error.
 *
 * `handle` must be a live streaming handle. The returned pointer is owned by
 * Rust and valid only until the next `feed`, `finish`, `abort`, or handle-free
 * call on the same handle (whichever comes first). The C caller must not free
 * or modify the returned pointer. If C needs to preserve the reason across
 * calls, it must copy the string immediately into an NGINX pool or another
 * caller-owned buffer. Using a reason pointer after handle release is invalid.
 *
 * Returns NULL when no reason is available (i.e. the last call returned
 * `ERROR_SUCCESS` or the handle is NULL).
 *
 * # Safety
 *
 * - `handle` must be NULL or a live pointer returned by
 *   [`markdown_streaming_new`] that has not been finalized, aborted,
 *   or freed.
 * - The returned `*const c_char` must not be used after the next `feed`,
 *   `finish`, `abort`, or `free` call on the same handle.
 */
const char *markdown_streaming_reason(const struct StreamingConverterHandle *handle);
#endif

#endif  /* NGINX_MARKDOWN_CONVERTER_H */
