/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef NGINX_MARKDOWN_CONVERTER_H
#define NGINX_MARKDOWN_CONVERTER_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. */
/* Any manual changes will be overwritten on next build. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success - no error occurred.
 */
#define ERROR_SUCCESS 0

/**
 * HTML parsing failed (malformed HTML, invalid structure).
 */
#define ERROR_PARSE 1

/**
 * Character encoding error (invalid UTF-8, unsupported charset).
 */
#define ERROR_ENCODING 2

/**
 * Conversion timeout exceeded.
 */
#define ERROR_TIMEOUT 3

/**
 * Memory limit exceeded during conversion.
 */
#define ERROR_MEMORY_LIMIT 4

/**
 * Invalid input data (NULL pointers, invalid parameters).
 */
#define ERROR_INVALID_INPUT 5

/**
 * Internal error (unexpected condition, panic caught).
 */
#define ERROR_INTERNAL 99

/**
 * Opaque handle to Rust converter state shared across conversions.
 */
typedef struct MarkdownConverterHandle MarkdownConverterHandle;

/**
 * Conversion options passed from C to Rust.
 */
typedef struct MarkdownOptions {
  uint32_t flavor;
  uint32_t timeout_ms;
  uint8_t generate_etag;
  uint8_t estimate_tokens;
  uint8_t front_matter;
  const uint8_t *content_type;
  uintptr_t content_type_len;
  const uint8_t *base_url;
  uintptr_t base_url_len;
} MarkdownOptions;

/**
 * Conversion result returned from Rust to C.
 */
typedef struct MarkdownResult {
  uint8_t *markdown;
  uintptr_t markdown_len;
  uint8_t *etag;
  uintptr_t etag_len;
  uint32_t token_estimate;
  uint32_t error_code;
  uint8_t *error_message;
  uintptr_t error_len;
} MarkdownResult;

struct MarkdownConverterHandle *markdown_converter_new(void);

void markdown_convert(struct MarkdownConverterHandle *handle,
                      const uint8_t *html,
                      uintptr_t html_len,
                      const struct MarkdownOptions *options,
                      struct MarkdownResult *result);

void markdown_result_free(struct MarkdownResult *result);

void markdown_converter_free(struct MarkdownConverterHandle *handle);

#endif  /* NGINX_MARKDOWN_CONVERTER_H */
