//! Streaming security sanitizer for the token pipeline.
//!
//! Provides security validation equivalent to [`SecurityValidator`](crate::security::SecurityValidator)
//! but operating on [`StreamEvent`] tokens instead of DOM nodes.
//!
//! # Security Guarantees
//!
//! - Dangerous elements (script, style, etc.) and all their children are removed
//! - Embedded content elements (iframe, object, embed) have tags stripped but
//!   child content preserved; src/data URLs are extracted
//! - Form elements have tags stripped but child content preserved
//! - Event handler attributes (on*) are removed
//! - Dangerous URL schemes (javascript:, data:, etc.) are blocked
//! - Nesting depth is limited to prevent stack exhaustion

use crate::converter::pruning::{PruneConfig, should_prune_with_config};
use crate::security::URL_ATTRIBUTES;
use crate::security::escape_markdown_text;
use crate::security::is_dangerous_url_value;
use crate::streaming::emitter::escape_markdown_destination;
use crate::streaming::types::StreamEvent;

/// HTML void elements that never have children.
///
/// html5ever's tokenizer may report `self_closing = false` for these
/// because the source HTML uses `<link ...>` (no trailing `/>`).  The
/// sanitizer must treat them as self-closing so that entering skip or
/// strip mode for a void element does not permanently suppress all
/// subsequent content.
const VOID_ELEMENTS: &[&str] = &[
    "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source",
    "track", "wbr",
];

/// Start tags that implicitly close an open paragraph in button scope.
const PARAGRAPH_CLOSING_START_TAGS: &[&str] = &[
    "address",
    "article",
    "aside",
    "blockquote",
    "details",
    "div",
    "dl",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "header",
    "hgroup",
    "hr",
    "main",
    "menu",
    "nav",
    "ol",
    "p",
    "pre",
    "search",
    "section",
    "table",
    "ul",
];

const BUTTON_SCOPE_BOUNDARIES: &[&str] = &[
    "applet", "button", "caption", "html", "marquee", "object", "table", "td", "th", "template",
];
const LIST_ITEM_SCOPE_BOUNDARIES: &[&str] = &[
    "applet", "caption", "html", "marquee", "menu", "object", "ol", "table", "td", "th",
    "template", "ul",
];
const DEFINITION_SCOPE_BOUNDARIES: &[&str] = &["dl", "html", "table", "template"];
const SELECT_SCOPE_BOUNDARIES: &[&str] = &["datalist", "select", "template"];
const TABLE_SCOPE_BOUNDARIES: &[&str] = &["html", "table", "template"];
const TABLE_SECTION_SCOPE_BOUNDARIES: &[&str] =
    &["html", "table", "tbody", "tfoot", "thead", "template"];
const TABLE_ROW_SCOPE_BOUNDARIES: &[&str] =
    &["html", "table", "tbody", "tfoot", "thead", "tr", "template"];
const RUBY_SCOPE_BOUNDARIES: &[&str] = &["html", "ruby", "table", "template"];

/// Elements whose entire subtree is removed (content discarded).
const DANGEROUS_CONTAINER_ELEMENTS: &[&str] = &["script", "style", "noscript", "applet"];

/// Dangerous elements that are also HTML void elements.
///
/// These must be handled as one-shot "skip this tag" events rather than
/// entering skip-depth mode, because no matching end tag will arrive.
const DANGEROUS_VOID_ELEMENTS: &[&str] = &["link", "base"];

/// Embedded content elements: tags stripped, src/data URL extracted.
const EMBEDDED_CONTENT_ELEMENTS: &[&str] = &["iframe", "object", "embed"];

/// Media content elements: tags stripped, URL extracted from src/href.
const MEDIA_CONTENT_ELEMENTS: &[&str] = &["video", "audio", "source", "track", "area"];

/// Form elements: tags stripped, child text preserved.
const FORM_ELEMENTS: &[&str] = &[
    "form", "button", "select", "textarea", "fieldset", "legend", "label", "option", "optgroup",
    "datalist", "output",
];

/// Void form controls that have no children.
const VOID_FORM_CONTROLS: &[&str] = &["input"];

/// Maximum nesting depth (matches SecurityValidator).
const MAX_NESTING_DEPTH: usize = 1000;

/// Decision made by the sanitizer for a given event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SanitizeDecision {
    /// Pass the event through unchanged.
    Pass(StreamEvent),
    /// Pass the event with modified attributes (dangerous ones removed).
    PassModified(StreamEvent),
    /// Pass Markdown generated by the sanitizer from a validated URL.
    ///
    /// This is intentionally distinct from ordinary text: the emitter must
    /// preserve the generated link syntax while still escaping raw text from
    /// the upstream HTML document.
    PassGenerated(StreamEvent),
    /// Skip this event entirely (dangerous element or its children).
    Skip,
    /// The event signals a nesting depth violation.
    DepthExceeded,
}

/// Streaming security sanitizer.
///
/// Processes [`StreamEvent`] tokens and filters out dangerous content,
/// maintaining state to track skip/strip regions across multiple events.
pub struct StreamingSanitizer {
    /// Nesting depth of elements inside a dangerous element being skipped.
    /// When > 0, all events are suppressed.
    skip_depth: usize,
    /// Name of the outermost dangerous element that entered skip mode.
    /// Used to ensure only the matching end tag can exit skip mode,
    /// preventing mismatched end tags (e.g. `</div>` inside `<noscript>`)
    /// from prematurely re-enabling content.
    skip_element: Option<String>,
    /// Stack of element names that entered strip mode (tags removed, content kept).
    /// Using a stack instead of a simple counter ensures mismatched end tags
    /// (e.g., `<iframe>...</form>`) don't corrupt the strip state.
    strip_stack: Vec<String>,
    /// Open element names tracked for nesting-depth accounting.
    ///
    /// Using explicit names (rather than raw +/- counters) prevents malformed
    /// end tags from reducing depth incorrectly.
    nesting_stack: Vec<String>,
    /// Current HTML element nesting depth.
    nesting_depth: usize,
    /// Maximum allowed nesting depth.
    max_nesting_depth: usize,
    /// Noise-region pruning configuration.
    prune_config: PruneConfig,
    /// Depth counter for noise-region pruning. When > 0, events inside
    /// a pruned element (nav, footer, aside, etc.) are suppressed.
    prune_depth: usize,
    /// Name of the outermost pruned element that entered prune mode,
    /// for name-aware exit (same pattern as skip_element).
    prune_element: Option<String>,
    /// Tags that were implicitly closed by the most recent
    /// `close_optional_end_tags_for_start` call, in close order
    /// (innermost first). Consumed by the streaming converter to mirror
    /// the closures into the StructuralStateMachine so its context stack
    /// does not leak stale open elements (e.g. `Paragraph` surviving an
    /// implied `</p>` when `<div>` opens).
    pub(crate) implied_closures: Vec<String>,
}

impl StreamingSanitizer {
    /// Creates a new StreamingSanitizer configured with the default maximum nesting depth and empty state.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let s = StreamingSanitizer::new();
    /// assert_eq!(s.nesting_depth(), 0);
    /// assert!(!s.is_skipping());
    /// assert!(!s.is_stripping());
    /// ```
    pub fn new() -> Self {
        Self {
            skip_depth: 0,
            skip_element: None,
            strip_stack: Vec::new(),
            nesting_stack: Vec::new(),
            nesting_depth: 0,
            max_nesting_depth: MAX_NESTING_DEPTH,
            prune_config: PruneConfig::disabled(),
            prune_depth: 0,
            prune_element: None,
            implied_closures: Vec::new(),
        }
    }

    /// Estimate the physical heap memory currently retained by the
    /// sanitizer state.
    ///
    /// Counts capacity (allocated bytes), not logical length, for every
    /// long-lived allocation: `skip_element` / `prune_element` names,
    /// the strip / nesting / implied-closure stacks, and each stack
    /// entry's own capacity.  These allocations are attacker-derived
    /// (element names come from the input stream) and persist across
    /// chunks while a skip/strip/prune region is open, so they must be
    /// part of the parser working-set budget.
    ///
    /// Scalar counters (depths) are stack-resident and not counted.
    pub fn resident_bytes(&self) -> usize {
        let stack_entry_bytes = |stack: &Vec<String>| -> usize {
            stack
                .iter()
                .map(|s| s.capacity())
                .fold(0usize, usize::saturating_add)
                .saturating_add(
                    stack
                        .capacity()
                        .saturating_mul(std::mem::size_of::<String>()),
                )
        };

        self.skip_element
            .as_ref()
            .map_or(0, |s| s.capacity())
            .saturating_add(self.prune_element.as_ref().map_or(0, |s| s.capacity()))
            .saturating_add(stack_entry_bytes(&self.strip_stack))
            .saturating_add(stack_entry_bytes(&self.nesting_stack))
            .saturating_add(stack_entry_bytes(&self.implied_closures))
    }

    /// Creates a `StreamingSanitizer` with noise-region pruning enabled.
    ///
    /// Elements matching the prune config (nav, footer, aside, etc.) and
    /// their entire subtrees will be suppressed, equivalent to the
    /// full-buffer path's `should_prune_with_config()` behavior.
    pub fn with_prune_config(prune_config: PruneConfig) -> Self {
        Self {
            prune_config,
            ..Self::new()
        }
    }

    /// Creates a `StreamingSanitizer` configured with a custom maximum nesting depth.
    ///
    /// The sanitizer is initialized with default state (no skipping or stripping in progress)
    /// and `max_nesting_depth` set to `max_depth`.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let s = StreamingSanitizer::with_max_depth(10);
    /// assert_eq!(s.nesting_depth(), 0);
    /// assert!(!s.is_skipping());
    /// ```
    pub fn with_max_depth(max_depth: usize) -> Self {
        Self {
            max_nesting_depth: max_depth,
            ..Self::new()
        }
    }

    /// Process a `StreamEvent` and produce the sanitizer's decision for that token.
    ///
    /// The method updates internal sanitizer state (skip depth, strip stack, and
    /// nesting depth) as it classifies the event and returns a `SanitizeDecision`
    /// indicating whether the event should be emitted unchanged, emitted with
    /// modifications, suppressed, or rejected due to excessive nesting depth.
    ///
    /// # Returns
    ///
    /// A `SanitizeDecision` describing how the caller should handle the provided
    /// `StreamEvent`.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use nginx_markdown_converter::streaming::sanitizer::StreamingSanitizer;
    /// use nginx_markdown_converter::streaming::sanitizer::SanitizeDecision;
    /// use nginx_markdown_converter::streaming::types::StreamEvent;
    ///
    /// let mut s = StreamingSanitizer::new();
    /// let evt = StreamEvent::Text("hello".into());
    /// match s.process_event(evt) {
    ///     SanitizeDecision::Pass(e) => assert!(matches!(e, StreamEvent::Text(_))),
    ///     _ => panic!("unexpected decision"),
    /// }
    /// ```
    fn process_start_skip_state(
        &mut self,
        tag: &str,
        effectively_self_closing: bool,
    ) -> Option<SanitizeDecision> {
        if self.skip_depth > 0 {
            if !effectively_self_closing {
                self.skip_depth = self.skip_depth.saturating_add(1);
            }
            return Some(SanitizeDecision::Skip);
        }

        if self.prune_depth == 0 {
            self.close_optional_end_tags_for_start(tag);
        }
        if DANGEROUS_VOID_ELEMENTS.contains(&tag) {
            return Some(SanitizeDecision::Skip);
        }
        if DANGEROUS_CONTAINER_ELEMENTS.contains(&tag) {
            if !effectively_self_closing {
                self.skip_depth = 1;
                self.skip_element = Some(tag.to_string());
            }
            return Some(SanitizeDecision::Skip);
        }
        if self.prune_depth > 0 {
            if !effectively_self_closing {
                self.prune_depth = self.prune_depth.saturating_add(1);
            }
            return Some(SanitizeDecision::Skip);
        }
        if self.prune_config.enabled
            && matches!(
                should_prune_with_config(tag, &self.prune_config),
                crate::converter::pruning::PruneDecision::SkipSubtree
            )
        {
            if !effectively_self_closing {
                self.prune_depth = 1;
                self.prune_element = Some(tag.to_string());
            }
            return Some(SanitizeDecision::Skip);
        }
        None
    }

    fn remember_stripped_tag(&mut self, tag: &str, effectively_self_closing: bool) {
        if !effectively_self_closing {
            self.strip_stack.push(tag.to_string());
        }
    }

    fn url_decision(tag: &str, url: Option<String>) -> SanitizeDecision {
        match url {
            Some(url_value) if !is_dangerous_url(&url_value) => {
                let escaped = escape_markdown_destination(&url_value);
                SanitizeDecision::PassGenerated(StreamEvent::Text(format!(
                    "[{}]({})",
                    tag, escaped
                )))
            }
            _ => SanitizeDecision::Skip,
        }
    }

    fn process_embedded_start(
        &mut self,
        tag: &str,
        attrs: &[(String, String)],
        effectively_self_closing: bool,
    ) -> Option<SanitizeDecision> {
        if !EMBEDDED_CONTENT_ELEMENTS.contains(&tag) {
            return None;
        }
        self.remember_stripped_tag(tag, effectively_self_closing);
        let url = attrs
            .iter()
            .find(|(key, _)| key == "src" || key == "data")
            .map(|(_, value)| value.clone());
        Some(Self::url_decision(tag, url))
    }

    fn process_media_start(
        &mut self,
        tag: &str,
        attrs: &[(String, String)],
        effectively_self_closing: bool,
    ) -> Option<SanitizeDecision> {
        if !MEDIA_CONTENT_ELEMENTS.contains(&tag) {
            return None;
        }
        self.remember_stripped_tag(tag, effectively_self_closing);
        let url = match tag {
            "area" => attrs
                .iter()
                .find(|(key, _)| key == "href")
                .or_else(|| attrs.iter().find(|(key, _)| key == "src"))
                .map(|(_, value)| value.clone()),
            _ => attrs
                .iter()
                .find(|(key, _)| key == "src")
                .map(|(_, value)| value.clone()),
        };
        Some(Self::url_decision(tag, url))
    }

    fn process_form_start(
        &mut self,
        tag: &str,
        attrs: &[(String, String)],
        effectively_self_closing: bool,
    ) -> Option<SanitizeDecision> {
        if !FORM_ELEMENTS.contains(&tag) && !VOID_FORM_CONTROLS.contains(&tag) {
            return None;
        }
        if tag == "input" {
            let input_type = attrs
                .iter()
                .find(|(name, _)| name == "type")
                .map(|(_, value)| value.to_ascii_lowercase())
                .unwrap_or_else(|| "text".to_string());
            let text = if matches!(input_type.as_str(), "hidden" | "image") {
                None
            } else if matches!(input_type.as_str(), "submit" | "reset") {
                attrs
                    .iter()
                    .find(|(name, _)| name == "value")
                    .map(|(_, value)| value.as_str())
            } else {
                attrs
                    .iter()
                    .find(|(name, _)| name == "aria-label")
                    .or_else(|| attrs.iter().find(|(name, _)| name == "placeholder"))
                    .or_else(|| attrs.iter().find(|(name, _)| name == "value"))
                    .map(|(_, value)| value.as_str())
            };
            return Some(
                match text.map(str::trim).filter(|value| !value.is_empty()) {
                    Some(value) => SanitizeDecision::PassGenerated(StreamEvent::Text(format!(
                        "{} ",
                        escape_markdown_text(value)
                    ))),
                    None => SanitizeDecision::Skip,
                },
            );
        }
        if !effectively_self_closing && !VOID_FORM_CONTROLS.contains(&tag) {
            self.strip_stack.push(tag.to_string());
        }
        Some(SanitizeDecision::Skip)
    }

    fn process_special_start(
        &mut self,
        tag: &str,
        attrs: &[(String, String)],
        effectively_self_closing: bool,
    ) -> Option<SanitizeDecision> {
        self.process_embedded_start(tag, attrs, effectively_self_closing)
            .or_else(|| self.process_media_start(tag, attrs, effectively_self_closing))
            .or_else(|| self.process_form_start(tag, attrs, effectively_self_closing))
    }

    fn process_start_tag(
        &mut self,
        name: String,
        attrs: Vec<(String, String)>,
        self_closing: bool,
    ) -> SanitizeDecision {
        let tag = name.as_str();
        let effectively_self_closing = self_closing || VOID_ELEMENTS.contains(&tag);
        if let Some(decision) = self.process_start_skip_state(tag, effectively_self_closing) {
            return decision;
        }

        if !effectively_self_closing {
            self.nesting_stack.push(tag.to_string());
            self.nesting_depth = self.nesting_stack.len();
            if self.nesting_depth > self.max_nesting_depth {
                return SanitizeDecision::DepthExceeded;
            }
        }
        if let Some(decision) = self.process_special_start(tag, &attrs, effectively_self_closing) {
            return decision;
        }

        let cleaned_attrs = sanitize_attributes(&attrs);
        if cleaned_attrs.len() != attrs.len() {
            return SanitizeDecision::PassModified(StreamEvent::StartTag {
                name,
                attrs: cleaned_attrs,
                self_closing,
            });
        }
        SanitizeDecision::Pass(StreamEvent::StartTag {
            name,
            attrs,
            self_closing,
        })
    }

    fn update_region_depth(depth: &mut usize, element: &mut Option<String>, tag: &str) -> bool {
        if *depth == 1 && element.as_deref() == Some(tag) {
            *depth = 0;
            *element = None;
            return true;
        }
        if *depth > 1 {
            *depth = depth.saturating_sub(1);
        }
        false
    }

    fn process_skip_end(&mut self, tag: &str) -> bool {
        if self.skip_depth == 0 {
            return false;
        }
        if Self::update_region_depth(&mut self.skip_depth, &mut self.skip_element, tag) {
            self.pop_open_tag(tag);
        }
        true
    }

    fn process_prune_end(&mut self, tag: &str) -> bool {
        if self.prune_depth == 0 {
            return false;
        }
        if Self::update_region_depth(&mut self.prune_depth, &mut self.prune_element, tag) {
            self.pop_open_tag(tag);
        }
        true
    }

    fn process_end_tag(&mut self, name: String) -> SanitizeDecision {
        let tag = name.as_str();
        if self.process_skip_end(tag) || self.process_prune_end(tag) {
            return SanitizeDecision::Skip;
        }

        self.pop_open_tag(tag);
        if EMBEDDED_CONTENT_ELEMENTS.contains(&tag)
            || MEDIA_CONTENT_ELEMENTS.contains(&tag)
            || FORM_ELEMENTS.contains(&tag)
        {
            if self.strip_stack.last().is_some_and(|entry| entry == tag) {
                self.strip_stack.pop();
            }
            return SanitizeDecision::Skip;
        }
        SanitizeDecision::Pass(StreamEvent::EndTag { name })
    }

    pub fn process_event(&mut self, event: StreamEvent) -> SanitizeDecision {
        self.implied_closures.clear();
        match event {
            StreamEvent::StartTag {
                name,
                attrs,
                self_closing,
            } => self.process_start_tag(name, attrs, self_closing),
            StreamEvent::EndTag { name } => self.process_end_tag(name),
            StreamEvent::Text(_) | StreamEvent::Comment(_) => {
                if self.skip_depth > 0 || self.prune_depth > 0 {
                    SanitizeDecision::Skip
                } else {
                    SanitizeDecision::Pass(event)
                }
            }
            StreamEvent::Doctype | StreamEvent::ParseError(_) => SanitizeDecision::Pass(event),
        }
    }

    /// Indicates whether the sanitizer is currently inside a dangerous element.
    ///
    /// When `true`, the sanitizer is suppressing events because at least one
    /// dangerous element has been opened and not yet closed.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let mut s = StreamingSanitizer::new();
    /// assert!(!s.is_skipping());
    /// ```
    pub fn is_skipping(&self) -> bool {
        self.skip_depth > 0
    }

    /// Indicates whether the sanitizer is currently in strip mode (element tags are being suppressed while their children continue to be processed).
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let s = StreamingSanitizer::new();
    /// assert!(!s.is_stripping());
    /// ```
    pub fn is_stripping(&self) -> bool {
        !self.strip_stack.is_empty()
    }

    /// Report the current element nesting depth tracked by the sanitizer.
    ///
    /// The value represents the number of open (non-self-closing) elements that
    /// are currently being counted toward the configured nesting limit.
    ///
    /// # Returns
    ///
    /// `usize` — the current nesting depth.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let mut s = StreamingSanitizer::new();
    /// assert_eq!(s.nesting_depth(), 0);
    /// ```
    pub fn nesting_depth(&self) -> usize {
        self.nesting_depth
    }

    /// Returns the current prune depth (0 if not pruning).
    #[cfg(test)]
    pub(crate) fn prune_depth(&self) -> usize {
        self.prune_depth
    }

    /// Removes the most recent occurrence of `tag` from the nesting stack.
    ///
    /// Uses `rposition` (searches from the top of the stack) rather than a
    /// simple `pop()` to correctly handle implicitly-closed or mismatched
    /// tags where the target may not be at the top.  After removal, nesting
    /// depth is recalculated from the stack length.
    fn pop_open_tag(&mut self, tag: &str) {
        if let Some(idx) = self.nesting_stack.iter().rposition(|open| open == tag) {
            self.truncate_nesting_stack(idx);
        }
        self.nesting_depth = self.nesting_stack.len();
    }

    /// Applies tree-builder implied end-tag behavior visible from start tags.
    fn close_optional_end_tags_for_start(&mut self, tag: &str) {
        if PARAGRAPH_CLOSING_START_TAGS.contains(&tag) {
            self.close_nearest_in_scope(&["p"], BUTTON_SCOPE_BOUNDARIES);
        }

        match tag {
            "li" => {
                self.close_nearest_in_scope(&["li"], LIST_ITEM_SCOPE_BOUNDARIES);
            }
            "dt" | "dd" => {
                self.close_nearest_in_scope(&["dt", "dd"], DEFINITION_SCOPE_BOUNDARIES);
            }
            "rb" => {
                self.close_nearest_in_scope(&["rb", "rt", "rtc", "rp"], RUBY_SCOPE_BOUNDARIES);
            }
            "rt" | "rtc" | "rp" => {
                self.close_nearest_in_scope(&["rb", "rt", "rtc", "rp"], RUBY_SCOPE_BOUNDARIES);
            }
            "option" => {
                self.close_nearest_in_scope(&["option"], SELECT_SCOPE_BOUNDARIES);
            }
            "optgroup" => {
                self.close_nearest_in_scope(&["option"], SELECT_SCOPE_BOUNDARIES);
                self.close_nearest_in_scope(&["optgroup"], SELECT_SCOPE_BOUNDARIES);
            }
            "colgroup" => {
                self.close_nearest_in_scope(&["colgroup"], TABLE_SCOPE_BOUNDARIES);
            }
            "thead" | "tbody" | "tfoot" => {
                self.close_nearest_in_scope(&["thead", "tbody", "tfoot"], TABLE_SCOPE_BOUNDARIES);
            }
            "tr" => {
                self.close_nearest_in_scope(&["td", "th"], TABLE_ROW_SCOPE_BOUNDARIES);
                self.close_nearest_in_scope(&["tr"], TABLE_SECTION_SCOPE_BOUNDARIES);
            }
            "td" | "th" => {
                self.close_nearest_in_scope(&["td", "th"], TABLE_ROW_SCOPE_BOUNDARIES);
            }
            _ => {}
        }
    }

    /// Closes the nearest target unless an HTML scope boundary is encountered.
    // Linear scan from the top of the open-element stack to find the
    // nearest target or scope boundary.  The worst-case cost is O(n) but
    // n is bounded by `max_nesting_depth` (default 1000).  This preserves
    // correct HTML implied-end-tag semantics for malformed or
    // optional-end-tag input.  Avoid replacing with a simpler pop-only
    // path unless equivalent scope semantics are maintained.
    fn close_nearest_in_scope(&mut self, targets: &[&str], boundaries: &[&str]) {
        let close_index = self.nesting_stack.iter().rposition(|open| {
            targets.contains(&open.as_str()) || boundaries.contains(&open.as_str())
        });

        if let Some(idx) = close_index
            && targets.contains(&self.nesting_stack[idx].as_str())
        {
            let closed = self.truncate_nesting_stack(idx);
            self.implied_closures.extend(closed);
        }
    }

    /// Removes an implicitly closed element and all of its open descendants.
    /// Returns the closed tag names in close order (innermost first).
    ///
    /// Uses `drain(index..)` which is O(n) in the number of elements from
    /// `index` to the stack end.  This cost is bounded by
    /// `max_nesting_depth`.  The linear truncation is required to unwind
    /// implied closures (e.g. `<p>` closed by `<div>`) while preserving
    /// correct scope semantics for nested lists, blockquotes, and other
    /// structured elements.
    fn truncate_nesting_stack(&mut self, index: usize) -> Vec<String> {
        let mut closed_tags: Vec<String> = self.nesting_stack.drain(index..).collect();
        for tag in closed_tags.iter().rev() {
            if let Some(strip_index) = self.strip_stack.iter().rposition(|open| open == tag) {
                self.strip_stack.remove(strip_index);
            }
        }
        self.nesting_depth = self.nesting_stack.len();
        closed_tags.reverse();
        closed_tags
    }
}

impl Default for StreamingSanitizer {
    /// Creates a `StreamingSanitizer` configured with the module's default settings.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let mut s = StreamingSanitizer::default();
    /// assert!(!s.is_skipping());
    /// assert!(!s.is_stripping());
    /// assert_eq!(s.nesting_depth(), 0);
    /// ```
    fn default() -> Self {
        Self::new()
    }
}

/// Checks whether a URL starts with a blocked dangerous scheme (after trimming and lowercasing).
///
/// The input is trimmed and converted to lowercase before comparison against the predefined
/// dangerous scheme prefixes.
///
/// # Examples
///
/// ```ignore
/// let safe = is_dangerous_url("https://example.com");
/// let dangerous = is_dangerous_url("   javascript:alert(1)");
/// assert_eq!(safe, false);
/// assert_eq!(dangerous, true);
/// ```
///
/// # Returns
///
/// `true` if the trimmed, lowercased URL begins with any dangerous scheme prefix, `false` otherwise.
pub(crate) fn is_dangerous_url(url: &str) -> bool {
    is_dangerous_url_value(url)
}

/// Filters an attribute list, removing event-handler attributes (names starting
/// with `on` except the exact name `"on"`), inline `style`, and `href`/`src`
/// attributes whose values use a dangerous URL scheme.
///
/// Returns a new `Vec<(String, String)>` containing only the allowed attributes.
///
/// # Examples
///
/// ```ignore
/// let attrs = vec![
///     ("onclick".to_string(), "alert(1)".to_string()),
///     ("on".to_string(), "not-an-event".to_string()),
///     ("href".to_string(), "javascript:alert(1)".to_string()),
///     ("href".to_string(), "https://example.com".to_string()),
///     ("title".to_string(), "Example".to_string()),
/// ];
/// let clean = sanitize_attributes(&attrs);
/// assert_eq!(clean, vec![
///     ("on".to_string(), "not-an-event".to_string()),
///     ("href".to_string(), "https://example.com".to_string()),
///     ("title".to_string(), "Example".to_string()),
/// ]);
/// ```
fn sanitize_attributes(attrs: &[(String, String)]) -> Vec<(String, String)> {
    attrs
        .iter()
        .filter(|(name, value)| {
            // Remove event handlers (on* prefix, but not bare "on")
            if name.len() > 2 && name.starts_with("on") {
                return false;
            }
            // Drop inline style to avoid CSS-based script/navigation vectors.
            if name == "style" {
                return false;
            }
            // Remove dangerous URLs from every URL-bearing attribute.
            if URL_ATTRIBUTES.contains(&name.as_str()) && is_dangerous_url(value) {
                return false;
            }
            true
        })
        .cloned()
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    /// Create a non-self-closing `StreamEvent::StartTag` from a tag name and attribute pairs.
    ///
    /// The provided attribute pairs (`(&str, &str)`) are converted into owned `String` name/value pairs
    /// in the resulting event.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let ev = start_tag("a", vec![("href", "https://example.com"), ("rel", "noopener")]);
    /// match ev {
    ///     StreamEvent::StartTag { name, attrs, self_closing } => {
    ///         assert_eq!(name, "a");
    ///         assert_eq!(self_closing, false);
    ///         assert!(attrs.contains(&(String::from("href"), String::from("https://example.com"))));
    ///     }
    ///     _ => panic!("expected StartTag"),
    /// }
    /// ```
    fn start_tag(name: &str, attrs: Vec<(&str, &str)>) -> StreamEvent {
        StreamEvent::StartTag {
            name: name.to_string(),
            attrs: attrs
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            self_closing: false,
        }
    }

    #[test]
    fn all_url_attributes_reject_dangerous_schemes() {
        let attrs: Vec<(String, String)> = URL_ATTRIBUTES
            .iter()
            .map(|name| ((*name).to_string(), "javascript:alert(1)".to_string()))
            .collect();
        assert!(sanitize_attributes(&attrs).is_empty());
    }

    #[test]
    fn input_control_text_matches_full_buffer_policy() {
        let mut sanitizer = StreamingSanitizer::new();
        let decision = sanitizer.process_event(start_tag(
            "input",
            vec![
                ("type", "text"),
                ("placeholder", "*search*"),
                ("value", "fallback"),
            ],
        ));
        assert_eq!(
            decision,
            SanitizeDecision::PassGenerated(StreamEvent::Text(r"\*search\* ".to_string(),))
        );
    }

    /// Creates a `StreamEvent::EndTag` for the given element name.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let ev = end_tag("div");
    /// match ev {
    ///     StreamEvent::EndTag { name } => assert_eq!(name, "div"),
    ///     _ => panic!("expected EndTag"),
    /// }
    /// ```
    fn end_tag(name: &str) -> StreamEvent {
        StreamEvent::EndTag {
            name: name.to_string(),
        }
    }

    /// Create a `StreamEvent::Text` containing the given string slice.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let ev = text("hello");
    /// match ev {
    ///     StreamEvent::Text(t) => assert_eq!(t, "hello"),
    ///     _ => panic!("expected Text event"),
    /// }
    /// ```
    fn text(s: &str) -> StreamEvent {
        StreamEvent::Text(s.to_string())
    }

    // --- Dangerous element removal ---

    #[test]
    fn test_script_element_removed() {
        let mut san = StreamingSanitizer::new();
        assert_eq!(
            san.process_event(start_tag("script", vec![])),
            SanitizeDecision::Skip
        );
        assert!(san.is_skipping());
        assert_eq!(
            san.process_event(text("alert('xss')")),
            SanitizeDecision::Skip
        );
        assert_eq!(san.process_event(end_tag("script")), SanitizeDecision::Skip);
        assert!(!san.is_skipping());
    }

    #[test]
    fn test_style_element_removed() {
        let mut san = StreamingSanitizer::new();
        assert_eq!(
            san.process_event(start_tag("style", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(
            san.process_event(text("body { color: red }")),
            SanitizeDecision::Skip
        );
        assert_eq!(san.process_event(end_tag("style")), SanitizeDecision::Skip);
    }

    #[test]
    fn test_all_dangerous_elements() {
        for elem in &["script", "style", "noscript", "applet", "link", "base"] {
            let mut san = StreamingSanitizer::new();
            assert_eq!(
                san.process_event(start_tag(elem, vec![])),
                SanitizeDecision::Skip,
                "Expected {} to be skipped",
                elem
            );
        }
    }

    #[test]
    fn test_nested_dangerous_elements() {
        let mut san = StreamingSanitizer::new();
        assert_eq!(
            san.process_event(start_tag("script", vec![])),
            SanitizeDecision::Skip
        );
        // Nested element inside script
        assert_eq!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.process_event(text("nested")), SanitizeDecision::Skip);
        assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        assert!(san.is_skipping()); // Still inside script
        assert_eq!(san.process_event(end_tag("script")), SanitizeDecision::Skip);
        assert!(!san.is_skipping());
    }

    // --- Embedded content elements ---

    #[test]
    fn test_iframe_stripped_with_url() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("iframe", vec![("src", "https://example.com")]));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert!(t.contains("https://example.com"));
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
        // Child text should pass through (strip mode)
        let child = san.process_event(text("fallback text"));
        assert!(matches!(child, SanitizeDecision::Pass(_)));
        assert_eq!(san.process_event(end_tag("iframe")), SanitizeDecision::Skip);
    }

    #[test]
    fn test_iframe_dangerous_url_blocked() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("iframe", vec![("src", "javascript:alert(1)")]));
        assert_eq!(decision, SanitizeDecision::Skip);
    }

    #[test]
    fn test_iframe_url_destination_escaped() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "iframe",
            vec![("src", "https://example.com/path?a=1&b=2)")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert!(
                    t.contains('<'),
                    "Parenthesis in URL must trigger angle-bracket escaping, got: {}",
                    t
                );
            }
            _ => panic!("Expected PassModified with escaped URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_media_url_destination_escaped() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "video",
            vec![("src", "https://example.com/vid)eo.mp4")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert!(
                    t.contains('<'),
                    "Parenthesis in URL must trigger angle-bracket escaping, got: {}",
                    t
                );
            }
            _ => panic!("Expected PassModified with escaped URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_object_data_url_extracted() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "object",
            vec![("data", "https://example.com/doc.pdf")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert!(t.contains("https://example.com/doc.pdf"));
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_video_src_url_extracted() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "video",
            vec![("src", "https://example.com/v.mp4")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert_eq!(t, "[video](https://example.com/v.mp4)");
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
        let child = san.process_event(text("fallback text"));
        assert!(matches!(child, SanitizeDecision::Pass(_)));
        assert_eq!(san.process_event(end_tag("video")), SanitizeDecision::Skip);
    }

    #[test]
    fn test_source_src_url_extracted() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "source",
            vec![("src", "https://example.com/a.mp3")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert_eq!(t, "[source](https://example.com/a.mp3)");
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_area_href_url_extracted() {
        let mut san = StreamingSanitizer::new();
        let decision =
            san.process_event(start_tag("area", vec![("href", "https://example.com/map")]));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert_eq!(t, "[area](https://example.com/map)");
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_track_src_url_extracted() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "track",
            vec![("src", "https://example.com/captions.vtt")],
        ));
        match decision {
            SanitizeDecision::PassGenerated(StreamEvent::Text(t)) => {
                assert_eq!(t, "[track](https://example.com/captions.vtt)");
            }
            _ => panic!("Expected PassModified with URL, got {:?}", decision),
        }
    }

    #[test]
    fn test_media_dangerous_url_blocked() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("audio", vec![("src", "javascript:alert(1)")]));
        assert_eq!(decision, SanitizeDecision::Skip);
    }

    // --- Form elements ---

    #[test]
    fn test_form_elements_stripped() {
        for elem in &[
            "form", "button", "select", "textarea", "fieldset", "label", "option",
        ] {
            let mut san = StreamingSanitizer::new();
            assert_eq!(
                san.process_event(start_tag(elem, vec![])),
                SanitizeDecision::Skip,
                "Expected {} tag to be stripped",
                elem
            );
            // Child text should pass through
            let child = san.process_event(text("form text"));
            assert!(
                matches!(child, SanitizeDecision::Pass(_)),
                "Expected child text of {} to pass",
                elem
            );
        }
    }

    // --- Event handler attributes ---

    #[test]
    fn test_event_handler_removed() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "div",
            vec![("onclick", "alert(1)"), ("class", "safe")],
        ));
        match decision {
            SanitizeDecision::PassModified(StreamEvent::StartTag { attrs, .. }) => {
                assert!(
                    !attrs.iter().any(|(k, _)| k == "onclick"),
                    "onclick should be removed"
                );
                assert!(
                    attrs.iter().any(|(k, _)| k == "class"),
                    "class should be kept"
                );
            }
            _ => panic!("Expected PassModified, got {:?}", decision),
        }
    }

    #[test]
    fn test_style_attribute_removed() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag(
            "div",
            vec![
                ("style", "background:url(javascript:alert(1))"),
                ("class", "safe"),
            ],
        ));
        match decision {
            SanitizeDecision::PassModified(StreamEvent::StartTag { attrs, .. }) => {
                assert!(!attrs.iter().any(|(k, _)| k == "style"));
                assert!(attrs.iter().any(|(k, _)| k == "class"));
            }
            _ => panic!("Expected PassModified, got {:?}", decision),
        }
    }

    #[test]
    fn test_bare_on_not_removed() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("div", vec![("on", "value")]));
        // "on" (2 chars) should NOT be treated as event handler
        assert!(matches!(decision, SanitizeDecision::Pass(_)));
    }

    // --- Dangerous URL schemes ---

    #[test]
    fn test_dangerous_url_in_href_removed() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("a", vec![("href", "javascript:alert(1)")]));
        match decision {
            SanitizeDecision::PassModified(StreamEvent::StartTag { attrs, .. }) => {
                assert!(
                    !attrs.iter().any(|(k, _)| k == "href"),
                    "dangerous href should be removed"
                );
            }
            _ => panic!("Expected PassModified, got {:?}", decision),
        }
    }

    #[test]
    fn test_safe_url_preserved() {
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("a", vec![("href", "https://example.com")]));
        assert!(matches!(decision, SanitizeDecision::Pass(_)));
    }

    #[test]
    fn test_all_dangerous_schemes() {
        for scheme in &["javascript:", "data:", "vbscript:", "file:", "about:"] {
            let url = format!("{}test", scheme);
            assert!(
                is_dangerous_url(&url),
                "Expected {} to be dangerous",
                scheme
            );
        }
    }

    #[test]
    fn test_dangerous_url_case_insensitive() {
        assert!(is_dangerous_url("JavaScript:alert(1)"));
        assert!(is_dangerous_url("JAVASCRIPT:alert(1)"));
    }

    #[test]
    fn test_non_ascii_scheme_prefix_is_rejected() {
        assert!(is_dangerous_url("java\u{0455}cript:alert(1)"));
        assert!(is_dangerous_url("\u{fffd}:payload"));
    }

    #[test]
    fn test_dangerous_url_with_control_chars() {
        assert!(is_dangerous_url("javascript:\u{0000}alert(1)"));
        assert!(is_dangerous_url("java\u{0009}script:alert(1)"));
    }

    #[test]
    fn test_dangerous_url_with_percent_encoded_control_chars() {
        assert!(is_dangerous_url("https://example.com/%00"));
        assert!(is_dangerous_url("https://example.com/%0a"));
        assert!(is_dangerous_url("https://example.com/%0d"));
        assert!(is_dangerous_url("https://example.com/%1f"));
        assert!(is_dangerous_url("https://example.com/%7f"));
        assert!(!is_dangerous_url("https://example.com/%20"));
        assert!(!is_dangerous_url("https://example.com/%41"));
    }

    // --- Nesting depth ---

    #[test]
    fn test_nesting_depth_exceeded() {
        let mut san = StreamingSanitizer::with_max_depth(3);
        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        // 4th level should exceed depth 3
        assert_eq!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::DepthExceeded
        );
    }

    // --- Normal elements pass through ---

    #[test]
    fn test_safe_elements_pass() {
        let mut san = StreamingSanitizer::new();
        assert!(matches!(
            san.process_event(start_tag("p", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(text("hello")),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(end_tag("p")),
            SanitizeDecision::Pass(_)
        ));
    }

    #[test]
    fn test_stray_end_tag_does_not_reduce_nesting_depth() {
        let mut san = StreamingSanitizer::new();
        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(san.nesting_depth(), 1);

        assert!(matches!(
            san.process_event(end_tag("span")),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(san.nesting_depth(), 1);

        assert!(matches!(
            san.process_event(end_tag("div")),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(san.nesting_depth(), 0);
    }

    #[test]
    fn test_optional_end_tag_siblings_do_not_accumulate_nesting_depth() {
        let cases = [
            (&["li", "li", "li", "li"][..], 1),
            (&["p", "span", "div"][..], 1),
            (&["dl", "dt", "dd"][..], 2),
            (&["ruby", "rb", "rt", "rp"][..], 2),
            (
                &["select", "optgroup", "option", "option", "optgroup"][..],
                2,
            ),
            (&["table", "colgroup", "colgroup"][..], 2),
            (&["table", "thead", "tbody", "tfoot"][..], 2),
        ];

        for (tags, expected_depth) in cases {
            let mut san = StreamingSanitizer::with_max_depth(tags.len());
            for tag in tags {
                assert!(matches!(
                    san.process_event(start_tag(tag, vec![])),
                    SanitizeDecision::Pass(_) | SanitizeDecision::Skip
                ));
            }
            assert_eq!(san.nesting_depth(), expected_depth, "tags: {tags:?}");
        }

        let mut table = StreamingSanitizer::with_max_depth(4);
        for tag in ["table", "tbody", "tr", "td", "td", "tr", "td"] {
            assert!(matches!(
                table.process_event(start_tag(tag, vec![])),
                SanitizeDecision::Pass(_)
            ));
        }
        assert_eq!(table.nesting_depth(), 4);

        let mut pruned = StreamingSanitizer::with_max_depth(1);
        pruned.prune_config.enabled = true;
        pruned.prune_config.selectors = vec!["nav".to_string()];
        assert!(matches!(
            pruned.process_event(start_tag("p", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(
            pruned.process_event(start_tag("nav", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(pruned.nesting_depth(), 0);
    }

    #[test]
    fn test_optional_end_tag_rules_preserve_genuine_nested_list_items() {
        let mut san = StreamingSanitizer::with_max_depth(4);

        for tag in ["ul", "li", "ul", "li"] {
            assert!(matches!(
                san.process_event(start_tag(tag, vec![])),
                SanitizeDecision::Pass(_)
            ));
        }
        assert_eq!(san.nesting_depth(), 4);

        assert_eq!(
            san.process_event(start_tag("span", vec![])),
            SanitizeDecision::DepthExceeded
        );
    }

    #[test]
    fn test_dangerous_void_elements_do_not_enter_skip_mode() {
        let mut san = StreamingSanitizer::new();
        assert_eq!(
            san.process_event(start_tag("link", vec![("href", "https://x.test")],)),
            SanitizeDecision::Skip
        );
        assert!(!san.is_skipping());

        assert_eq!(
            san.process_event(start_tag("base", vec![("href", "https://x.test")],)),
            SanitizeDecision::Skip
        );
        assert!(!san.is_skipping());
    }

    // --- Mismatched tag resilience ---

    /// Verify that deep nesting inside a dangerous element does not affect
    /// `nesting_depth` and cannot bypass the depth limit. This documents
    /// the design decision explained in the `process_event` comments:
    /// content inside dangerous elements is fully discarded, so its
    /// nesting depth is irrelevant to security.
    #[test]
    fn test_deep_nesting_inside_dangerous_element_is_safe() {
        let mut san = StreamingSanitizer::with_max_depth(5);

        // Open a script element (skipped, does not enter nesting_stack)
        assert_eq!(
            san.process_event(start_tag("script", vec![])),
            SanitizeDecision::Skip
        );
        assert!(san.is_skipping());
        assert_eq!(san.nesting_depth(), 0);

        // Nest 100 elements inside the script — all skipped, nesting_depth
        // stays at 0 because these elements never reach the emitter.
        for _ in 0..100 {
            assert_eq!(
                san.process_event(start_tag("div", vec![])),
                SanitizeDecision::Skip
            );
        }
        // nesting_depth should still be 0 (dangerous elements do not
        // contribute to nesting_stack)
        assert_eq!(
            san.nesting_depth(),
            0,
            "nesting_depth should not increase for elements inside a dangerous element"
        );

        // Close all 100 inner elements
        for _ in 0..100 {
            assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        }
        assert!(san.is_skipping(), "still inside script");

        // Close the script
        assert_eq!(san.process_event(end_tag("script")), SanitizeDecision::Skip);
        assert!(!san.is_skipping());
        assert_eq!(san.nesting_depth(), 0);

        // After exiting the dangerous element, the depth limit still works
        // normally for subsequent elements.
        for _ in 0..5 {
            assert!(matches!(
                san.process_event(start_tag("div", vec![])),
                SanitizeDecision::Pass(_)
            ));
        }
        // 6th level should exceed depth 5
        assert_eq!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::DepthExceeded
        );
    }

    #[test]
    fn test_mismatched_end_tag_does_not_corrupt_strip_state() {
        // Regression: <iframe>...</form> should not decrement the strip
        // stack because </form> doesn't match the <iframe> that started it.
        let mut san = StreamingSanitizer::new();
        let decision = san.process_event(start_tag("iframe", vec![("src", "https://example.com")]));
        // iframe enters strip mode
        assert!(
            matches!(decision, SanitizeDecision::PassGenerated(_)),
            "iframe should be stripped with URL"
        );
        assert!(san.is_stripping());

        // Mismatched </form> should NOT exit strip mode
        assert_eq!(san.process_event(end_tag("form")), SanitizeDecision::Skip);
        assert!(
            san.is_stripping(),
            "mismatched </form> must not exit iframe strip mode"
        );

        // Correct </iframe> should exit strip mode
        assert_eq!(san.process_event(end_tag("iframe")), SanitizeDecision::Skip);
        assert!(
            !san.is_stripping(),
            "matching </iframe> should exit strip mode"
        );
    }

    /// Regression: a mismatched end tag inside a dangerous element must not
    /// prematurely exit skip mode. html5ever's tokenizer emits nested tags
    /// normally for `<noscript>` and `<applet>` (unlike `<script>`/`<style>`
    /// which use the raw-text state), so the sanitizer must be name-aware.
    #[test]
    fn test_mismatched_end_tag_does_not_exit_skip_mode() {
        let mut san = StreamingSanitizer::new();

        // Enter skip mode via <noscript>
        assert_eq!(
            san.process_event(start_tag("noscript", vec![])),
            SanitizeDecision::Skip
        );
        assert!(san.is_skipping());

        // Mismatched </div> must NOT exit skip mode
        assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        assert!(
            san.is_skipping(),
            "mismatched </div> must not exit noscript skip mode"
        );

        // Content after the mismatched end tag must still be skipped
        assert_eq!(
            san.process_event(text("should be skipped")),
            SanitizeDecision::Skip,
            "text after mismatched end tag must remain skipped"
        );

        // Only the matching </noscript> should exit skip mode
        assert_eq!(
            san.process_event(end_tag("noscript")),
            SanitizeDecision::Skip
        );
        assert!(
            !san.is_skipping(),
            "matching </noscript> should exit skip mode"
        );

        // Content after the matching end tag should pass through
        assert!(matches!(
            san.process_event(text("visible")),
            SanitizeDecision::Pass(_)
        ));
    }

    // --- Property-based tests ---
    // Feature: rust-streaming-engine-core, Property 4: Streaming Sanitizer Security Equivalence

    /// Produces a proptest strategy that generates HTML element names treated as dangerous by the sanitizer.
    ///
    /// The strategy yields one of: "script", "style", "noscript", "applet", "link", "base".
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use proptest::prelude::*;
    /// let strat = arb_dangerous_element();
    /// proptest!(|(tag in strat)| {
    ///     assert!(["script","style","noscript","applet","link","base"].contains(&tag.as_str()));
    /// });
    /// ```
    fn arb_dangerous_element() -> impl Strategy<Value = String> {
        prop::sample::select(vec![
            "script".to_string(),
            "style".to_string(),
            "noscript".to_string(),
            "applet".to_string(),
            "link".to_string(),
            "base".to_string(),
        ])
    }

    /// Produces a proptest strategy that generates common safe HTML element tag names.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use proptest::prelude::*;
    /// // Create the strategy and draw a single example value.
    /// let strat = arb_safe_element();
    /// let mut runner = proptest::test_runner::TestRunner::default();
    /// let value = strat.new_tree(&mut runner).unwrap().current();
    /// assert!(["div","p","span","h1","a","ul"].contains(&value.as_str()));
    /// ```
    fn arb_safe_element() -> impl Strategy<Value = String> {
        prop::sample::select(vec![
            "div".to_string(),
            "p".to_string(),
            "span".to_string(),
            "h1".to_string(),
            "a".to_string(),
            "ul".to_string(),
        ])
    }

    proptest! {
        /// **Validates: Requirements 3.1, 3.6**
        ///
        /// All dangerous elements must be skipped regardless of which one is used.
        /// Void dangerous elements (link, base) are skipped as a single event
        /// without entering persistent skip mode.
        #[test]
        fn prop_dangerous_elements_always_skipped(elem in arb_dangerous_element()) {
            let mut san = StreamingSanitizer::new();
            let decision = san.process_event(StreamEvent::StartTag {
                name: elem.clone(),
                attrs: vec![],
                self_closing: false,
            });
            prop_assert_eq!(decision, SanitizeDecision::Skip,
                "Dangerous element '{}' should be skipped", elem);
            // Void elements (link, base) don't enter persistent skip mode
            let is_void = VOID_ELEMENTS.contains(&elem.as_str());
            if is_void {
                prop_assert!(!san.is_skipping(),
                    "Void dangerous element '{}' should not enter skip mode", elem);
            } else {
                prop_assert!(san.is_skipping(),
                    "Non-void dangerous element '{}' should enter skip mode", elem);
            }
        }

        /// **Validates: Requirements 3.1**
        ///
        /// Safe elements must always pass through the sanitizer.
        #[test]
        fn prop_safe_elements_always_pass(elem in arb_safe_element()) {
            let mut san = StreamingSanitizer::new();
            let decision = san.process_event(StreamEvent::StartTag {
                name: elem.clone(),
                attrs: vec![],
                self_closing: false,
            });
            prop_assert!(matches!(decision, SanitizeDecision::Pass(_)),
                "Safe element '{}' should pass", elem);
        }

        /// **Validates: Requirements 3.2**
        ///
        /// Event handler attributes (on* prefix) must always be removed.
        #[test]
        fn prop_event_handlers_always_removed(
            handler in prop::sample::select(vec![
                "onclick".to_string(), "onload".to_string(), "onerror".to_string(),
                "onmouseover".to_string(), "onfocus".to_string(),
            ])
        ) {
            let mut san = StreamingSanitizer::new();
            let decision = san.process_event(StreamEvent::StartTag {
                name: "div".to_string(),
                attrs: vec![(handler.clone(), "alert(1)".to_string())],
                self_closing: false,
            });
            match decision {
                SanitizeDecision::PassModified(StreamEvent::StartTag { attrs, .. }) => {
                    prop_assert!(!attrs.iter().any(|(k, _)| k == &handler),
                        "Event handler '{}' should be removed", handler);
                }
                _ => prop_assert!(false, "Expected PassModified for event handler removal"),
            }
        }

        /// **Validates: Requirements 3.3**
        ///
        /// Dangerous URL schemes must always be detected as dangerous.
        #[test]
        fn prop_dangerous_urls_always_blocked(
            scheme in prop::sample::select(vec![
                "javascript:".to_string(), "data:".to_string(), "vbscript:".to_string(),
                "file:".to_string(), "about:".to_string(),
            ]),
            suffix in "[a-z]{1,20}",
        ) {
            let url = format!("{}{}", scheme, suffix);
            prop_assert!(is_dangerous_url(&url), "URL '{}' should be dangerous", url);
        }
    }

    #[test]
    fn test_pruned_element_does_not_enter_nesting_stack() {
        let mut san = StreamingSanitizer::with_max_depth(10);
        san.prune_config.enabled = true;
        san.prune_config.selectors = vec!["nav".to_string()];

        assert_eq!(
            san.process_event(start_tag("nav", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(
            san.nesting_depth(),
            0,
            "pruned nav should not increase nesting_depth"
        );
        assert_eq!(san.prune_depth(), 1);

        assert_eq!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.nesting_depth(), 0);

        assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        assert_eq!(san.process_event(end_tag("nav")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 0);
        assert_eq!(san.nesting_depth(), 0);
    }

    #[test]
    fn test_mismatched_end_tag_inside_prune_region() {
        let mut san = StreamingSanitizer::with_max_depth(10);
        san.prune_config.enabled = true;
        san.prune_config.selectors = vec!["footer".to_string()];

        assert_eq!(
            san.process_event(start_tag("footer", vec![])),
            SanitizeDecision::Skip
        );

        assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        assert_eq!(
            san.prune_depth(),
            1,
            "mismatched end tag should not exit prune"
        );

        assert_eq!(san.process_event(end_tag("footer")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 0);
    }

    #[test]
    fn test_text_and_comments_suppressed_during_prune() {
        let mut san = StreamingSanitizer::with_max_depth(10);
        san.prune_config.enabled = true;
        san.prune_config.selectors = vec!["aside".to_string()];

        assert_eq!(
            san.process_event(start_tag("aside", vec![])),
            SanitizeDecision::Skip
        );

        let text_event = StreamEvent::Text("important content".into());
        assert_eq!(san.process_event(text_event), SanitizeDecision::Skip);

        let comment_event = StreamEvent::Comment("<!-- hidden -->".into());
        assert_eq!(san.process_event(comment_event), SanitizeDecision::Skip);

        assert_eq!(san.process_event(end_tag("aside")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 0);
    }

    #[test]
    fn test_prune_depth_increments_for_nested_elements() {
        let mut san = StreamingSanitizer::with_max_depth(10);
        san.prune_config.enabled = true;
        san.prune_config.selectors = vec!["nav".to_string()];

        assert_eq!(
            san.process_event(start_tag("nav", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.prune_depth(), 1);

        assert_eq!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.prune_depth(), 2);

        assert_eq!(
            san.process_event(start_tag("span", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.prune_depth(), 3);

        assert_eq!(san.process_event(end_tag("span")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 2);

        assert_eq!(san.process_event(end_tag("div")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 1);

        assert_eq!(san.process_event(end_tag("nav")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 0);
    }

    #[test]
    fn test_nesting_depth_intact_after_prune_exit() {
        let mut san = StreamingSanitizer::with_max_depth(10);
        san.prune_config.enabled = true;
        san.prune_config.selectors = vec!["nav".to_string()];

        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(san.nesting_depth(), 1);

        assert_eq!(
            san.process_event(start_tag("nav", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(
            san.process_event(start_tag("p", vec![])),
            SanitizeDecision::Skip
        );
        assert_eq!(san.process_event(end_tag("p")), SanitizeDecision::Skip);
        assert_eq!(san.process_event(end_tag("nav")), SanitizeDecision::Skip);
        assert_eq!(san.prune_depth(), 0);

        assert_eq!(
            san.nesting_depth(),
            1,
            "nesting_depth should still be 1 after prune exit"
        );

        assert!(matches!(
            san.process_event(end_tag("div")),
            SanitizeDecision::Pass(_)
        ));
        assert_eq!(san.nesting_depth(), 0);
    }

    // ── resident_bytes accounting (parser budget) ──────────────────

    #[test]
    fn test_resident_bytes_empty_state_is_zero() {
        let san = StreamingSanitizer::new();
        assert_eq!(san.resident_bytes(), 0, "empty sanitizer retains no heap");
    }

    #[test]
    fn test_resident_bytes_grows_with_retained_state_and_never_shrinks_below_capacity() {
        let mut san = StreamingSanitizer::new();

        // Enter a skip region (script is a dangerous container element).
        assert_eq!(
            san.process_event(start_tag("script", vec![])),
            SanitizeDecision::Skip
        );
        let after_skip = san.resident_bytes();
        assert!(
            after_skip > 0,
            "retained skip_element name must be accounted, got {after_skip}"
        );

        // Exit the skip region, then open normal nested elements:
        // nesting_stack entries must add to the retained estimate.
        assert_eq!(san.process_event(end_tag("script")), SanitizeDecision::Skip);
        assert!(matches!(
            san.process_event(start_tag("div", vec![])),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(start_tag("span", vec![])),
            SanitizeDecision::Pass(_)
        ));
        let after_nesting = san.resident_bytes();
        assert!(after_nesting > 0, "nesting stack entries must be accounted");

        // Exit everything: allocations are released, accounting drops.
        assert!(matches!(
            san.process_event(end_tag("span")),
            SanitizeDecision::Pass(_)
        ));
        assert!(matches!(
            san.process_event(end_tag("div")),
            SanitizeDecision::Pass(_)
        ));
        let after_exit = san.resident_bytes();
        assert!(
            after_exit < after_nesting,
            "closing regions must release retained entries ({} < {})",
            after_exit,
            after_nesting
        );
    }

    // =========================================================================
    // Task 13.4 — accounting test for deep nesting + skip/strip/prune
    // =========================================================================

    /// Test 7: resident_bytes grows with deeply nested skip/strip/nesting.
    ///
    /// Feed deeply nested HTML with skip (script), strip (form), and normal
    /// nesting (div) elements. Verify resident_bytes() increases with each
    /// additional layer, demonstrating all stacks contribute to accounting.
    #[test]
    fn test_resident_bytes_grows_with_deep_nesting() {
        let mut san = StreamingSanitizer::new();

        let baseline = san.resident_bytes();
        assert_eq!(baseline, 0, "empty sanitizer has no retained heap");

        // Push nested div elements to grow nesting_stack
        for _ in 0..16 {
            assert!(matches!(
                san.process_event(start_tag("div", vec![])),
                SanitizeDecision::Pass(_)
            ));
        }
        let after_16_divs = san.resident_bytes();
        assert!(
            after_16_divs > baseline,
            "16 nested divs must increase resident_bytes: {} > {}",
            after_16_divs,
            baseline
        );

        // Verify a specific numeric relationship: each div pushes a String
        // "div" (len 3, capacity >= 3) onto nesting_stack. With 16 entries,
        // the nesting stack alone should contribute at least 16 * 3 bytes
        // of String payload capacity.
        assert!(
            after_16_divs >= 16 * 3,
            "16 nested divs: resident_bytes ({}) must be >= 48 (16 * 3 bytes \
             minimum per 'div' String capacity)",
            after_16_divs
        );

        // Enter a form element (strip mode) inside the nesting
        san.process_event(start_tag("form", vec![]));
        let after_strip = san.resident_bytes();
        assert!(
            after_strip > after_16_divs,
            "entering strip mode (form) must increase resident_bytes: {} > {}",
            after_strip,
            after_16_divs
        );

        // Enter a script element inside the form (skip mode, nested)
        san.process_event(start_tag("script", vec![]));
        let after_skip = san.resident_bytes();
        assert!(
            after_skip > after_strip,
            "entering skip mode (script) must increase resident_bytes: {} > {}",
            after_skip,
            after_strip
        );
    }
}
