# ARCHIVED — historical record only. THIS FILE IS NOT A PACKAGING SURFACE.
#
# The live spec is packaging/rpm/SPECS/nginx-module-markdown.spec, which carries
# a parameterized %{version} and is the one release-rpm.yml builds. Every
# release workflow, build script, and test reads that file; nothing reads this
# one.
#
# Why it stays here instead of moving to an archive tree: the release gate
# tools/release/gates/validate_package_metadata.py lists this exact path in
# MODULE_NAME_SURFACES and fails the gate with `module-name:exists` when it is
# absent. Moving it would break that gate, which owns the check.
#
# The `Version: 0.6.1` below is the frozen historical value of this record, not
# a current release version. No scanner reads a version out of a .spec file:
# the harness detectors scan *.py and *.sh, Semgrep covers those extensions
# only, and the gate above checks field presence rather than field values. No
# scan-exclusion marker is therefore required, and the version is deliberately
# left as the history it documents.
#
# Do not edit this file for a release. Edit the live spec instead.
Name:           nginx-module-markdown-for-agents
Version:        0.6.1
Release:        1%{?dist}
Summary:        NGINX module for HTML-to-Markdown conversion

License:        BSD-2-Clause
URL:            https://github.com/cnkang/nginx-markdown-for-agents
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  cargo
BuildRequires:  rustc
BuildRequires:  pcre-devel
BuildRequires:  zlib-devel
BuildRequires:  openssl-devel
BuildRequires:  nginx-devel >= 1.26.0
BuildRequires:  nginx-devel < 1.27.0
Requires:       nginx >= 1:1.26.0

%description
NGINX filter module that converts HTML responses to Markdown
for AI agent consumption. Supports streaming, CommonMark/GFM flavors,
noise pruning, token estimation, and conditional requests.

%prep
%setup -q

%build
make build

%install
make install DESTDIR=%{buildroot}

%files
%doc README.md
%license LICENSE
%{_libdir}/nginx/modules/ngx_http_markdown_filter_module.so

%changelog
* Wed May 06 2026 Kang - 0.6.1-1
- v0.6.1: harness Rules 27-31, output-safety risk pack, dynconf two-phase reload

* Sat May 02 2026 Kang - 0.6.0-1
- Initial RPM package for v0.6.0
