// DO NOT EDIT — generated by tools/reason-codegen/generate.py
// Source: components/rust-converter/reason_registry.toml
// Source SHA-256: bd302c40372a40777ed12b0dec324c75c43f4fdb03e6ae3b364b3019346cd997
//
// Regenerate with: python3 tools/reason-codegen/generate.py

//! Generated reason-code projection for the declarative registry.
//!
//! The canonical source is `reason_registry.toml`; this module defines
//! the [`ReasonCode`] enum projected from that registry. It represents
//! every possible outcome of the module's conversion decision chain.
//! C code accesses these values through FFI, and all metrics, logging, and
//! documentation use the generated projections.
//!
//! # FFI Boundary
//!
//! The enum uses `#[repr(u8)]` so the compiler guarantees all discriminants
//! fit in a single byte, matching the C reason-code accessors.
//! Each variant has a stable numeric discriminant that must not change once
//! assigned.

/// Total number of reason code variants.
///
/// This constant is used by the closure test to verify that all variants
/// are accounted for in the `ALL` array. Update this when adding variants.
pub const REASON_CODE_COUNT: usize = 27;

/// Compile-time guard: all discriminants must fit in a `u8` because the
/// FFI boundary transports reason-code discriminants as `u8`.
/// If the enum grows beyond 256 variants this assertion will fail the build.
const _: () = assert!(
    REASON_CODE_COUNT <= 256,
    "ReasonCode discriminant range exceeds the u8 FFI transport"
);

/// Generated reason code enum projected from `reason_registry.toml`.
///
/// Every conversion decision path produces exactly one `ReasonCode`.
/// The numeric discriminants are stable and must not be reordered.
///
/// # Repr
///
/// Uses `#[repr(u8)]` so the compiler guarantees all discriminants fit in
/// a single byte. The enum is never passed directly across FFI; only its
/// discriminant value is transported as `u8`.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReasonCode {
    /// Reason: converted (stage: conversion)
    Converted = 0,

    /// Reason: skipped_accept (stage: eligibility)
    SkippedAccept = 1,

    /// Reason: skipped_no_accept (stage: eligibility)
    SkippedNoAccept = 2,

    /// Reason: skipped_conditional (stage: eligibility)
    SkippedConditional = 3,

    /// Reason: decompression_error (stage: decompression)
    DecompressionError = 4,

    /// Reason: decompression_budget_exceeded (stage: decompression)
    DecompressionBudgetExceeded = 5,

    /// Reason: decompression_format_error (stage: decompression)
    DecompressionFormatError = 6,

    /// Reason: decompression_truncated_input (stage: decompression)
    DecompressionTruncatedInput = 7,

    /// Reason: decompression_io_error (stage: decompression)
    DecompressionIoError = 8,

    /// Reason: timeout (stage: parsing)
    Timeout = 9,

    /// Reason: budget_exceeded (stage: parsing)
    BudgetExceeded = 10,

    /// Reason: replay_error (stage: precommit)
    ReplayError = 11,

    /// Reason: skipped_accept_reject (stage: eligibility)
    SkippedAcceptReject = 12,

    /// Reason: ffi_panic (stage: conversion)
    FfiPanic = 13,

    /// Reason: not_eligible (stage: eligibility)
    NotEligible = 14,

    /// Reason: disabled (stage: eligibility)
    Disabled = 15,

    /// Reason: failed_open (stage: delivery)
    FailedOpen = 16,

    /// Reason: failed_closed (stage: delivery)
    FailedClosed = 17,

    /// Reason: conversion_error (stage: conversion)
    ConversionError = 18,

    /// Reason: memory_budget_exceeded (stage: conversion)
    MemoryBudgetExceeded = 19,

    /// Reason: overload (stage: eligibility)
    Overload = 20,

    /// Reason: invalid_dynconf (stage: dynconf)
    InvalidDynconf = 21,

    /// Reason: degraded_snapshot (stage: dynconf)
    DegradedSnapshot = 22,

    /// Reason: header_plan_apply_error (stage: precommit)
    HeaderPlanApplyError = 23,

    /// Reason: streaming_mid_flight_error (stage: delivery)
    StreamingMidFlightError = 24,

    /// Reason: bypass_no_transform (stage: eligibility)
    BypassNoTransform = 25,

    /// Reason: encoding_header_invalid (stage: decompression)
    EncodingHeaderInvalid = 26,
}

#[cfg(test)]
#[path = "reason_code_complexity_tests.rs"]
mod reason_code_complexity_tests;

/// Array of all reason code variants for exhaustive iteration.
///
/// This array must contain every variant of [`ReasonCode`] exactly once.
/// The closure test verifies this invariant.
///
/// cbindgen:ignore
pub const ALL: [ReasonCode; REASON_CODE_COUNT] = [
    ReasonCode::Converted,
    ReasonCode::SkippedAccept,
    ReasonCode::SkippedNoAccept,
    ReasonCode::SkippedConditional,
    ReasonCode::DecompressionError,
    ReasonCode::DecompressionBudgetExceeded,
    ReasonCode::DecompressionFormatError,
    ReasonCode::DecompressionTruncatedInput,
    ReasonCode::DecompressionIoError,
    ReasonCode::Timeout,
    ReasonCode::BudgetExceeded,
    ReasonCode::ReplayError,
    ReasonCode::SkippedAcceptReject,
    ReasonCode::FfiPanic,
    ReasonCode::NotEligible,
    ReasonCode::Disabled,
    ReasonCode::FailedOpen,
    ReasonCode::FailedClosed,
    ReasonCode::ConversionError,
    ReasonCode::MemoryBudgetExceeded,
    ReasonCode::Overload,
    ReasonCode::InvalidDynconf,
    ReasonCode::DegradedSnapshot,
    ReasonCode::HeaderPlanApplyError,
    ReasonCode::StreamingMidFlightError,
    ReasonCode::BypassNoTransform,
    ReasonCode::EncodingHeaderInvalid,
];

impl ReasonCode {
    /// Return the lowercase snake_case string representation.
    ///
    /// This string is used in structured logs, diagnostics endpoints,
    /// and as the label value in Prometheus metrics.
    ///
    /// # Examples
    ///
    /// ```
    /// use nginx_markdown_converter::decision::reason_code::ReasonCode;
    ///
    /// assert_eq!(ReasonCode::Converted.as_str(), "converted");
    /// assert_eq!(ReasonCode::Timeout.as_str(), "timeout");
    /// ```
    pub fn as_str(self) -> &'static str {
        match self {
            ReasonCode::Converted => "converted",
            ReasonCode::SkippedAccept => "skipped_accept",
            ReasonCode::SkippedNoAccept => "skipped_no_accept",
            ReasonCode::SkippedConditional => "skipped_conditional",
            ReasonCode::DecompressionError => "decompression_error",
            ReasonCode::DecompressionBudgetExceeded => "decompression_budget_exceeded",
            ReasonCode::DecompressionFormatError => "decompression_format_error",
            ReasonCode::DecompressionTruncatedInput => "decompression_truncated_input",
            ReasonCode::DecompressionIoError => "decompression_io_error",
            ReasonCode::Timeout => "timeout",
            ReasonCode::BudgetExceeded => "budget_exceeded",
            ReasonCode::ReplayError => "replay_error",
            ReasonCode::SkippedAcceptReject => "skipped_accept_reject",
            ReasonCode::FfiPanic => "ffi_panic",
            ReasonCode::NotEligible => "not_eligible",
            ReasonCode::Disabled => "disabled",
            ReasonCode::FailedOpen => "failed_open",
            ReasonCode::FailedClosed => "failed_closed",
            ReasonCode::ConversionError => "conversion_error",
            ReasonCode::MemoryBudgetExceeded => "memory_budget_exceeded",
            ReasonCode::Overload => "overload",
            ReasonCode::InvalidDynconf => "invalid_dynconf",
            ReasonCode::DegradedSnapshot => "degraded_snapshot",
            ReasonCode::HeaderPlanApplyError => "header_plan_apply_error",
            ReasonCode::StreamingMidFlightError => "streaming_mid_flight_error",
            ReasonCode::BypassNoTransform => "bypass_no_transform",
            ReasonCode::EncodingHeaderInvalid => "encoding_header_invalid",
        }
    }

    /// Return the Prometheus metric key name for this reason code.
    ///
    /// # Examples
    ///
    /// ```
    /// use nginx_markdown_converter::decision::reason_code::ReasonCode;
    ///
    /// assert_eq!(
    ///     ReasonCode::Converted.metric_key(),
    ///     "markdown_conversions_total"
    /// );
    /// ```
    pub fn metric_key(self) -> &'static str {
        match self {
            ReasonCode::Converted => "markdown_conversions_total",
            ReasonCode::SkippedAccept => "markdown_skipped_total",
            ReasonCode::SkippedNoAccept => "markdown_skipped_total",
            ReasonCode::SkippedConditional => "markdown_skipped_total",
            ReasonCode::DecompressionError => "markdown_errors_total",
            ReasonCode::DecompressionBudgetExceeded => "markdown_errors_total",
            ReasonCode::DecompressionFormatError => "markdown_errors_total",
            ReasonCode::DecompressionTruncatedInput => "markdown_errors_total",
            ReasonCode::DecompressionIoError => "markdown_errors_total",
            ReasonCode::Timeout => "markdown_errors_total",
            ReasonCode::BudgetExceeded => "markdown_errors_total",
            ReasonCode::ReplayError => "markdown_errors_total",
            ReasonCode::SkippedAcceptReject => "markdown_skipped_total",
            ReasonCode::FfiPanic => "markdown_errors_total",
            ReasonCode::NotEligible => "markdown_skipped_total",
            ReasonCode::Disabled => "markdown_skipped_total",
            ReasonCode::FailedOpen => "markdown_failed_open_total",
            ReasonCode::FailedClosed => "markdown_failed_closed_total",
            ReasonCode::ConversionError => "markdown_errors_total",
            ReasonCode::MemoryBudgetExceeded => "markdown_errors_total",
            ReasonCode::Overload => "markdown_skipped_total",
            ReasonCode::InvalidDynconf => "markdown_errors_total",
            ReasonCode::DegradedSnapshot => "markdown_errors_total",
            ReasonCode::HeaderPlanApplyError => "markdown_errors_total",
            ReasonCode::StreamingMidFlightError => "markdown_errors_total",
            ReasonCode::BypassNoTransform => "markdown_skipped_total",
            ReasonCode::EncodingHeaderInvalid => "markdown_errors_total",
        }
    }

    /// Return the expected `log_decision()` callsite description.
    ///
    /// # Examples
    ///
    /// ```
    /// use nginx_markdown_converter::decision::reason_code::ReasonCode;
    ///
    /// assert_eq!(
    ///     ReasonCode::Converted.log_callsite(),
    ///     "body_filter: after successful conversion and downstream NGX_OK"
    /// );
    /// ```
    pub fn log_callsite(self) -> &'static str {
        match self {
            ReasonCode::Converted => {
                "body_filter: after successful conversion and downstream NGX_OK"
            }
            ReasonCode::SkippedAccept => {
                "header_filter: Accept negotiation determined text/html preferred"
            }
            ReasonCode::SkippedNoAccept => "header_filter: no Accept header present",
            ReasonCode::SkippedConditional => "header_filter: conditional request matched (304)",
            ReasonCode::DecompressionError => "body_filter: decompression error",
            ReasonCode::DecompressionBudgetExceeded => {
                "body_filter: decompression output exceeded budget"
            }
            ReasonCode::DecompressionFormatError => "body_filter: invalid compression format",
            ReasonCode::DecompressionTruncatedInput => "body_filter: truncated compressed input",
            ReasonCode::DecompressionIoError => "body_filter: decompression I/O error",
            ReasonCode::Timeout => "body_filter: timeout",
            ReasonCode::BudgetExceeded => "body_filter: budget exceeded",
            ReasonCode::ReplayError => "body_filter: replay error",
            ReasonCode::SkippedAcceptReject => {
                "header_filter: Accept explicitly rejects text/markdown (q=0)"
            }
            ReasonCode::FfiPanic => "body_filter: FFI panic",
            ReasonCode::NotEligible => {
                "header_filter: response not eligible (method/status/content-type)"
            }
            ReasonCode::Disabled => "header_filter: module disabled for this location",
            ReasonCode::FailedOpen => "body_filter: fail-open path triggered",
            ReasonCode::FailedClosed => "body_filter: fail-closed path triggered",
            ReasonCode::ConversionError => "body_filter: conversion error",
            ReasonCode::MemoryBudgetExceeded => "body_filter: memory budget exceeded",
            ReasonCode::Overload => "header_filter: inflight guard overload",
            ReasonCode::InvalidDynconf => "header_filter: invalid dynconf",
            ReasonCode::DegradedSnapshot => "header_filter: degraded dynconf snapshot",
            ReasonCode::HeaderPlanApplyError => "header_filter: header plan apply error",
            ReasonCode::StreamingMidFlightError => "body_filter: streaming mid-flight error",
            ReasonCode::BypassNoTransform => "header_filter: no-transform bypass",
            ReasonCode::EncodingHeaderInvalid => "body_filter: malformed Content-Encoding grammar",
        }
    }

    /// Return the numeric discriminant value for FFI transport.
    ///
    /// # Examples
    ///
    /// ```
    /// use nginx_markdown_converter::decision::reason_code::ReasonCode;
    ///
    /// assert_eq!(ReasonCode::Converted.discriminant(), 0);
    /// assert_eq!(ReasonCode::Timeout.discriminant(), 9);
    /// ```
    pub fn discriminant(self) -> u32 {
        self as u32
    }

    /// Attempt to construct a `ReasonCode` from its numeric discriminant.
    ///
    /// Returns `None` if the value does not correspond to a known variant.
    ///
    /// # Examples
    ///
    /// ```
    /// use nginx_markdown_converter::decision::reason_code::ReasonCode;
    ///
    /// assert_eq!(ReasonCode::from_discriminant(0), Some(ReasonCode::Converted));
    /// assert_eq!(ReasonCode::from_discriminant(255), None);
    /// ```
    pub fn from_discriminant(value: u32) -> Option<Self> {
        match value {
            0 => Some(ReasonCode::Converted),
            1 => Some(ReasonCode::SkippedAccept),
            2 => Some(ReasonCode::SkippedNoAccept),
            3 => Some(ReasonCode::SkippedConditional),
            4 => Some(ReasonCode::DecompressionError),
            5 => Some(ReasonCode::DecompressionBudgetExceeded),
            6 => Some(ReasonCode::DecompressionFormatError),
            7 => Some(ReasonCode::DecompressionTruncatedInput),
            8 => Some(ReasonCode::DecompressionIoError),
            9 => Some(ReasonCode::Timeout),
            10 => Some(ReasonCode::BudgetExceeded),
            11 => Some(ReasonCode::ReplayError),
            12 => Some(ReasonCode::SkippedAcceptReject),
            13 => Some(ReasonCode::FfiPanic),
            14 => Some(ReasonCode::NotEligible),
            15 => Some(ReasonCode::Disabled),
            16 => Some(ReasonCode::FailedOpen),
            17 => Some(ReasonCode::FailedClosed),
            18 => Some(ReasonCode::ConversionError),
            19 => Some(ReasonCode::MemoryBudgetExceeded),
            20 => Some(ReasonCode::Overload),
            21 => Some(ReasonCode::InvalidDynconf),
            22 => Some(ReasonCode::DegradedSnapshot),
            23 => Some(ReasonCode::HeaderPlanApplyError),
            24 => Some(ReasonCode::StreamingMidFlightError),
            25 => Some(ReasonCode::BypassNoTransform),
            26 => Some(ReasonCode::EncodingHeaderInvalid),
            _ => None,
        }
    }
}

/// Get the string representation of a reason code by its numeric value.
///
/// Returns a pointer to a static string and writes the length to `out_len`.
/// Returns NULL if the discriminant is invalid.
///
/// # Safety
///
/// The caller must ensure that `out_len` either is NULL or points to
/// writable storage for a `usize`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn markdown_reason_code_str(code: u32, out_len: *mut usize) -> *const u8 {
    match ReasonCode::from_discriminant(code) {
        Some(rc) => {
            let s = rc.as_str();
            if !out_len.is_null() {
                unsafe { *out_len = s.len() };
            }
            s.as_ptr()
        }
        None => {
            if !out_len.is_null() {
                unsafe { *out_len = 0 };
            }
            std::ptr::null()
        }
    }
}

/// Get the Prometheus metric key for a reason code by its numeric value.
///
/// Returns a pointer to a static string and writes the length to `out_len`.
/// Returns NULL if the discriminant is invalid.
///
/// # Safety
///
/// The caller must ensure that `out_len` either is NULL or points to
/// writable storage for a `usize`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn markdown_reason_code_metric_key(
    code: u32,
    out_len: *mut usize,
) -> *const u8 {
    match ReasonCode::from_discriminant(code) {
        Some(rc) => {
            let s = rc.metric_key();
            if !out_len.is_null() {
                unsafe { *out_len = s.len() };
            }
            s.as_ptr()
        }
        None => {
            if !out_len.is_null() {
                unsafe { *out_len = 0 };
            }
            std::ptr::null()
        }
    }
}

/// Return the total number of defined reason codes.
///
/// C callers can use this to verify they handle all variants.
#[unsafe(no_mangle)]
pub extern "C" fn markdown_reason_code_count() -> u32 {
    REASON_CODE_COUNT as u32
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Verify that ALL array length matches REASON_CODE_COUNT.
    #[test]
    fn test_all_array_length_matches_count() {
        assert_eq!(
            ALL.len(),
            REASON_CODE_COUNT,
            "ALL array length ({}) must equal REASON_CODE_COUNT ({})",
            ALL.len(),
            REASON_CODE_COUNT
        );
    }

    /// Verify that every variant in ALL has a unique discriminant.
    #[test]
    fn test_discriminants_unique() {
        let mut seen = HashSet::new();
        for rc in &ALL {
            let d = rc.discriminant();
            assert!(seen.insert(d), "Duplicate discriminant {} for {:?}", d, rc);
        }
    }

    /// Verify that every variant in ALL has a unique string representation.
    #[test]
    fn test_strings_unique() {
        let mut seen = HashSet::new();
        for rc in &ALL {
            let s = rc.as_str();
            assert!(seen.insert(s), "Duplicate string '{}' for {:?}", s, rc);
        }
    }

    /// Verify that all string representations are lowercase snake_case.
    #[test]
    fn test_strings_are_lowercase_snake_case() {
        let re = regex::Regex::new(r"^[a-z][a-z0-9_]*$").unwrap();
        for rc in &ALL {
            let s = rc.as_str();
            assert!(!s.is_empty(), "{:?} has empty string", rc);
            assert!(
                re.is_match(s),
                "String '{}' for {:?} does not match lowercase snake_case pattern",
                s,
                rc
            );
        }
    }

    /// Verify that exactly 5 unified metric families are used.
    #[test]
    fn test_metric_keys_unified_families() {
        let mut families: HashSet<&str> = HashSet::new();
        for rc in &ALL {
            families.insert(rc.metric_key());
        }
        assert_eq!(
            families.len(),
            5,
            "Expected exactly 5 unified metric families, got {:?}",
            families
        );
    }

    /// Verify round-trip: discriminant -> from_discriminant -> same variant.
    #[test]
    fn test_from_discriminant_roundtrip() {
        for rc in &ALL {
            let d = rc.discriminant();
            let recovered = ReasonCode::from_discriminant(d);
            assert_eq!(recovered, Some(*rc));
        }
    }

    /// Verify that from_discriminant returns None for invalid values.
    #[test]
    fn test_from_discriminant_invalid() {
        assert_eq!(ReasonCode::from_discriminant(255), None);
        assert_eq!(ReasonCode::from_discriminant(u32::MAX), None);
    }

    /// Closure test: verify discriminant range is contiguous 0..COUNT-1.
    #[test]
    fn test_discriminant_range_contiguous() {
        let mut discriminants: Vec<u32> = ALL.iter().map(|rc| rc.discriminant()).collect();
        discriminants.sort();
        for (i, d) in discriminants.iter().enumerate() {
            assert_eq!(*d, i as u32, "Expected discriminant {} at index {}", i, i);
        }
    }

    /// FFI function test: markdown_reason_code_str returns correct data.
    #[test]
    fn test_ffi_reason_code_str() {
        for rc in &ALL {
            let mut len: usize = 0;
            let ptr = unsafe { markdown_reason_code_str(rc.discriminant(), &mut len) };
            assert!(!ptr.is_null(), "NULL returned for {:?}", rc);
            assert_eq!(len, rc.as_str().len());
            let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
            let s = std::str::from_utf8(slice).unwrap();
            assert_eq!(s, rc.as_str());
        }
    }

    /// FFI function test: markdown_reason_code_count returns correct value.
    #[test]
    fn test_ffi_reason_code_count() {
        assert_eq!(markdown_reason_code_count(), REASON_CODE_COUNT as u32);
    }

    /// Verify the enum size is suitable for FFI (repr(u8) single-byte).
    #[test]
    fn test_enum_size_for_ffi() {
        assert_eq!(std::mem::size_of::<ReasonCode>(), 1);
        assert_eq!(std::mem::align_of::<ReasonCode>(), 1);
    }

    /// Verify that every variant has a non-empty log_callsite().
    #[test]
    fn test_log_callsite_non_empty() {
        for rc in &ALL {
            assert!(
                !rc.log_callsite().is_empty(),
                "{:?} has empty log_callsite",
                rc
            );
        }
    }

    /// Verify that log_callsite() descriptions indicate a valid filter phase.
    #[test]
    fn test_log_callsite_has_valid_phase() {
        for rc in &ALL {
            let callsite = rc.log_callsite();
            assert!(
                callsite.starts_with("header_filter:") || callsite.starts_with("body_filter:"),
                "{:?} log_callsite must start with header_filter: or body_filter:",
                rc
            );
        }
    }
}
