/*
 * Generated by tools/reason-codegen/generate.py — DO NOT EDIT.
 * Source: components/rust-converter/reason_registry.toml (SHA-256: bd302c40372a4077...)
 *
 * This file provides generated reason metadata and stable discriminants
 * consumed by the C diagnostics renderer and reason accessors. The TOML
 * registry remains the only source; this header replaces former
 * hand-maintained diagnostics reason and compatibility tables.
 */
#ifndef MARKDOWN_REASON_META_H
#define MARKDOWN_REASON_META_H

#include <ngx_config.h>
#include <ngx_core.h>

typedef struct {
    const char    *key;
    const char    *outcome;
    const char    *stage;
    const char    *error_origin;
} markdown_reason_meta_t;

#define MARKDOWN_REASON_META_COUNT 27

/* Stable discriminants projected from the canonical registry. */
#define MARKDOWN_REASON_CODE_CONVERTED 0
#define MARKDOWN_REASON_CODE_SKIPPED_ACCEPT 1
#define MARKDOWN_REASON_CODE_SKIPPED_NO_ACCEPT 2
#define MARKDOWN_REASON_CODE_SKIPPED_CONDITIONAL 3
#define MARKDOWN_REASON_CODE_DECOMPRESSION_ERROR 4
#define MARKDOWN_REASON_CODE_DECOMPRESSION_BUDGET_EXCEEDED 5
#define MARKDOWN_REASON_CODE_DECOMPRESSION_FORMAT_ERROR 6
#define MARKDOWN_REASON_CODE_DECOMPRESSION_TRUNCATED_INPUT 7
#define MARKDOWN_REASON_CODE_DECOMPRESSION_IO_ERROR 8
#define MARKDOWN_REASON_CODE_TIMEOUT 9
#define MARKDOWN_REASON_CODE_BUDGET_EXCEEDED 10
#define MARKDOWN_REASON_CODE_REPLAY_ERROR 11
#define MARKDOWN_REASON_CODE_SKIPPED_ACCEPT_REJECT 12
#define MARKDOWN_REASON_CODE_FFI_PANIC 13
#define MARKDOWN_REASON_CODE_NOT_ELIGIBLE 14
#define MARKDOWN_REASON_CODE_DISABLED 15
#define MARKDOWN_REASON_CODE_FAILED_OPEN 16
#define MARKDOWN_REASON_CODE_FAILED_CLOSED 17
#define MARKDOWN_REASON_CODE_CONVERSION_ERROR 18
#define MARKDOWN_REASON_CODE_MEMORY_BUDGET_EXCEEDED 19
#define MARKDOWN_REASON_CODE_OVERLOAD 20
#define MARKDOWN_REASON_CODE_INVALID_DYNCONF 21
#define MARKDOWN_REASON_CODE_DEGRADED_SNAPSHOT 22
#define MARKDOWN_REASON_CODE_HEADER_PLAN_APPLY_ERROR 23
#define MARKDOWN_REASON_CODE_STREAMING_MID_FLIGHT_ERROR 24
#define MARKDOWN_REASON_CODE_BYPASS_NO_TRANSFORM 25
#define MARKDOWN_REASON_CODE_ENCODING_HEADER_INVALID 26

/*
 * Reason metadata table (index = discriminant).
 * Entry MARKDOWN_REASON_META_COUNT is the unknown sentinel.
 */
#ifdef MARKDOWN_REASON_META_DEFINE
const markdown_reason_meta_t
    markdown_reason_meta[MARKDOWN_REASON_META_COUNT + 1] = {
    [0] = { "converted", "converted", "conversion", "none" },
    [1] = { "skipped_accept", "skipped", "eligibility", "none" },
    [2] = { "skipped_no_accept", "skipped", "eligibility", "none" },
    [3] = { "skipped_conditional", "skipped", "eligibility", "none" },
    [4] = { "decompression_error", "failed_closed", "decompression", "internal" },
    [5] = { "decompression_budget_exceeded", "failed_closed", "decompression", "memory_budget" },
    [6] = { "decompression_format_error", "failed_closed", "decompression", "format" },
    [7] = { "decompression_truncated_input", "failed_closed", "decompression", "truncated" },
    [8] = { "decompression_io_error", "failed_closed", "decompression", "downstream" },
    [9] = { "timeout", "failed_closed", "parsing", "timeout" },
    [10] = { "budget_exceeded", "failed_closed", "parsing", "memory_budget" },
    [11] = { "replay_error", "failed_closed", "precommit", "allocation" },
    [12] = { "skipped_accept_reject", "skipped", "eligibility", "none" },
    [13] = { "ffi_panic", "failed_closed", "conversion", "internal" },
    [14] = { "not_eligible", "skipped", "eligibility", "none" },
    [15] = { "disabled", "skipped", "eligibility", "none" },
    [16] = { "failed_open", "failed_open", "delivery", "downstream" },
    [17] = { "failed_closed", "failed_closed", "delivery", "downstream" },
    [18] = { "conversion_error", "failed_closed", "conversion", "internal" },
    [19] = { "memory_budget_exceeded", "failed_closed", "conversion", "memory_budget" },
    [20] = { "overload", "skipped", "eligibility", "allocation" },
    [21] = { "invalid_dynconf", "failed_closed", "dynconf", "format" },
    [22] = { "degraded_snapshot", "failed_closed", "dynconf", "internal" },
    [23] = { "header_plan_apply_error", "failed_closed", "precommit", "invariant" },
    [24] = { "streaming_mid_flight_error", "aborted", "delivery", "internal" },
    [25] = { "bypass_no_transform", "skipped", "eligibility", "none" },
    [26] = { "encoding_header_invalid", "failed_closed", "decompression", "format" },
    [27] = { "unknown", "failed_closed", "delivery", "internal" },
};
#else
extern const markdown_reason_meta_t
    markdown_reason_meta[MARKDOWN_REASON_META_COUNT + 1];
#endif

/*
 * Legacy uppercase aliases retained for diagnostics compatibility.
 * This table is generated from each reason's legacy_keys field.
 */
typedef struct {
    const char    *key;
    ngx_int_t      code;
} markdown_reason_alias_t;

#define MARKDOWN_REASON_ALIAS_COUNT 26

#ifdef MARKDOWN_REASON_META_DEFINE
const markdown_reason_alias_t
    markdown_reason_aliases[MARKDOWN_REASON_ALIAS_COUNT > 0 ? MARKDOWN_REASON_ALIAS_COUNT : 1] = {
    { "CONVERTED", 0 },
    { "ELIGIBLE_CONVERTED", 0 },
    { "SKIPPED_ACCEPT", 1 },
    { "SKIP_ACCEPT", 1 },
    { "SKIPPED_NO_ACCEPT", 2 },
    { "SKIPPED_CONDITIONAL", 3 },
    { "FAILED_DECOMPRESSION", 4 },
    { "DECOMPRESSION_BUDGET_EXCEEDED", 5 },
    { "DECOMPRESSION_FORMAT_ERROR", 6 },
    { "DECOMPRESSION_TRUNCATED_INPUT", 7 },
    { "DECOMPRESSION_IO_ERROR", 8 },
    { "PARSE_TIMEOUT", 9 },
    { "PARSE_BUDGET_EXCEEDED", 10 },
    { "REPLAY_BUFFER_ERROR", 11 },
    { "SKIPPED_ACCEPT_REJECT", 12 },
    { "FFI_CALL_ERROR", 13 },
    { "FAIL_SYSTEM", 13 },
    { "NOT_ELIGIBLE", 14 },
    { "DISABLED", 15 },
    { "FAILED_OPEN", 16 },
    { "ELIGIBLE_FAILED_OPEN", 16 },
    { "FAILED_CLOSED", 17 },
    { "ELIGIBLE_FAILED_CLOSED", 17 },
    { "FAIL_CONVERSION", 18 },
    { "FAIL_RESOURCE_LIMIT", 19 },
    { "BYPASS_NO_TRANSFORM", 25 },
};
#else
extern const markdown_reason_alias_t
    markdown_reason_aliases[MARKDOWN_REASON_ALIAS_COUNT > 0 ? MARKDOWN_REASON_ALIAS_COUNT : 1];
#endif

#endif /* MARKDOWN_REASON_META_H */
