/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef NGINX_MARKDOWN_CONVERTER_H
#define NGINX_MARKDOWN_CONVERTER_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. */
/* Any manual changes will be overwritten on next build. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success - no error occurred.
 */
#define ERROR_SUCCESS 0

/**
 * HTML parsing failed (malformed HTML, invalid structure).
 */
#define ERROR_PARSE 1

/**
 * Character encoding error (invalid UTF-8, unsupported charset).
 */
#define ERROR_ENCODING 2

/**
 * Conversion timeout exceeded.
 */
#define ERROR_TIMEOUT 3

/**
 * Memory limit exceeded during conversion.
 */
#define ERROR_MEMORY_LIMIT 4

/**
 * Invalid input data (NULL pointers, invalid parameters).
 */
#define ERROR_INVALID_INPUT 5

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Memory budget exceeded during streaming conversion.
 */
#define ERROR_BUDGET_EXCEEDED 6
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Streaming engine requests fallback to full-buffer conversion (Pre-Commit only).
 */
#define ERROR_STREAMING_FALLBACK 7
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Error after the streaming engine has already emitted partial output (Post-Commit).
 */
#define ERROR_POST_COMMIT 8
#endif

/**
 * Internal error (unexpected condition, panic caught).
 */
#define ERROR_INTERNAL 99

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Maximum accumulated buffer size in bytes (64 MiB).
 */
#define IncrementalConverter_MAX_BUFFER_SIZE ((64 * 1024) * 1024)
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Opaque handle wrapping an [`IncrementalConverter`] for the C ABI.
 */
typedef struct IncrementalConverterHandle IncrementalConverterHandle;
#endif

/**
 * Opaque handle to a reusable Rust converter instance shared across FFI calls.
 *
 * This struct holds stateful components (ETag generator, token estimator) that
 * are reused across multiple conversions to avoid re-initialization overhead.
 * The handle is created via `markdown_converter_new()` and freed via
 * `markdown_converter_free()` on the C side.
 *
 * # Thread Safety
 *
 * This handle is NOT thread-safe. The caller must ensure exclusive access
 * when using a handle across multiple FFI calls.
 */
typedef struct MarkdownConverterHandle MarkdownConverterHandle;

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Opaque handle wrapping a [`StreamingConverter`] for the C ABI.
 */
typedef struct StreamingConverterHandle StreamingConverterHandle;
#endif

/**
 * Conversion options passed from C to Rust.
 */
typedef struct MarkdownOptions {
  /**
   * Markdown flavor selector.
   *
   * `0` selects CommonMark-compatible output, `1` selects the GFM
   * extension set, `2` selects MDX (experimental), `3` selects
   * Org-mode (experimental). Values outside 0-3 are rejected
   * during option decoding with `ConversionError::InvalidInput`.
   */
  uint32_t flavor;
  /**
   * Cooperative conversion timeout in milliseconds.
   *
   * `0` disables the deadline. The value is copied from C at call entry and
   * is not retained after the FFI call returns.
   */
  uint32_t timeout_ms;
  /**
   * Non-zero when Rust should generate a Markdown-variant ETag.
   */
  uint8_t generate_etag;
  /**
   * Non-zero when Rust should estimate token count/savings.
   */
  uint8_t estimate_tokens;
  /**
   * Non-zero when Rust should extract YAML front matter metadata.
   */
  uint8_t front_matter;
  /**
   * Borrowed Content-Type bytes from the C caller.
   *
   * Must either be NULL with `content_type_len == 0` or point to
   * `content_type_len` readable bytes for the duration of the FFI call.
   * Rust never takes ownership of this buffer.
   */
  const uint8_t *content_type;
  /**
   * Length in bytes of [`MarkdownOptions::content_type`].
   */
  uintptr_t content_type_len;
  /**
   * Borrowed base URL bytes used for resolving relative links.
   *
   * Must either be NULL with `base_url_len == 0` or point to
   * `base_url_len` readable UTF-8 bytes for the duration of the FFI call.
   * Rust copies any value it needs to retain.
   */
  const uint8_t *base_url;
  /**
   * Length in bytes of [`MarkdownOptions::base_url`].
   */
  uintptr_t base_url_len;
  /**
   * Streaming memory budget in bytes (0 = use default).
   *
   * When non-zero, the streaming converter uses this value as the
   * total memory budget instead of the compiled-in default (2 MiB).
   * Populated from the `markdown_streaming_budget` NGINX directive.
   */
  uint64_t streaming_budget;
  /**
   * Non-zero when noise region pruning is enabled at runtime.
   *
   * When non-zero, structural HTML regions matching the prune selectors
   * are excluded from output. Protection selectors override prune selectors.
   * Populated from the `markdown_prune_noise` NGINX directive.
   */
  uint32_t prune_noise;
  /**
   * Borrowed prune selector string from the C caller.
   *
   * Space-separated tag names for regions to prune (e.g., "nav footer aside").
   * Must either be NULL with `prune_selectors_len == 0` or point to
   * `prune_selector_len` readable UTF-8 bytes for the duration of the FFI call.
   * Rust never takes ownership of this buffer.
   */
  const uint8_t *prune_selectors;
  /**
   * Length in bytes of [`MarkdownOptions::prune_selectors`].
   */
  uintptr_t prune_selector_len;
  /**
   * Borrowed protection selector string from the C caller.
   *
   * Space-separated tag names for regions to protect from pruning.
   * An element matching both a prune selector and a protection selector
   * is kept (protection wins). Must either be NULL with
   * `prune_protection_selector_len == 0` or point to
   * `prune_protection_selector_len` readable UTF-8 bytes.
   */
  const uint8_t *prune_protection_selectors;
  /**
   * Length in bytes of [`MarkdownOptions::prune_protection_selectors`].
   */
  uintptr_t prune_protection_selector_len;
  /**
   * Unified memory budget in bytes (0 = use per-engine defaults).
   *
   * Currently enforced only by the streaming and incremental
   * conversion paths.  The full-buffer path relies on the
   * NGINX-side `max_size` limit for input bounding; the Rust
   * full-buffer converter does not check this budget internally.
   *
   * When non-zero and no per-engine explicit budget is set, this
   * value overrides the default budget for streaming/incremental
   * engines. Priority: per-engine explicit > unified > default.
   * Populated from the `markdown_memory_budget` NGINX directive.
   */
  uint64_t memory_budget;
  /**
   * LLM provider for token estimation (0=default, 1=openai-gpt, 2=anthropic-claude,
   * 3=google-gemini, 4=meta-llama).
   *
   * When non-zero and `estimate_tokens` is enabled, the provider's
   * characteristic chars-per-token ratio overrides the default 4.0.
   * Populated from the `markdown_llm_provider` NGINX directive.
   */
  uint8_t llm_provider;
  /**
   * Explicit chars-per-token ratio for token estimation (0.0 = use default/provider).
   *
   * When non-zero, this value overrides both the default 4.0 and the
   * provider-specific ratio.  Stored as a fixed-point value: actual
   * ratio = `chars_per_token_fixed / 10.0` (e.g., 38 = 3.8 chars/token).
   * Populated from the `markdown_chars_per_token` NGINX directive.
   */
  uint8_t chars_per_token_fixed;
} MarkdownOptions;

/**
 * Conversion result returned from Rust to C.
 */
typedef struct MarkdownResult {
  /**
   * Rust-owned Markdown output buffer.
   *
   * Valid only when `error_code == ERROR_SUCCESS`. The C caller must release
   * it with `markdown_result_free()` and must not mutate it.
   */
  uint8_t *markdown;
  /**
   * Length in bytes of [`MarkdownResult::markdown`].
   */
  uintptr_t markdown_len;
  /**
   * Rust-owned ETag bytes, or NULL when ETag generation was disabled.
   *
   * Valid only when `etag_len > 0` and released by `markdown_result_free()`.
   */
  uint8_t *etag;
  /**
   * Length in bytes of [`MarkdownResult::etag`].
   */
  uintptr_t etag_len;
  /**
   * Estimated token count for successful conversions.
   *
   * `0` means token estimation was disabled or no estimate was produced.
   */
  uint32_t token_estimate;
  /**
   * FFI error code; `ERROR_SUCCESS` means the output fields are valid.
   */
  uint32_t error_code;
  /**
   * Rust-owned UTF-8 diagnostic message for non-success results.
   *
   * The pointer may be NULL when no diagnostic is available. Release through
   * `markdown_result_free()` together with the rest of the result.
   */
  uint8_t *error_message;
  /**
   * Length in bytes of [`MarkdownResult::error_message`].
   */
  uintptr_t error_len;
  /**
   * Peak working-set memory estimate during streaming conversion (bytes).
   *
   * This is derived from converter-owned resident state and is not
   * a process RSS/high-water-mark measurement.
   * Populated by `markdown_streaming_finalize` from
   * `StreamingStats.peak_memory_estimate`.
   */
  uintptr_t peak_memory_estimate;
} MarkdownResult;

/**
 * Allocate a new converter handle for use across multiple FFI calls.
 *
 * # Safety
 *
 * Returns a raw pointer that must eventually be freed with
 * `markdown_converter_free()`.
 *
 * # Returns
 *
 * Returns a non-NULL handle on success. Returns NULL only when
 * `MarkdownConverterHandle::new()` panics and that panic is caught by
 * `catch_unwind()`. On stable Rust, allocator out-of-memory aborts the process
 * instead of unwinding, so OOM is not caught here and does not produce NULL.
 */
struct MarkdownConverterHandle *markdown_converter_new(void);

/**
 * Convert an HTML byte buffer into Markdown using the provided converter handle.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `handle` points to a live converter created by `markdown_converter_new()`
 * - `options` points to a valid `MarkdownOptions`
 * - `result` points to writable storage for a `MarkdownResult` whose owned
 *   buffers are either NULL/zero-length or were previously returned by this API
 * - `html` either points to `html_len` readable bytes or is NULL when `html_len == 0`
 * - `result` is not concurrently mutated while this function is executing
 */
void markdown_convert(struct MarkdownConverterHandle *handle,
                      const uint8_t *html,
                      uintptr_t html_len,
                      const struct MarkdownOptions *options,
                      struct MarkdownResult *result);

/**
 * Release buffers owned by a `MarkdownResult` and reset it to the empty state.
 *
 * # Safety
 *
 * The caller must ensure that `result` either is NULL or points to a valid
 * `MarkdownResult` previously initialized by `markdown_convert()`. Passing the
 * same result twice is allowed because the function resets pointers to NULL.
 */
void markdown_result_free(struct MarkdownResult *result);

/**
 * Destroy a converter handle previously returned by `markdown_converter_new()`.
 *
 * # Safety
 *
 * The caller must ensure that `handle` either is NULL or was returned by
 * `markdown_converter_new()` and has not already been freed. The handle must
 * not be used after this call returns.
 */
void markdown_converter_free(struct MarkdownConverterHandle *handle);

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Create a new incremental converter handle for incremental Markdown processing.
 *
 * The returned handle is an opaque pointer owned by the caller and must be
 * either finalized with `markdown_incremental_finalize` or freed with
 * `markdown_incremental_free`.
 *
 * # Safety
 *
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 * - The returned pointer is heap-allocated; the caller owns it and must not
 *   dereference it except via the `markdown_incremental_*` family of functions.
 *
 * # Returns
 *
 * A non-NULL handle on success, or NULL if `options` is NULL, if `MarkdownOptions`
 * cannot be decoded, or if an internal panic is caught.
 *
 * # Examples
 *
 * ```ignore
 * use nginx_markdown_converter::ffi::{MarkdownOptions, markdown_incremental_new, markdown_incremental_free};
 * // Construct and fully initialize MarkdownOptions for your environment.
 * let opts = MarkdownOptions {
 *     flavor: 0,
 *     timeout_ms: 0,
 *     generate_etag: 0,
 *     estimate_tokens: 0,
 *     front_matter: 0,
 *     content_type: std::ptr::null(),
 *     content_type_len: 0,
 *     base_url: std::ptr::null(),
 *     base_url_len: 0,
 *     streaming_budget: 0,
 *     prune_noise: 1,
 *     prune_selectors: std::ptr::null(),
 *     prune_selector_len: 0,
 *     prune_protection_selectors: std::ptr::null(),
 *     prune_protection_selector_len: 0,
 *     memory_budget: 0,
 *     llm_provider: 0,
 *     chars_per_token_fixed: 0,
 * };
 * let handle = unsafe { markdown_incremental_new(&opts) };
 * assert!(!handle.is_null());
 * // Either finalize to produce output or free when done without producing output.
 * unsafe { markdown_incremental_free(handle) };
 * ```
 */
struct IncrementalConverterHandle *markdown_incremental_new(const struct MarkdownOptions *options);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Buffers a provided input chunk for later conversion.
 *
 * Accepts an empty chunk (`data_len == 0`) as a no-op.
 *
 * # Safety
 *
 * * `handle` must be a live pointer returned by [`markdown_incremental_new`].
 * * `data` must point to at least `data_len` readable bytes, or be NULL when `data_len` is 0`.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure.
 *
 * # Examples
 *
 * ```ignore
 * use std::ptr;
 * use nginx_markdown_converter::ffi::{markdown_incremental_new, markdown_incremental_feed, markdown_incremental_free};
 * unsafe {
 *     let options = ptr::null(); // populate as needed
 *     let handle = markdown_incremental_new(options);
 *     if !handle.is_null() {
 *         // feed a chunk
 *         let _ = markdown_incremental_feed(handle, b"hello".as_ptr(), 5);
 *         // finalize or free the handle as appropriate
 *         markdown_incremental_free(handle);
 *     }
 * }
 * ```
 */
uint32_t markdown_incremental_feed(struct IncrementalConverterHandle *handle,
                                   const uint8_t *data,
                                   uintptr_t data_len);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Finalize an incremental converter, consume its handle, and write the conversion output or error into `result`.
 *
 * The call always consumes the provided `handle`; after this function returns (whether success, failure,
 * or internal panic) the handle is invalid and must not be used again or freed by the caller.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by `markdown_incremental_new` that has not already been
 *   finalized or freed. This function takes ownership of the handle and will free it during execution.
 * - `result` must be a valid, writable pointer to a `MarkdownResult`. Any buffers previously owned by
 *   `result` must either be NULL/zero-length or must have been previously returned by this API.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure. In all cases `result` is populated
 * with either the produced markdown (and optional ETag/token estimate) or an error code and message.
 *
 * # Examples
 *
 * ```ignore
 * use std::ptr::null_mut;
 * use nginx_markdown_converter::ffi::{markdown_incremental_finalize, ERROR_INVALID_INPUT};
 *
 * // Passing NULL result pointer is invalid and returns ERROR_INVALID_INPUT.
 * let code = unsafe { markdown_incremental_finalize(null_mut(), null_mut()) };
 * assert_eq!(code, ERROR_INVALID_INPUT);
 * ```
 */
uint32_t markdown_incremental_finalize(struct IncrementalConverterHandle *handle,
                                       struct MarkdownResult *result);
#endif

#if defined(MARKDOWN_INCREMENTAL_ENABLED)
/**
 * Frees an incremental converter handle without finalizing.
 *
 * Use this function to release resources when the conversion is being
 * abandoned (e.g. on error or cancellation).  If the handle has already
 * been consumed by [`markdown_incremental_finalize`], do **not** call
 * this function — `finalize` always consumes the handle regardless of
 * its return code, and calling `free` afterwards is a double-free.
 *
 * Passing NULL is a safe no-op.
 *
 * # Safety
 *
 * * `handle` must be NULL or a live pointer returned by
 *   [`markdown_incremental_new`] that has not been finalized or freed.
 */
void markdown_incremental_free(struct IncrementalConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Create a new streaming converter handle and return an explicit status code.
 *
 * This API is the recommended constructor for C callers that need actionable
 * failure classification. On success, `*out_handle` receives a non-NULL handle.
 * On error, `*out_handle` is set to NULL and the function returns an error code.
 *
 * # Safety
 *
 * - `out_handle` must be a valid, writable pointer to `*mut StreamingConverterHandle`.
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) on success
 * - `ERROR_INVALID_INPUT` (5) for NULL pointers or invalid options
 * - `ERROR_INTERNAL` (99) for caught panics
 */
uint32_t markdown_streaming_new_with_code(const struct MarkdownOptions *options,
                                          struct StreamingConverterHandle **out_handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Create a new streaming converter handle.
 *
 * The returned handle is an opaque pointer owned by the caller and must be
 * consumed by exactly one of `markdown_streaming_finalize`,
 * `markdown_streaming_abort`, or `markdown_streaming_free`.
 *
 * # Safety
 *
 * - `options` must point to a valid, properly aligned `MarkdownOptions` that
 *   remains readable for the duration of this call.
 * - The returned pointer is heap-allocated; the caller owns it and must not
 *   dereference it except via the `markdown_streaming_*` family of functions.
 *
 * # Returns
 *
 * A non-NULL handle on success, or NULL if `options` is NULL, if
 * `MarkdownOptions` cannot be decoded, or if an internal panic is caught.
 */
struct StreamingConverterHandle *markdown_streaming_new(const struct MarkdownOptions *options);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Feed a chunk of HTML input and receive any ready Markdown output.
 *
 * On success (`ERROR_SUCCESS`), `*out_data` and `*out_len` are set to the
 * Markdown output buffer allocated by Rust. The caller must free this buffer
 * via [`markdown_streaming_output_free`]. If no output is ready, `*out_data`
 * is NULL and `*out_len` is 0.
 *
 * On error, `*out_data` is set to NULL and `*out_len` to 0. The returned
 * error code indicates the failure type.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by [`markdown_streaming_new`].
 * - `data` must point to at least `data_len` readable bytes, or be NULL
 *   when `data_len` is 0.
 * - `out_data` must be a valid, writable pointer to `*mut u8`.
 * - `out_len` must be a valid, writable pointer to `usize`.
 *
 * # Returns
 *
 * - `ERROR_SUCCESS` (0) on success
 * - `ERROR_STREAMING_FALLBACK` (7) for pre-commit fallback signal
 * - `ERROR_BUDGET_EXCEEDED` (6) for memory budget exceeded
 * - `ERROR_POST_COMMIT` (8) for post-commit error
 * - `ERROR_TIMEOUT` (3) for timeout
 * - `ERROR_INVALID_INPUT` (5) for NULL handle or output pointers
 * - `ERROR_INTERNAL` (99) for caught panics
 */
uint32_t markdown_streaming_feed(struct StreamingConverterHandle *handle,
                                 const uint8_t *data,
                                 uintptr_t data_len,
                                 uint8_t **out_data,
                                 uintptr_t *out_len);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Finalize a streaming conversion, consume the handle, and write the result.
 *
 * This call always consumes the provided `handle`; after this function
 * returns (whether success, failure, or internal panic) the handle is
 * invalid and must not be used again or freed by the caller.
 *
 * # Safety
 *
 * - `handle` must be a live pointer returned by `markdown_streaming_new`
 *   that has not already been finalized, aborted, or freed.
 * - `result` must be a valid, writable pointer to a `MarkdownResult`. Any
 *   buffers previously owned by `result` must either be NULL/zero-length
 *   or must have been previously returned by this API.
 *
 * # Returns
 *
 * `ERROR_SUCCESS` (0) on success, or a non-zero error code on failure.
 * In all cases `result` is populated with either the produced markdown
 * (and optional ETag/token estimate) or an error code and message.
 */
uint32_t markdown_streaming_finalize(struct StreamingConverterHandle *handle,
                                     struct MarkdownResult *result);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Abort a streaming conversion and release all Rust resources.
 *
 * Use this function when the conversion must be abandoned (e.g. client
 * abort or unrecoverable error). This always consumes the handle.
 *
 * Passing NULL is a safe no-op.
 *
 * # Safety
 *
 * - `handle` must be NULL or a live pointer returned by
 *   [`markdown_streaming_new`] that has not been finalized, aborted,
 *   or freed.
 */
void markdown_streaming_abort(struct StreamingConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Free a streaming converter handle without finalizing.
 *
 * Use this function to release resources when the conversion is being
 * abandoned in an error path where neither `finalize` nor `abort` was
 * called. If the handle has already been consumed by `finalize` or
 * `abort`, do **not** call this function — that would be a double-free.
 *
 * Passing NULL is a safe no-op.
 *
 * This delegates to [`markdown_streaming_abort`] which has identical
 * semantics (both consume the handle by dropping it).
 *
 * # Safety
 *
 * - `handle` must be NULL or a live pointer returned by
 *   [`markdown_streaming_new`] that has not been finalized, aborted,
 *   or freed.
 */
void markdown_streaming_free(struct StreamingConverterHandle *handle);
#endif

#if defined(MARKDOWN_STREAMING_ENABLED)
/**
 * Free a Markdown output buffer returned by [`markdown_streaming_feed`].
 *
 * The `data` pointer and `len` must be exactly the values written to
 * `out_data` and `out_len` by a previous `feed` call. Passing NULL/0
 * is a safe no-op.
 *
 * # Safety
 *
 * - `data` must be NULL or a pointer previously returned via
 *   `markdown_streaming_feed`'s `out_data` parameter.
 * - `len` must be the corresponding `out_len` value.
 * - Each (data, len) pair must be freed exactly once.
 */
void markdown_streaming_output_free(uint8_t *data, uintptr_t len);
#endif

#endif  /* NGINX_MARKDOWN_CONVERTER_H */
