/*
 * Generated by tools/reason-codegen/generate.py — DO NOT EDIT.
 * Source: components/rust-converter/reason_registry.toml (SHA-256: 6d395a04ca766c4b...)
 *
 * This file provides the canonical reason metadata table consumed
 * by the C diagnostics renderer. It is the single C-side source of
 * truth for outcome/stage/origin mappings, replacing the former
 * hand-maintained ngx_http_markdown_diag_reason_meta[] table.
 */
#ifndef MARKDOWN_REASON_META_H
#define MARKDOWN_REASON_META_H

#include <ngx_config.h>
#include <ngx_core.h>

typedef struct {
    const char    *key;
    const char    *outcome;
    const char    *stage;
    const char    *error_origin;
} markdown_reason_meta_t;

#define MARKDOWN_REASON_META_COUNT 27

/*
 * Reason metadata table (index = discriminant).
 * Entry MARKDOWN_REASON_META_COUNT is the unknown sentinel.
 */
static const markdown_reason_meta_t
    markdown_reason_meta[MARKDOWN_REASON_META_COUNT + 1] = {
    [0] = { "converted", "converted", "conversion", "none" },
    [1] = { "skipped_accept", "skipped", "eligibility", "none" },
    [2] = { "skipped_no_accept", "skipped", "eligibility", "none" },
    [3] = { "skipped_conditional", "skipped", "eligibility", "none" },
    [4] = { "decompression_error", "failed_closed", "decompression", "internal" },
    [5] = { "decompression_budget_exceeded", "failed_closed", "decompression", "memory_budget" },
    [6] = { "decompression_format_error", "failed_closed", "decompression", "format" },
    [7] = { "decompression_truncated_input", "failed_closed", "decompression", "truncated" },
    [8] = { "decompression_io_error", "failed_closed", "decompression", "downstream" },
    [9] = { "timeout", "failed_closed", "parsing", "timeout" },
    [10] = { "budget_exceeded", "failed_closed", "parsing", "memory_budget" },
    [11] = { "replay_error", "failed_closed", "precommit", "allocation" },
    [12] = { "skipped_accept_reject", "skipped", "eligibility", "none" },
    [13] = { "ffi_panic", "failed_closed", "conversion", "internal" },
    [14] = { "not_eligible", "skipped", "eligibility", "none" },
    [15] = { "disabled", "skipped", "eligibility", "none" },
    [16] = { "failed_open", "failed_open", "delivery", "downstream" },
    [17] = { "failed_closed", "failed_closed", "delivery", "downstream" },
    [18] = { "conversion_error", "failed_closed", "conversion", "internal" },
    [19] = { "memory_budget_exceeded", "failed_closed", "conversion", "memory_budget" },
    [20] = { "overload", "skipped", "eligibility", "allocation" },
    [21] = { "invalid_dynconf", "failed_closed", "dynconf", "format" },
    [22] = { "degraded_snapshot", "failed_closed", "dynconf", "internal" },
    [23] = { "header_plan_apply_error", "failed_closed", "precommit", "invariant" },
    [24] = { "streaming_mid_flight_error", "aborted", "delivery", "internal" },
    [25] = { "bypass_no_transform", "skipped", "eligibility", "none" },
    [26] = { "encoding_header_invalid", "failed_closed", "decompression", "format" },
    [27] = { "unknown", "failed_closed", "delivery", "internal" },
};

#endif /* MARKDOWN_REASON_META_H */
