/*
 * DO NOT EDIT — generated by tools/reason-codegen/generate.py
 * Source: components/rust-converter/reason_registry.toml
 * Source SHA-256: 992170682ff4562002c6b085380dc9098c53e87ef61a8db04bb23a4b1e474f06
 *
 * Regenerate with: python3 tools/reason-codegen/generate.py
 */


#include "ngx_http_markdown_reason_generated.h"

#include <stddef.h>


/*
 * Static string table for reason code snake_case names.
 */
static const char *reason_code_strings[] = {
    "converted",
    "skipped_accept",
    "skipped_no_accept",
    "skipped_conditional",
    "decompression_error",
    "decompression_budget_exceeded",
    "decompression_format_error",
    "decompression_truncated_input",
    "decompression_io_error",
    "timeout",
    "budget_exceeded",
    "replay_error",
    "skipped_accept_reject",
    "ffi_panic",
    "not_eligible",
    "disabled",
    "failed_open",
    "failed_closed",
    "conversion_error",
    "memory_budget_exceeded",
    "overload",
    "invalid_dynconf",
    "degraded_snapshot",
    "header_plan_apply_error",
    "streaming_mid_flight_error",
    "bypass_no_transform",
    "encoding_header_invalid",
};


/*
 * Static string table for reason code metric family names.
 */
static const char *reason_code_metric_keys[] = {
    "markdown_conversions_total",
    "markdown_skipped_total",
    "markdown_skipped_total",
    "markdown_skipped_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_skipped_total",
    "markdown_errors_total",
    "markdown_skipped_total",
    "markdown_skipped_total",
    "markdown_failed_open_total",
    "markdown_failed_closed_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_errors_total",
    "markdown_skipped_total",
    "markdown_errors_total",
};


/*
 * Return the snake_case string for a reason code discriminant.
 *
 * Returns NULL if code is out of range.
 */
const char *
reason_code_str(unsigned int code)
{
    if (code >= REASON_CODE_COUNT) {
        return NULL;
    }
    return reason_code_strings[code];
}


/*
 * Return the Prometheus metric family name for a reason code discriminant.
 *
 * Returns NULL if code is out of range.
 */
const char *
reason_code_metric_key(unsigned int code)
{
    if (code >= REASON_CODE_COUNT) {
        return NULL;
    }
    return reason_code_metric_keys[code];
}
