/*
 * DO NOT EDIT — generated by tools/reason-codegen/generate.py
 * Source: components/rust-converter/reason_registry.toml
 * Source SHA-256: 992170682ff4562002c6b085380dc9098c53e87ef61a8db04bb23a4b1e474f06
 *
 * Regenerate with: python3 tools/reason-codegen/generate.py
 */


#ifndef _NGX_HTTP_MARKDOWN_REASON_GENERATED_H_INCLUDED_
#define _NGX_HTTP_MARKDOWN_REASON_GENERATED_H_INCLUDED_


/*
 * Reason code discriminant constants matching the Rust ReasonCode enum.
 *
 * These are generated from components/rust-converter/reason_registry.toml
 * and must not be edited manually.
 */

#define REASON_CONVERTED                     0
#define REASON_SKIPPED_ACCEPT                1
#define REASON_SKIPPED_NO_ACCEPT             2
#define REASON_SKIPPED_CONDITIONAL           3
#define REASON_DECOMPRESSION_ERROR           4
#define REASON_DECOMPRESSION_BUDGET_EXCEEDED 5
#define REASON_DECOMPRESSION_FORMAT_ERROR    6
#define REASON_DECOMPRESSION_TRUNCATED_INPUT 7
#define REASON_DECOMPRESSION_IO_ERROR        8
#define REASON_TIMEOUT                       9
#define REASON_BUDGET_EXCEEDED               10
#define REASON_REPLAY_ERROR                  11
#define REASON_SKIPPED_ACCEPT_REJECT         12
#define REASON_FFI_PANIC                     13
#define REASON_NOT_ELIGIBLE                  14
#define REASON_DISABLED                      15
#define REASON_FAILED_OPEN                   16
#define REASON_FAILED_CLOSED                 17
#define REASON_CONVERSION_ERROR              18
#define REASON_MEMORY_BUDGET_EXCEEDED        19
#define REASON_OVERLOAD                      20
#define REASON_INVALID_DYNCONF               21
#define REASON_DEGRADED_SNAPSHOT             22
#define REASON_HEADER_PLAN_APPLY_ERROR       23
#define REASON_STREAMING_MID_FLIGHT_ERROR    24
#define REASON_BYPASS_NO_TRANSFORM           25
#define REASON_ENCODING_HEADER_INVALID       26

#define REASON_CODE_COUNT  27


/*
 * Accessor function declarations.
 *
 * reason_code_str() returns the snake_case string for a discriminant.
 * reason_code_metric_key() returns the Prometheus metric family name.
 */
const char *reason_code_str(unsigned int code);
const char *reason_code_metric_key(unsigned int code);


#endif /* _NGX_HTTP_MARKDOWN_REASON_GENERATED_H_INCLUDED_ */
