apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-markdown-config
data:
  markdown-snippet: |
    load_module modules/ngx_http_markdown_filter_module.so;
  markdown-filter: |
    markdown_filter on;
    markdown_flavor gfm;
    markdown_auto_decompress on;
    markdown_limits decompressed_size=10m;
    markdown_streaming auto;
